[package]
name = "quent-analyzer"
version.workspace = true
edition.workspace =  true
publish.workspace = true

[dependencies]
quent-dynamic-attributes = { path = "../dynamic-attributes" }
quent-events = { path = "../events" }
quent-time = { path = "../time" }
rustc-hash.workspace = true
smallvec = { workspace = true, features = ["serde"] }
thiserror.workspace = true
uuid.workspace=true

[dev-dependencies]
tempfile = "3"
