[package]
name = "quent-simulator-analyzer"
version.workspace = true
edition.workspace =  true
publish.workspace = true

[dependencies]
nvtx-analyzer = { path = "../../../../integrations/nvtx/analyzer" }
quent-analyzer = { path = "../../../../crates/analyzer" }
quent-dynamic-attributes = { path = "../../../../crates/dynamic-attributes" }
quent-events = { path = "../../../../crates/events" }
quent-query-engine-analyzer = { path = "../../../../domains/query_engine/analyzer" }
quent-query-engine-ui = { path = "../../../../domains/query_engine/ui" }
quent-time = { path = "../../../../crates/time" }
quent-ui = { path = "../../../../crates/ui" }
rustc-hash.workspace = true
smallvec.workspace = true
tracing.workspace = true
uuid.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nvtx-server = { path = "../../../../integrations/nvtx/server" }
quent-io = { path = "../../../../crates/io", default-features = false }
quent-query-engine-server = { path = "../../../../domains/query_engine/server" }
quent-simulator-store = { path = "../store" }
quent-store = { path = "../../../../crates/store", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
quent-simulator-store = { path = "../store", default-features = false }
