[package]
name = "quent-model-macros"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[features]
default = ["serde"]
serde = []

[dependencies]
convert_case = "0.11"
syn = { workspace = true, features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"
