# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "nvtx-bridge"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
nvtx-sys = { workspace = true }
nvtx-events = { path = "../events" }
nvtx-injection = { path = "../injection" }
quent-channel = { path = "../../../crates/channel" }
quent-instrumentation = { path = "../../../crates/instrumentation" }
quent-time = { path = "../../../crates/time" }
uuid = { workspace = true }
thiserror = { workspace = true }
quent-events = { path = "../../../crates/events" }
serde = { workspace = true }
