// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! PyO3 bridge for the Python integration example.
//!
//! The bridge module is generated by quent-codegen during build.rs into
//! OUT_DIR so that cargo fmt does not need to resolve generated code.

include!(concat!(env!("OUT_DIR"), "/pyo3_bridge.rs"));
