version: 2

multi-ecosystem-groups:
  quent-dependencies:
    schedule:
      interval: "weekly"

updates:
  - cooldown:
      default-days: 14
    directory: "/"
    multi-ecosystem-group: "quent-dependencies"
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    patterns:
      - "*"
  - cooldown:
      default-days: 14
    directories:
      - "/ui"
      - "/ui/examples/quent-pivot-table-panel"
      - "/crates/schema/ts"
    multi-ecosystem-group: "quent-dependencies"
    open-pull-requests-limit: 5
    package-ecosystem: "npm"
    patterns:
      - "*"
  - cooldown:
      default-days: 14
    directories:
      - "/"
      - "/crates/instrumentation-build/example"
    multi-ecosystem-group: "quent-dependencies"
    open-pull-requests-limit: 5
    package-ecosystem: "cargo"
    patterns:
      - "*"
