// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! CXX bridge instrumentation library for the C++ integration example.
//!
//! The bridge/ modules are generated by quent-codegen during build.rs.

#[allow(unused, clippy::all)]
mod bridge {
    pub mod context;
    pub mod job;
    pub mod task;
    pub mod thread_pool;
    pub mod uuid;
}
