services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: quent
    container_name: quent-simulator-server
    ports:
      - "8080:8080"
      - "7836:7836"
    restart: unless-stopped
    volumes:
      - ./data:/quent/data
    environment:
      QUENT_ANALYZER_CORS_ADDRESS: "http://localhost:5173"
    command: "/quent/quent-simulator-server --log-level debug --cors-address http://localhost:5173"

  simulator:
    image: quent
    container_name: quent-simulator
    depends_on:
      - server
    restart: "no"
    environment:
      QUENT_COLLECTOR_ADDRESS: "http://server:7836"
    command: "/quent/quent-simulator --num-query-groups 2 --num-queries 2 --num-workers 2 --num-threads 2 --num-tasks 128"
