version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: quent
    container_name: quent-simulator-server
    ports:
      - "8080:8080"
      - "7836:7836"
    restart: unless-stopped
    volumes:
      - ./data:/quent/data
    command: /quent/quent-simulator-server

  simulator:
    image: quent
    container_name: quent-simulator
    depends_on:
      - server
    restart: "no"
    environment:
      QUENT_COLLECTOR_ADDRESS: "http://server:7836"
    command: "/quent/quent-simulator --num-query-groups 2 --num-queries 2 --num-workers 2 --num-threads 2 --num-tasks 128"

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    image: quent-webserver
    container_name: quent-webserver
    depends_on:
      - server
    ports:
      - "8000:8000"
      - "5678:5678"  # Debugpy port
    restart: unless-stopped
    environment:
      QUENT_ANALYZER_ADDRESS: "http://server:8080"
      DEBUG_MODE: ${DEBUG_MODE:-false}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
    volumes:
      - ./webserver/webserver:/app/webserver
