version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: quent
    container_name: quent-server
    ports:
      - "8080:8080"
      - "7836:7836"
    restart: unless-stopped
    volumes:
      - ./data:/quent/data
    command: /quent/quent-server

  simulator:
    image: quent
    container_name: quent-simulator
    depends_on:
      - server
    restart: "no"
    environment:
      QUENT_COLLECTOR_ADDRESS: "http://server:7836"
    command: "/quent/simulator --num-query-groups 2 --num-queries 2 --num-workers 2 --num-threads 4 --num-tasks 32"

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    image: quent-webserver
    container_name: quent-webserver
    depends_on:
      - server
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      QUENT_ANALYZER_ADDRESS: "http://server:8080"
