[workspace]
name = "quent"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64"]
requires-pixi = ">=0.68"

[dependencies]
rust = ">=1.93"
rust-src = ">=1.93"
nodejs = ">=24.11.0"
pnpm = "=11.6.0"
libprotobuf = ">=5"
cmake = ">=3.24"
cxx-compiler = ">=1"
python = ">=3.11,<3.15"
maturin = ">=1.10,<2"
pytest = ">=8,<10"
ty = ">=0.0.34"
uv = ">=0.11.11"
