// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Generate a standalone wrapper crate that serves the quent UI for a model,
//! driven by its analyzer. Dependencies are git-pinned to the commits recorded
//! in the sidecar (clone, don't patch), so the analyzer and quent line up by
//! construction. For an in-repo model the analyzer and quent share one git
//! source+rev, which cargo deduplicates to a single checkout.

use std::path::Path;

use crate::error::Result;
use crate::spec::ViewerSpec;

/// Name of the generated wrapper package (also the built binary name).
pub const WRAPPER_PACKAGE: &str = "quent-open-viewer";

/// Env var the wrapper reads for the output root to serve: a directory whose
/// children are `<context-uuid>/` context directories.
pub const ROOT_ENV: &str = "QUENT_OPEN_ROOT";
/// Env var the wrapper reads for the TCP port to bind (`0` = ephemeral).
pub const PORT_ENV: &str = "QUENT_OPEN_PORT";

/// Write the wrapper crate (`Cargo.toml` + `src/main.rs`) into `crate_dir`.
pub fn generate(spec: &ViewerSpec, crate_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(crate_dir.join("src"))?;
    std::fs::write(crate_dir.join("Cargo.toml"), cargo_toml(spec))?;
    std::fs::write(crate_dir.join("src/main.rs"), main_rs(spec))?;
    Ok(())
}

/// The wrapper's `Cargo.toml`. quent crates are pinned to `quent.{remote,commit}`
/// and the analyzer to `analyzer.{remote,commit}`; the empty `[workspace]` table
/// keeps the generated crate out of any parent workspace.
fn cargo_toml(spec: &ViewerSpec) -> String {
    let quent = &spec.quent;
    let analyzer = &spec.analyzer;
    let format_feature = spec.format.extension();
    format!(
        r#"# Generated by quent-open. Do not edit.
[package]
name = "{WRAPPER_PACKAGE}"
version = "0.0.0"
edition = "2024"
publish = false

# Standalone: do not join any parent cargo workspace.
[workspace]

[dependencies]
quent-query-engine-server = {{ git = "{q_remote}", rev = "{q_commit}", features = ["ui"] }}
quent-query-engine-analyzer = {{ git = "{q_remote}", rev = "{q_commit}" }}
quent-exporter = {{ git = "{q_remote}", rev = "{q_commit}", features = ["{format_feature}"] }}
{analyzer_pkg} = {{ git = "{a_remote}", rev = "{a_commit}" }}
axum = "0.8"
tokio = {{ version = "1", features = ["macros", "net", "rt-multi-thread"] }}
uuid = "1"
"#,
        q_remote = quent.cargo_url(),
        q_commit = quent.commit,
        a_remote = analyzer.cargo_url(),
        a_commit = analyzer.commit,
        analyzer_pkg = spec.analyzer_package,
    )
}

/// The wrapper's `src/main.rs`: wire `<analyzer>::Viewer`'s analyzer + importer
/// into `analyzer_service_router` and serve it. The output root (a directory of
/// `<context-uuid>/` subdirs) and port come from the environment so the same
/// built binary serves any artifacts.
fn main_rs(spec: &ViewerSpec) -> String {
    format!(
        r#"// Generated by quent-open. Do not edit.
use std::path::PathBuf;

use quent_exporter::FileSystemFormat;
use quent_query_engine_analyzer::ui::QuentViewer;
use quent_query_engine_server::analyzer_cache::index_query_engines;
use quent_query_engine_server::analyzer_service_router;
use {analyzer_crate}::Viewer;

type Analyzer = <Viewer as QuentViewer>::Analyzer;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let root = PathBuf::from(std::env::var("{ROOT_ENV}")?);
    let port: u16 = std::env::var("{PORT_ENV}").ok().and_then(|p| p.parse().ok()).unwrap_or(0);
    let format = FileSystemFormat::{format_variant};

    let import_root = root.clone();
    let importer = move |id: uuid::Uuid| {{
        Ok(<Viewer as QuentViewer>::import_events(&import_root.join(id.to_string()), format)?)
    }};
    let lister_root = root.clone();
    let lister = move || index_query_engines(&lister_root, format);

    let router =
        analyzer_service_router::<Analyzer>(Box::new(importer), Box::new(lister), None)?;

    let listener = tokio::net::TcpListener::bind(("127.0.0.1", port)).await?;
    axum::serve(listener, router.into_make_service()).await?;
    Ok(())
}}
"#,
        analyzer_crate = spec.analyzer_crate(),
        format_variant = spec.format.variant(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::{Format, GitPin, ViewerSpec};
    use std::path::PathBuf;

    fn spec() -> ViewerSpec {
        ViewerSpec {
            root: PathBuf::from("/data/ctx"),
            format: Format::Msgpack,
            analyzer_package: "quent-simulator-analyzer".into(),
            quent: GitPin {
                remote: "https://example.com/quent".into(),
                commit: "quentcommit".into(),
            },
            analyzer: GitPin {
                remote: "https://example.com/sirius".into(),
                commit: "analyzercommit".into(),
            },
        }
    }

    #[test]
    fn cargo_toml_pins_quent_and_analyzer() {
        let toml = cargo_toml(&spec());
        assert!(
            toml.contains(r#"[workspace]"#),
            "must be a standalone workspace"
        );
        assert!(toml.contains(
            r#"quent-query-engine-server = { git = "https://example.com/quent", rev = "quentcommit", features = ["ui"] }"#
        ));
        assert!(
            toml.contains(r#"features = ["msgpack"]"#),
            "format feature on exporter"
        );
        assert!(toml.contains(
            r#"quent-simulator-analyzer = { git = "https://example.com/sirius", rev = "analyzercommit" }"#
        ));
    }

    #[test]
    fn main_rs_names_viewer_and_format() {
        let main = main_rs(&spec());
        assert!(main.contains("use quent_simulator_analyzer::Viewer;"));
        assert!(main.contains("FileSystemFormat::Msgpack"));
        assert!(main.contains("analyzer_service_router::<Analyzer>"));
    }
}
