// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Generate a standalone wrapper crate serving the quent UI for a model via
//! its analyzer. Dependencies are git-pinned to sidecar commits (clone, don't
//! patch), so analyzer and quent versions line up. For an in-repo model, both
//! share one git source+rev, which Cargo deduplicates to one checkout.

use std::collections::BTreeMap;
use std::path::Path;

use cargo_manifest::{
    Dependency, DependencyDetail, Edition, Manifest, MaybeInherited, Package, Publish, Workspace,
};
use quote::{format_ident, quote};

use crate::error::Result;
use crate::spec::ViewerSpec;

/// Name of the generated wrapper package (also the built binary name).
pub const WRAPPER_PACKAGE: &str = "quent-open-viewer";

/// Wrapper env var for the output root: a directory of `<context-uuid>/`
/// context directories.
pub const ROOT_ENV: &str = "QUENT_OPEN_ROOT";
/// Env var the wrapper reads for the `ip:port` socket address to bind.
pub const ADDR_ENV: &str = "QUENT_OPEN_ADDR";

/// Write the wrapper crate (`Cargo.toml` + `src/main.rs`) into `crate_dir`.
pub fn generate(spec: &ViewerSpec, crate_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(crate_dir.join("src"))?;
    std::fs::write(crate_dir.join("Cargo.toml"), cargo_toml(spec))?;
    std::fs::write(crate_dir.join("src/main.rs"), main_rs(spec))?;
    Ok(())
}

/// A git-pinned dependency, with optional features.
fn git_dep(url: String, rev: &str, features: &[&str]) -> Dependency {
    Dependency::Detailed(DependencyDetail {
        git: Some(url),
        rev: Some(rev.to_string()),
        features: (!features.is_empty()).then(|| features.iter().map(|f| f.to_string()).collect()),
        ..Default::default()
    })
}

/// Wrapper `Cargo.toml`, built with `cargo-manifest`: pin quent crates to
/// `quent.{remote,commit}` and the analyzer to `analyzer.{remote,commit}`; the
/// empty `[workspace]` keeps the generated crate out of any parent workspace.
fn cargo_toml(spec: &ViewerSpec) -> String {
    let quent = spec.quent.cargo_url();
    let q_rev = spec.quent.commit.as_str();
    let dependencies = BTreeMap::from([
        (
            "quent-query-engine-server".to_string(),
            git_dep(quent.clone(), q_rev, &["ui"]),
        ),
        (
            "quent-query-engine-analyzer".to_string(),
            git_dep(quent.clone(), q_rev, &[]),
        ),
        (
            "quent-exporter".to_string(),
            git_dep(quent, q_rev, &[spec.format.extension()]),
        ),
        (
            spec.analyzer_package.clone(),
            git_dep(spec.analyzer.cargo_url(), &spec.analyzer.commit, &[]),
        ),
        ("axum".to_string(), Dependency::Simple("0.8".to_string())),
        (
            "tokio".to_string(),
            Dependency::Detailed(DependencyDetail {
                version: Some("1".to_string()),
                features: Some(
                    ["macros", "net", "rt-multi-thread"]
                        .iter()
                        .map(|f| f.to_string())
                        .collect(),
                ),
                ..Default::default()
            }),
        ),
        ("uuid".to_string(), Dependency::Simple("1".to_string())),
    ]);

    let mut package = Package::new(WRAPPER_PACKAGE.to_string(), "0.0.0".to_string());
    package.edition = Some(MaybeInherited::Local(Edition::E2024));
    package.publish = Some(MaybeInherited::Local(Publish::Flag(false)));

    // `()` metadata so `Workspace::default()` applies (the default `Value`
    // metadata type is not `Default`); we emit no `[package.metadata]` anyway.
    let manifest = Manifest::<(), ()> {
        package: Some(package),
        workspace: Some(Workspace::default()),
        dependencies: Some(dependencies),
        ..Default::default()
    };

    format!(
        "# Generated by quent-open. Do not edit.\n{}",
        toml::to_string(&manifest).expect("wrapper manifest serializes")
    )
}

/// Wrapper `src/main.rs`: wire `<analyzer>::Viewer`'s analyzer/importer into
/// `analyzer_service_router` and serve it. Root (`<context-uuid>/` subdirs) and
/// bind address come from env so one built binary serves any artifacts.
fn main_rs(spec: &ViewerSpec) -> String {
    let analyzer_crate = format_ident!("{}", spec.analyzer_crate());
    let format_variant = format_ident!("{}", spec.format.variant());
    let (root_env, addr_env) = (ROOT_ENV, ADDR_ENV);
    let tokens = quote! {
        use std::net::SocketAddr;
        use std::path::PathBuf;

        use quent_exporter::FileSystemFormat;
        use quent_query_engine_analyzer::ui::QuentViewer;
        use quent_query_engine_server::analyzer_cache::index_query_engines;
        use quent_query_engine_server::analyzer_service_router;
        use #analyzer_crate::Viewer;

        type Analyzer = <Viewer as QuentViewer>::Analyzer;

        #[tokio::main]
        async fn main() -> Result<(), Box<dyn std::error::Error>> {
            let root = PathBuf::from(std::env::var(#root_env)?);
            let addr: SocketAddr = std::env::var(#addr_env)?.parse()?;
            let format = FileSystemFormat::#format_variant;

            let import_root = root.clone();
            let importer = move |id: uuid::Uuid| {
                Ok(<Viewer as QuentViewer>::import_events(
                    &import_root.join(id.to_string()),
                    format,
                )?)
            };
            let lister_root = root.clone();
            let lister = move || index_query_engines(&lister_root, format);

            let router = analyzer_service_router::<Analyzer>(
                Box::new(importer),
                Box::new(lister),
                None,
            )?;

            let listener = tokio::net::TcpListener::bind(addr).await?;
            axum::serve(listener, router.into_make_service()).await?;
            Ok(())
        }
    };
    let file = syn::parse2(tokens).expect("generated wrapper main.rs is valid Rust");
    format!(
        "// Generated by quent-open. Do not edit.\n{}",
        prettyplease::unparse(&file)
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::{Format, GitPin, ViewerSpec};
    use std::path::PathBuf;

    fn spec() -> ViewerSpec {
        ViewerSpec {
            root: PathBuf::from("/data/ctx"),
            format: Format::Msgpack,
            analyzer_package: "quent-simulator-analyzer".into(),
            quent: GitPin {
                remote: "https://example.com/quent".into(),
                commit: "quentcommit".into(),
            },
            analyzer: GitPin {
                remote: "https://example.com/analyzer".into(),
                commit: "analyzercommit".into(),
            },
        }
    }

    #[test]
    fn cargo_toml_pins_quent_and_analyzer() {
        let manifest: toml::Value = toml::from_str(&cargo_toml(&spec())).unwrap();
        assert!(manifest.get("workspace").is_some(), "standalone workspace");
        let deps = &manifest["dependencies"];
        let server = &deps["quent-query-engine-server"];
        assert_eq!(server["git"].as_str().unwrap(), "https://example.com/quent");
        assert_eq!(server["rev"].as_str().unwrap(), "quentcommit");
        assert_eq!(server["features"][0].as_str().unwrap(), "ui");
        assert_eq!(
            deps["quent-exporter"]["features"][0].as_str().unwrap(),
            "msgpack"
        );
        let analyzer = &deps["quent-simulator-analyzer"];
        assert_eq!(
            analyzer["git"].as_str().unwrap(),
            "https://example.com/analyzer"
        );
        assert_eq!(analyzer["rev"].as_str().unwrap(), "analyzercommit");
    }

    #[test]
    fn main_rs_names_viewer_and_format() {
        let main = main_rs(&spec());
        assert!(main.contains("use quent_simulator_analyzer::Viewer;"));
        assert!(main.contains("FileSystemFormat::Msgpack"));
        assert!(main.contains("QUENT_OPEN_ADDR")); // bind address is configurable
    }
}
