// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * A span of time separated into equally-sized bins of time.
 */
export type BinnedSpan = { span: Span, bin_duration: bigint, num_bins: bigint, };
