// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityKind } from "./CapacityKind";

/**
 * Declaration of a Capacity of a Resource
 */
export type CapacityDecl = { name: string, kind: CapacityKind, };
