// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of capacity of a Resource.
 */
export type CapacityType = "Occupancy" | "Rate";
