// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityType } from "./CapacityType";

/**
 * Declaration of a Capacity of a Resource
 */
export type CapacityDecl = { name: string, kind: CapacityType, };
