// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Value } from "./Value";

/**
 * A Resource Capacity
 */
export type CapacityValue = { name: string, bound: Value | null, };
