// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Declaration of an FSM state.
 */
export type DynamicFsmStateDecl = { name: string, };
