// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicFsmStateDecl } from "./DynamicFsmStateDecl";

/**
 * Declaration of an FSM
 */
export type DynamicFsmTypeDecl = { 
/**
 * The unique type name of this FSM type
 */
name: string, 
/**
 * Unordered set of states this FSM type
 */
states: Array<DynamicFsmStateDecl>, };
