// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A directed edge of a Plan DAG.
 */
export type Edge = { 
/**
 * The ID of the port sourcing data.
 */
source: string, 
/**
 * The ID of the port sinking data.
 */
target: string, };
