// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribute } from "./Attribute";

/**
 * Attributes describing details about the implementation of this Engine
 */
export type EngineImplementationAttributes = { 
/**
 * The name of this Engine implementation, e.g. "SiriusDB", "Velox", "DataFusion", etc.
 */
name: string | null, 
/**
 * The version of this Engine implementation, e.g. "13.3.7"
 */
version: string | null, 
/**
 * Arbitrary attributes defined at run time.
 */
custom_attributes: Array<Attribute>, };
