// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Timestamps (nanoseconds since Unix epoch) of state transitions of an Engine.
 */
export type EngineTimestamps = { 
/**
 * The time at which the Engine started initialization.
 */
init: bigint | null, 
/**
 * The time at which the Engine started accepting queries.
 */
operating: bigint | null, 
/**
 * The time at which the Engine started shutting down and cleaning up its resources.
 */
finalizing: bigint | null, 
/**
 * The time at which the Engine was completely destructed and all resources were freed.
 */
exit: bigint | null, };
