// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A run-time typed reference to an entity.
 */
export type EntityRef = { "Engine": string } | { "QueryGroup": string } | { "Query": string } | { "Plan": string } | { "Worker": string } | { "Operator": string } | { "Port": string } | { "ResourceGroup": string } | { "Resource": string } | { "Fsm": string };
