// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicFsmTypeDecl } from "./DynamicFsmTypeDecl";
import type { Engine } from "./Engine";
import type { Operator } from "./Operator";
import type { Plan } from "./Plan";
import type { Port } from "./Port";
import type { Query } from "./Query";
import type { QueryGroup } from "./QueryGroup";
import type { Resource } from "./Resource";
import type { ResourceGroup } from "./ResourceGroup";
import type { ResourceTypeDecl } from "./ResourceTypeDecl";
import type { Worker } from "./Worker";

/**
 * A set of high-level manageable entities stored in maps from entity id -> entity.
 *
 * The maps provide an easy way for quick lookups based on entity IDs.
 * This also means the values in the maps are flattened entities.
 * Their relations are solely expressed through IDs.
 */
export type EntitiesUI = { engine: Engine, workers: { [key in string]?: Worker }, resources_types: { [key in string]?: ResourceTypeDecl }, resources: { [key in string]?: Resource }, resource_groups: { [key in string]?: ResourceGroup }, query_groups: { [key in string]?: QueryGroup }, queries: { [key in string]?: Query }, plans: { [key in string]?: Plan }, operators: { [key in string]?: Operator }, ports: { [key in string]?: Port }, fsm_types: { [key in string]?: DynamicFsmTypeDecl }, };
