// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { State } from "./State";

export type Fsm = { id: string, type_name: string | null, instance_name: string | null, state_sequence: Array<State>, };
