// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateDecl } from "./StateDecl";

/**
 * Declaration of an FSM
 */
export type FsmTypeDecl = { 
/**
 * The unique type name of this FSM type
 */
name: string, 
/**
 * Unordered set of states this FSM type
 */
states: Array<StateDecl>, };
