// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatorState } from "./OperatorState";
import type { Port } from "./Port";

/**
 * An Operator in a Plan DAG.
 */
export type Operator = { 
/**
 * The ID of this Operator.
 */
id: string, 
/**
 * The ID of the Plan this Operator belongs to.
 */
plan_id: string, 
/**
 * A list of Operator IDs in a parent plan (if any) from which this Operator was derived.
 */
parent_operator_ids: Array<string>, 
/**
 * The name of this Operator.
 */
name: string | null, 
/**
 * The Ports of this operator.
 */
ports: Array<Port>, 
/**
 * The sequence of states through which this Operator has been executed.
 */
state_sequence: Array<OperatorState>, };
