// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tree of Plans.
 *
 * Plans under a Query can form a simple tree with a trunk and potentially a
 * single branching point when they are fanned out over workers for distributed
 * engines. Under the Queryy there must be always one top-level Plan (the root
 * of the tree). For example, this could be what in some engines is called a
 * "logical" plan. An engine may then "lower" a Plan to produce a derived Plan,
 * any arbitrary number of times. At some point, at least one worker will
 * execute a Plan, but the model is flexible enough to allow a worker to
 * locally lower the plan further.
 */
export type PlanTree = { 
/**
 * The Plan ID.
 */
id: string, 
/**
 * The ID of the Query this Plan is logically nested under.
 */
query: string | null, 
/**
 * The ID of the Worker this Plan is local to.
 */
worker: string | null, 
/**
 * The child plan. If this is an empty list, this is a leaf plan.
 */
children: Array<PlanTree>, };
