// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";

/**
 * A Query Plan.
 */
export type Plan = { 
/**
 * The ID of this Plan.
 */
id: string, 
/**
 * The name of this Plan.
 */
name: string | null, 
/**
 * The ID of the Query this Plan is part of.
 */
query_id: string | null, 
/**
 * The optional parent Plan ID. This is useful if an Engine constructs
 * various types of Plans before execution, sometimes referred to as
 * "lowering". Examples include a logical and physical plan.
 */
parent_plan_id: string | null, 
/**
 * The optional Worker ID of the Worker that executed this Plan.
 *
 * If this Plan was not directly executed on a worker, but merely some
 * level plan in a sequence of lowering stages, then this may be set to
 * None.
 */
worker_id: string | null, 
/**
 * The IDs of the Operators that are part of this Plan.
 */
operator_ids: Array<string>, 
/**
 * The Edges between Operators of this Plan.
 */
edges: Array<Edge>, };
