// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Port of an Operator in a Plan DAG.
 */
export type Port = { id: string, parent_operator_id: string, name: string, };
