// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntitiesUI } from "./EntitiesUI";
import type { PlanTree } from "./PlanTree";
import type { ResourceTree } from "./ResourceTree";

export type QueryBundle = { entities: EntitiesUI, plan_tree: PlanTree, resource_tree: ResourceTree, unique_operator_names: Array<string>, unique_entity_names: Array<string>, start_time_unix_ns: bigint, duration_s: number, };
