// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntitiesUI } from "./EntitiesUI";
import type { PlanTree } from "./PlanTree";
import type { ResourceTree } from "./ResourceTree";

export type QueryBundle = { 
/**
 * The ID of the query.
 */
query_id: string, 
/**
 * Maps with entities that are involved in this query.
 */
entities: EntitiesUI, 
/**
 * A tree of plans involved in the execution of this query.
 */
plan_tree: PlanTree, 
/**
 * A tree of resources involved in the execution of this query.
 */
resource_tree: ResourceTree, 
/**
 * A list of unique operator type names.
 */
unique_operator_names: Array<string>, 
/**
 * A list of unique entity type names.
 */
unique_entity_names: Array<string>, 
/**
 * The number of nanoseconds passed since the Unix epoch at which the
 * engine started executing this query.
 */
start_time_unix_ns: bigint, 
/**
 * The duration of this query, in seconds.
 */
duration_s: number, };
