// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Timestamps (nanoseconds since Unix epoch) of state transitions of a Query.
 */
export type QueryTimestamps = { 
/**
 * The time at which the Query started initialization.
 */
init: bigint | null, 
/**
 * The time at which the Query started planning.
 */
planning: bigint | null, 
/**
 * The time at which the Query started executing.
 */
executing: bigint | null, 
/**
 * The time at which the Query was idle.
 *
 * In this state, the Query has been processed, but it still potentially occupies
 * resources of the engine to hold a result which is yet to be delivered to the query
 * client.
 */
idle: bigint | null, 
/**
 * The time at which the Query started shutting down and cleaning up its resources.
 */
finalizing: bigint | null, 
/**
 * The time at which the Query was completely destructed and all resources were freed.
 */
exit: bigint | null, };
