// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Query.
 */
export type Query = { 
/**
 * The ID of this Query
 */
id: string, 
/**
 * The ID of the QueryGroup orchestrating this query
 */
query_group_id: string, 
/**
 * A name for this Query.
 */
name: string | null, };
