// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entities } from "./Entities";
import type { PlanTree } from "./PlanTree";
import type { ResourceTree } from "./ResourceTree";

export type QueryBundle = { entities: Entities, plan_tree: PlanTree, resource_tree: ResourceTree, };
