// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityDecl } from "./CapacityDecl";

/**
 * Declaration of a Resource type
 */
export type ResourceTypeDecl = { 
/**
 * The unique type name for this type of Resource.
 */
name: string, capacities: Array<CapacityDecl>, 
/**
 * An unordered set of FSM type names that Use this Resource.
 */
used_by_fsms: Array<string>, };
