// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";

/**
 * A Resource of which its Capacities cannot be resized.
 */
export type Resource = { 
/**
 * The ID of this Resource.
 */
id: string, 
/**
 * The name of this Resource.
 */
instance_name: string | null, 
/**
 * The type of this Resource.
 */
type_name: string, 
/**
 * The scope of this Resource.
 */
scope: EntityRef | null, };
