// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribute } from "./Attribute";
import type { EntityRef } from "./EntityRef";
import type { Span } from "./Span";

export type ResourceTimelineUse = { span: Span, amounts: Array<Attribute>, entity: EntityRef, };
