// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";
import type { ResourceGroupTimestamps } from "./ResourceGroupTimestamps";

/**
 * A Group of Resources.
 */
export type ResourceGroup = { 
/**
 * The ID of this Resource Group
 */
id: string, 
/**
 * The name of the type of this Resource Group
 */
type_name: string | null, 
/**
 * The name of the instance of this Resource Group
 */
instance_name: string | null, 
/**
 * The scope of this Resource Group
 */
scope: EntityRef | null, 
/**
 * The timestamps of state transitions of this ResourceGroup.
 */
timestamps: ResourceGroupTimestamps, };
