// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceTimelineUse } from "./ResourceTimelineUse";
import type { Span } from "./Span";

export type ResourceTimeline = { span: Span, uses: Array<ResourceTimelineUse>, };
