// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityValue } from "./CapacityValue";
import type { EntityRef } from "./EntityRef";
import type { Span } from "./Span";

/**
 * An individual usage of a resource.
 */
export type ResourceTimelineUse = { 
/**
 * The span of time in which the resource was utilized.
 */
span: Span, 
/**
 * The amounts of the resource's capacity that was utilized.
 */
amounts: Array<CapacityValue>, 
/**
 * The entity that utilized the resource.
 */
entity: EntityRef, };
