// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Timestamps (nanoseconds since Unix epoch) of state transitions of a
 * ResourceGroup.
 */
export type ResourceGroupTimestamps = { 
/**
 * The time at which the ResourceGroup started initialization.
 */
init: bigint | null, 
/**
 * The time at which the ResourceGroup started operating.
 */
operating: bigint | null, 
/**
 * The time at which the ResourceGroup started shutting down and
 * cleaning up its resources.
 */
finalizing: bigint | null, 
/**
 * The time at which the ResourceGroup was completely destructed and
 * all resources were freed.
 */
exit: bigint | null, };
