// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpan } from "./BinnedSpan";

export type ResourceTimelineBinned = { config: BinnedSpan, capacity_values: { [key in string]?: Array<number> }, };
