// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceOperatingState } from "./ResourceOperatingState";

/**
 * Resource states.
 */
export type ResourceState = { "Init": bigint } | { "Operating": ResourceOperatingState } | { "Resizing": bigint } | { "Finalizing": bigint } | { "Exit": bigint };
