// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";

/**
 * A tree of references to entities that can hold resources in their scope,
 * with resources as leaf nodes.
 *
 * The tree is built from the perspective of a single query. Thus, under the
 * root level, engine, query group and query and query-level plans are
 * siblings.
 */
export type ResourceTree = { 
/**
 * The ID of the Entity representing this node.
 *
 * This is either an [`EntityRef::Resource`] or a
 * [`EntityRef::ResourceGroup`].
 *
 * If this is None, this is the root level.
 */
item: EntityRef | null, 
/**
 * The children of this "resource".
 *
 * Valid for all items except those of the variant
 * ResourceTreeNodeItem::Resource
 */
children: Array<ResourceTree>, };
