// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribute } from "./Attribute";

/**
 * Attributes of the "Operating" state of a Resource.
 */
export type ResourceOperatingState = { timestamp: bigint, capacities: Array<Attribute>, };
