// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityDecl } from "./CapacityDecl";
import type { EntityRef } from "./EntityRef";
import type { ResourceState } from "./ResourceState";

/**
 * A Resource of which its Capacities cannot be resized.
 */
export type Resource = { 
/**
 * The ID of this Resource
 */
id: string, 
/**
 * The name of this Resource
 */
instance_name: string | null, 
/**
 * The name of this Resource type
 */
type_name: string, 
/**
 * The scope of this Resource.
 */
scope: EntityRef | null, 
/**
 * The Capacities of this Resource.
 *
 * If this is empty, this is Unit resource.
 */
capacities: { [key in string]?: CapacityDecl }, 
/**
 * The sequence of states that this Resource
 */
state_sequence: Array<ResourceState>, };
