// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";

export type ResourceTimelineBinnedByState = { 
/**
 * The configuration of the binned timeline.
 */
config: BinnedSpanSec, 
/**
 * Maps a resource capacity name to a map of a state name to a vector where
 * each element holds an aggregated value of a time bin.
 */
capacities_states_values: { [key in string]?: { [key in string]?: Array<number> } }, };
