// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceTimelineUse } from "./ResourceTimelineUse";
import type { Span } from "./Span";

/**
 * A timeline of individual [`ResourceTimelineUse`]s.
 */
export type ResourceTimeline = { 
/**
 * The span of time for which the usages are included.
 */
span: Span, 
/**
 * The uses, arbitrarily ordered.
 */
uses: Array<ResourceTimelineUse>, };
