// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpan } from "./BinnedSpan";

export type ResourceTimelineBinned = { 
/**
 * The configuration of the binned timeline.
 */
config: BinnedSpan, 
/**
 * Maps a resource capacity name to a vector where each element holds an
 * aggregated value of a time bin.
 */
capacities_values: { [key in string]?: Array<number> }, };
