// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span of time represented as a half-open interval [start, end) over discrete timestamps.
 */
export type Span = { 
/**
 * The start timestamp, inclusive.
 */
start: bigint, 
/**
 * The end timestamp, exclusive.
 */
end: bigint, };
