// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribute } from "./Attribute";
import type { EntityRef } from "./EntityRef";
import type { Use } from "./Use";

export type State = { name: string, uses: Array<Use>, timestamp: bigint, attributes: Array<Attribute>, relations: Array<EntityRef>, };
