// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceTimelineBinned } from "./ResourceTimelineBinned";
import type { ResourceTimelineBinnedByState } from "./ResourceTimelineBinnedByState";

export type TimelineResponse = { "type": "Binned" } & ResourceTimelineBinned | { "type": "BinnedByState" } & ResourceTimelineBinnedByState;
