// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityValue } from "./CapacityValue";

export type Use = { resource: string, capacities: Array<CapacityValue>, };
