// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Shared helpers for binding generators.

use convert_case::{Case, Casing};
use proc_macro2::TokenStream;
use quent_model::{AttributeDef, ModelBuilder, UsageDef};

use crate::{CxxOptions, PyO3Options};

pub(crate) trait HasInstrumentationCrate {
    fn instrumentation_crate(&self) -> &str;
}

impl HasInstrumentationCrate for CxxOptions {
    fn instrumentation_crate(&self) -> &str {
        &self.instrumentation_crate
    }
}

impl HasInstrumentationCrate for PyO3Options {
    fn instrumentation_crate(&self) -> &str {
        &self.instrumentation_crate
    }
}

/// Convert snake_case to PascalCase.
pub(crate) fn to_pascal_case(s: &str) -> String {
    s.to_case(Case::Pascal)
}

/// Convert a model-provided Rust identifier into the Python identifier spelling
/// exported by generated bindings.
///
/// The model definition language supplies ordinary Rust identifiers, so the
/// only Python-specific conflict we handle here is a Python reserved word.
pub(crate) fn py_export_name(name: &str) -> String {
    let mut out = name.to_string();
    if matches!(
        name,
        "False"
            | "None"
            | "True"
            | "and"
            | "as"
            | "assert"
            | "async"
            | "await"
            | "break"
            | "class"
            | "continue"
            | "def"
            | "del"
            | "elif"
            | "else"
            | "except"
            | "finally"
            | "for"
            | "from"
            | "global"
            | "if"
            | "import"
            | "in"
            | "is"
            | "lambda"
            | "nonlocal"
            | "not"
            | "or"
            | "pass"
            | "raise"
            | "return"
            | "try"
            | "while"
            | "with"
            | "yield"
    ) {
        println!(
            "cargo:warning=model component `{name}` is a Python reserved keyword. \
             The exposed Python name will be `{name}_`"
        );
        out.push('_');
    }
    out
}

/// Format a `TokenStream` into pretty-printed Rust source.
pub(crate) fn pretty_print(tokens: TokenStream) -> String {
    let file = syn::parse2::<syn::File>(tokens).expect("generated tokens must be valid syntax");
    prettyplease::unparse(&file)
}

/// Rust path to the hidden `__quent_{model}` re-export generated by `model!`.
pub(crate) fn quent_path(model_name: &str, options: &impl HasInstrumentationCrate) -> syn::Path {
    let snake = model_name.to_case(Case::Snake);
    syn::parse_str(&format!(
        "{}::__quent_{}",
        options.instrumentation_crate(),
        snake
    ))
    .unwrap()
}

/// Fully qualified top-level event enum path for a generated model.
pub(crate) fn event_type_path(model_name: &str, options: &impl HasInstrumentationCrate) -> String {
    format!("{}::{}Event", options.instrumentation_crate(), model_name)
}

/// Remap a `module_path!()` value to be relative to the instrumentation crate.
///
/// `module_path!()` returns paths like `quent_query_engine_model::engine`.
/// The generated bridges access those types through the instrumentation crate's
/// public re-exports, such as `quent_qe_python_instrumentation::engine`.
pub(crate) fn remap_module_path(
    module_path: &str,
    options: &impl HasInstrumentationCrate,
) -> String {
    if let Some(rest) = module_path.split_once("::").map(|(_, rest)| rest) {
        format!("{}::{}", options.instrumentation_crate(), rest)
    } else {
        options.instrumentation_crate().to_string()
    }
}

pub(crate) fn is_auto_declaration_event(entity_name: &str, event_name: &str) -> bool {
    event_name == format!("{entity_name}_declaration")
}

pub(crate) fn resource_operating_attrs(
    model: &ModelBuilder,
    usage: &UsageDef,
) -> Vec<AttributeDef> {
    model
        .fsms
        .iter()
        .find(|fsm| fsm.name == usage.resource_name)
        .and_then(|fsm| fsm.states.iter().find(|state| state.name == "operating"))
        .map(|state| state.attributes.clone())
        .unwrap_or_default()
}
