[package]
name = "quent-io-msgpack"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
quent-events = { path = "../../events", features = ["serde"]}
quent-io-types = { path = "../types" }
rmp-serde.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["sync", "fs", "io-util"]}
tracing.workspace = true
uuid.workspace = true
