// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanSec } from "./SpanSec";

/**
 * A UI-friendly representation of [`BinnedSpan`].
 */
export type BinnedSpanSec = { 
/**
 * The entire span of time this binned span represents.
 */
span: SpanSec, 
/**
 * The duration of one bin.
 */
bin_duration: number, 
/**
 * The number of bins.
 */
num_bins: bigint, };
