// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FiniteStateMachine } from "./FiniteStateMachine";

/**
 * The data of a single resource timeline within a bulk response.
 * Config is omitted here because it is shared across all resources.
 */
export type BulkTimelineData = { "type": "Binned", capacities_values: { [key in string]?: Array<number> }, long_fsms: Array<FiniteStateMachine>, } | { "type": "BinnedByState", capacities_states_values: { [key in string]?: { [key in string]?: Array<number> } }, long_fsms: Array<FiniteStateMachine>, };
