// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkTimelineData } from "./BulkTimelineData";

export type BulkTimelineResponseEntry = { "status": "ok", message: string, data: BulkTimelineData, } | { "status": "error", message: string, };
