// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkTimelinesResponseEntry } from "./BulkTimelinesResponseEntry";

/**
 * Response for a bulk timeline request.
 */
export type BulkTimelinesResponse = { 
/**
 * The timeline responses, keyed by the same keys as the request entries.
 */
entries: { [key in string]?: BulkTimelinesResponseEntry }, };
