// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { ResourceTimeline } from "./ResourceTimeline";

/**
 * A single entry in a bulk timeline response.
 */
export type BulkTimelinesResponseEntry = { "status": "ok", 
/**
 * An informational message about the entry.
 */
message: string, 
/**
 * The configuration of the binned timeline for this entry.
 */
config: BinnedSpanSec, 
/**
 * The timeline data for this entry.
 */
data: ResourceTimeline, } | { "status": "error", 
/**
 * A message describing the error.
 */
message: string, };
