// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkTimelineRequestParams } from "./BulkTimelineRequestParams";

/**
 * A request for timelines in bulk.
 */
export type BulkTimelinesRequest = { num_bins: number, start: number, end: number, 
/**
 * A map of resource_(group)_id to a request.
 */
entries: { [key in string]?: BulkTimelineRequestParams }, };
