// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineRequest } from "./TimelineRequest";

/**
 * Request for a bulk of timelines.
 */
export type BulkTimelineRequest<GlobalParams, TimelineParams> = { 
/**
 * The list of timelines requested.
 */
entries: { [key in string]?: TimelineRequest<TimelineParams> }, 
/**
 * Global application-specific parameters, e.g. filters.
 */
app_params: GlobalParams, };
