// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { BulkTimelinesResponseEntry } from "./BulkTimelinesResponseEntry";

export type BulkTimelinesResponse = { config: BinnedSpanSec, entries: { [key in string]?: BulkTimelinesResponseEntry }, };
