// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceGroupTimelineRequestParams } from "./ResourceGroupTimelineRequestParams";
import type { ResourceTimelineRequestParams } from "./ResourceTimelineRequestParams";

export type BulkTimelineRequestParams = ResourceGroupTimelineRequestParams | ResourceTimelineRequestParams;
