// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceTimeline } from "./ResourceTimeline";

export type BulkTimelinesResponseEntry = { "status": "ok", message: string, data: ResourceTimeline, } | { "status": "error", message: string, };
