// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { BulkTimelineResponseEntry } from "./BulkTimelineResponseEntry";

export type BulkTimelinesResponse = { config: BinnedSpanSec, resources: { [key in string]?: BulkTimelineResponseEntry }, };
