// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityKind } from "./CapacityKind";

/**
 * A capacity declaration for a resource type, as exposed to the UI.
 */
export type CapacityDecl = { 
/**
 * The name of this capacity.
 */
name: string, 
/**
 * The kind of capacity.
 */
kind: CapacityKind, 
/**
 * The name of the quantity spec (key into the quantity_specs map).
 */
quantity: string, };
