// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether two queries are structurally comparable (i.e. same plan shape).
 */
export type Compatibility = "compatible" | "incompatible";
