// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { DistributionDecl } from "./DistributionDecl";
import type { DistributionSeries } from "./DistributionSeries";

/**
 * A binned data-flow distribution timeline covering every operator of a
 * query.
 */
export type DataFlowTimelineBinned = { 
/**
 * The configuration of the binned timeline.
 *
 * This may slightly differ from the requested configuration to ensure
 * bounds are not exceeded and bin sizes are equal.
 */
config: BinnedSpanSec, 
/**
 * Presentation metadata declared by the analyzer.
 */
decl: DistributionDecl, 
/**
 * Distribution series keyed by operator id.
 */
operators: { [key in string]: DistributionSeries }, };
