// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { CategoricalDecl } from "./CategoricalDecl";
import type { CategoricalSeries } from "./CategoricalSeries";

/**
 * A binned data-flow categorical timeline covering every operator of a
 * query. Analyzers without data-flow telemetry return
 * `AnalyzerError::Unsupported` instead (HTTP 501), which the UI treats as
 * "hide the view".
 */
export type DataFlowTimelineBinned = { 
/**
 * The configuration of the binned timeline.
 *
 * This may slightly differ from the requested configuration to ensure
 * bounds are not exceeded and bin sizes are equal.
 */
config: BinnedSpanSec, 
/**
 * Presentation metadata declared by the analyzer.
 */
decl: CategoricalDecl, 
/**
 * Categorical series keyed by operator id.
 */
operators: { [key in string]: CategoricalSeries }, };
