// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataFlowTimelineBinned } from "./DataFlowTimelineBinned";

/**
 * Response for a data-flow distribution timeline request.
 */
export type DataFlowTimelineResponse = "Unsupported" | { "Binned": DataFlowTimelineBinned };
