// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffQueryRef } from "./DiffQueryRef";

/**
 * Request body for a workload diff.
 */
export type DiffRequest = { baseline_query: DiffQueryRef, comparison_queries: Array<DiffQueryRef>, };
