// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary metadata for a query included in a diff result.
 */
export type DiffQuerySummary = { id: string, engine_id: string, instance_name: string | null, query_group_id: string | null, query_group_name: string | null, };
