// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffDelta } from "./DiffDelta";
import type { DiffOperatorRef } from "./DiffOperatorRef";

/**
 * Stat deltas for a matched pair of operators (one from each query).
 */
export type DiffOperatorDelta = { 
/**
 * `operators.0` is from the baseline, `operators.1` is from the comparison query.
 */
operators: [DiffOperatorRef, DiffOperatorRef], 
/**
 * Keyed by stat name.
 */
stats: { [key in string]?: DiffDelta }, };
