// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to an operator type in a diff, aggregated across all operators of that type.
 */
export type DiffOperatorRef = { label: string, operator_type_name: string | null, 
/**
 * Number of operators of this type that were aggregated.
 */
count: number, };
