// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryDiff } from "./QueryDiff";

/**
 * Response body for a workload diff.
 *
 * One [`QueryDiff`] per entry in `DiffRequest.comparison_queries`, in the same order.
 */
export type DiffResponse = { comparison_queries: Array<QueryDiff>, };
