// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Value } from "./Value";

/**
 * The raw values and computed delta for a single stat across two queries.
 *
 * `stats.0` is the baseline value, `stats.1` is the comparison value.
 */
export type DiffDelta = { stats: [Value | null, Value | null], delta: number | null, percent_delta: number | null, };
