// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a single query within a specific engine.
 */
export type DiffQueryRef = { engine_id: string, query_id: string, };
