// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One key of the application-defined dimension of a categorical timeline.
 */
export type DimensionKeyDecl = { 
/**
 * The key used in [`CategoricalSeries::values`].
 */
key: string, 
/**
 * Human-friendly display name.
 */
display_name: string, };
