// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binned values of one distribution timeline series:
 * measure name -> state name -> dimension key -> one value per time bin.
 *
 * Absent inner entries mean all-zero bins.
 */
export type DistributionSeries = { values: { [key in string]: { [key in string]: { [key in string]: Array<number> } } }, };
