// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineConfig } from "./TimelineConfig";

/**
 * Request for a distribution timeline.
 */
export type DistributionTimelineRequest<GlobalParams> = { 
/**
 * Names of the measures to compute. Empty means all declared measures.
 */
measures: Array<string>, 
/**
 * The configuration of the window and number of bins.
 */
config: TimelineConfig, 
/**
 * Global application-specific parameters, e.g. filters.
 */
app_params: GlobalParams, };
