// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicList } from "./DynamicList";
import type { DynamicStruct } from "./DynamicStruct";

/**
 * A [`DynamicAttribute`] value.
 */
export type DynamicValue =
  | number
  | number
  | number
  | bigint
  | number
  | number
  | number
  | bigint
  | number
  | number
  | string
  | DynamicStruct
  | DynamicList;
