// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicAttribute } from "./DynamicAttribute";

/**
 * A group of [`DynamicAttribute`]s.
 */
export type DynamicStruct = Array<DynamicAttribute>;
