// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicValue } from "./DynamicValue";

/**
 * A key-value pair.
 */
export type DynamicAttribute = { key: string; value: DynamicValue | null };
