// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicStruct } from "./DynamicStruct";

/**
 * A sequence of [`DynamicValue`]s.
 */
export type DynamicList =
  | Array<number>
  | Array<number>
  | Array<number>
  | Array<bigint>
  | Array<number>
  | Array<number>
  | Array<number>
  | Array<bigint>
  | Array<number>
  | Array<number>
  | Array<string>
  | Array<DynamicStruct>;
