// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An edge between two [`Operator`] [`Port`]s.
 */
export type Edge = { 
/**
 * The [`Port`] that produced the data flowing over this edge.
 */
source: string, 
/**
 * The [`Port`] that consumed the data flowing over this edge.
 */
target: string, };
