// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FiniteStateMachine } from "./FiniteStateMachine";

/**
 * A ranked, paged list of entities.
 */
export type EntityListResponse = {
  items: Array<FiniteStateMachine>;
  /**
   * The count of entities matching the filter before paging.
   */
  total: number;
};
