// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityScope } from "./EntityScope";

/**
 * Entity filters.
 *
 * Every field that is set must match, `None` fields do not filter.
 */
export type EntityListFilter = {
  /**
   * Restrict resulting entities to be in this scope.
   */
  scope: EntityScope | null;
  /**
   * Restrict resulting entities to be of this type.
   */
  entity_type_name: string | null;
  /**
   * Keep only entities with resource usages longer than this threshold.
   *
   * N.B. only Fsm-type entities can have usages.
   */
  min_usage_s: number | null;
};
