// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityListFilter } from "./EntityListFilter";
import type { PageParams } from "./PageParams";
import type { Sort } from "./Sort";
import type { TimeWindow } from "./TimeWindow";

/**
 * A single entity-list query.
 */
export type EntityListEntry<EntryParams> = { 
/**
 * The window of time entities must fall in.
 */
window: TimeWindow, 
/**
 * Filter parameters.
 */
filter: EntityListFilter, 
/**
 * Sort parameters.
 */
sort: Sort, 
/**
 * Pagination parameters.
 *
 * When this is not set, return the full list. Depending on the dataset
 * size and other parameters, this may result in a large volume of data and
 * should be used with care.
 */
page: PageParams | null, 
/**
 * Per-query application-specific parameters.
 */
application: EntryParams, };
