// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityListEntry } from "./EntityListEntry";

/**
 * Parameters for listing entities.
 */
export type EntityListRequest<GlobalParams, EntryParams> = {
  entry: EntityListEntry<EntryParams>;
  /**
   * Global application parameters shared by the query.
   */
  app_params: GlobalParams;
};
