// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to an entity
 */
export type EntityRef = { "Engine": string } | { "Worker": string } | { "QueryGroup": string } | { "Query": string } | { "Plan": string } | { "Operator": string } | { "Port": string } | { "Resource": string } | { "ResourceGroup": string };
