// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntityFilter = { 
/**
 * If set, only include utilizations from entities with this type name.
 *
 * If this entity is an FSM, then the timeline will aggregate usages into
 * bins for each state separately.
 */
entity_type_name: string | null, };
