// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Restricts returned entities to appear in a certain scope.
 */
export type EntityScope = { "Resource": { resource_id: string } } | {
  "ResourceGroup": { resource_group_id: string; resource_type_name: string };
};
