// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsmTransition } from "./FsmTransition";

/**
 * A run-time defined Finite-State-Machine.
 */
export type FiniteStateMachine = { 
/**
 * The ID of this FSM.
 */
id: string, 
/**
 * The type name of this FSM.
 */
type_name: string, 
/**
 * The instance name of this FSM.
 */
instance_name: string, 
/**
 * The Operator this FSM executes on behalf of, if the application's
 * analyzer links one. Enables the UI to resolve and display the
 * operator (e.g. a task's fused pipeline chain) generically.
 */
operator_id: string | null, 
/**
 * The transitions of this FSM.
 */
transitions: Array<FsmTransition>, };
