// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declaration of an FSM state.
 */
export type FsmStateTypeDecl = { 
/**
 * The name of this FSM state.
 */
name: string, 
/**
 * The names of the resource types this FSM state can use.
 */
usages: Array<string>, };
