// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsmUsage } from "./FsmUsage";

/**
 * A transition in an FSM.
 */
export type FsmTransition = { 
/**
 * The name of the state this transition enters.
 */
name: string, 
/**
 * The usages of this state.
 */
usages: Array<FsmUsage>, 
/**
 * The timestamp in seconds relative to an epoch.
 */
timestamp: number, };
