// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsmStateTypeDecl } from "./FsmStateTypeDecl";
import type { FsmTransitionDecl } from "./FsmTransitionDecl";

/**
 * A declaration of an FSM type.
 */
export type FsmTypeDecl = { 
/**
 * The name of this FSM type.
 */
name: string, 
/**
 * The states of this FSM type.
 */
states: Array<FsmStateTypeDecl>, 
/**
 * The possible transitions of this FSM type.
 */
transitions: Array<FsmTransitionDecl>, };
