// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attribute } from "./Attribute";
import type { FsmUsage } from "./FsmUsage";

/**
 * A transition in an FSM.
 */
export type FsmTransition = { 
/**
 * The name of the state this transition enters.
 */
name: string, 
/**
 * The usages of this state.
 */
usages: Array<FsmUsage>, 
/**
 * The timestamp in seconds relative to an epoch.
 */
timestamp: number, 
/**
 * Attribute key-value pairs recorded by the application's
 * instrumentation on this state.
 */
attributes: Array<Attribute>, 
/**
 * Attribute key-value pairs computed by the application's analyzer
 * (e.g. a per-span processing rate, a resolved entity name). Kept
 * separate from [`Self::attributes`] so users can tell recorded values
 * apart from derived ones. The UI renders both.
 */
derived_attributes: Array<Attribute>, };
