// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declaration of an FSM state transition.
 */
export type FsmTransitionDecl = { "Entry": string } | { "Transition": [string, string] } | { "Exit": string };
