// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A capacity value used by an FSM state.
 */
export type FsmUsage = { 
/**
 * The resource ID being used.
 */
resource: string, 
/**
 * The capacities being used (name, optional value).
 */
capacities: Array<[string, bigint | null]>, };
