// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Struct } from "./Struct";

/**
 * A sequence of [`Value`]s.
 */
export type List = Array<number> | Array<number> | Array<number> | Array<bigint> | Array<number> | Array<number> | Array<number> | Array<bigint> | Array<number> | Array<number> | Array<string> | Array<Struct>;
