// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityKind } from "./CapacityKind";

/**
 * A measure declared by the downstream analyzer for a distribution timeline,
 * e.g. an entity count or a number of bytes.
 */
export type MeasureDecl = { 
/**
 * Unique name; key into [`DistributionSeries::values`].
 */
name: string, 
/**
 * Human-friendly display name.
 */
display_name: string, 
/**
 * Key into the application's quantity specs map for unit formatting.
 */
quantity: string, 
/**
 * Display semantics of a bin value (Occupancy = time-weighted level).
 */
kind: CapacityKind, };
