// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatorStatistics } from "./OperatorStatistics";
import type { SpanSec } from "./SpanSec";
import type { Value } from "./Value";

export type Operator = { 
/**
 * The ID of this [`Operator`].
 */
id: string, 
/**
 * The ID of the [`Plan`] this [`Operator`] belongs to.
 */
plan_id: string | null, 
/**
 * A list of [`Operator`] IDs in a parent plan (if any) from which this
 * [`Operator`] was derived.
 */
parent_operator_ids: Array<string>, 
/**
 * The name of this [`Operator`].
 */
instance_name: string | null, 
/**
 * The name of this type of [`Operator`].
 */
operator_type_name: string | null, 
/**
 * The custom attributes of this [`Operator`].
 */
custom_attributes: { [key in string]?: Value | null }, 
/**
 * The statistics of this [`Operator`].
 *
 * These are attributes that are typically gathered after the work
 * described by an [`Operator`] has completed.
 */
statistics: OperatorStatistics | null, 
/**
 * The span of time between the first moment an operator started processing
 * an input, and the latest moment at which an operator finished producing
 * an output (excluding any potential back-pressure).
 *
 * There may have been gaps in this span in which this operator was not
 * actively using any resources. Thus, this span of time does NOT represent
 * e.g. "CPU time" spent.
 */
active_span: SpanSec | null, };
