// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-entry timeline-request parameter; restricts a resource timeline to a
 * single operator when set.
 */
export type OperatorFilter = { operator_id: string | null, };
