// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for paginated lists.
 */
export type PageParams = { 
/**
 * The maximum size of a page.
 */
max: number, 
/**
 * The zero-based index of the requested page.
 */
page: number, };
