// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanTree = { 
/**
 * The ID of the plan at this node in the tree.
 */
id: string, 
/**
 * The ID of the worker that this Plan was local to, if any.
 */
worker: string | null, 
/**
 * The children of the plan at the node in this tree.
 */
children: Array<PlanTree>, };
