// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicValue } from "./DynamicValue";

export type PortStatistics = {
  /**
   * Custom statistics
   */
  custom_statistics: { [key in string]: DynamicValue | null };
};
