// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortStatistics } from "./PortStatistics";

export type Port = { 
/**
 * The ID of this [`Port`]
 */
id: string, 
/**
 * The [`Operator`] to which this [`Port`] belongs.
 */
operator_id: string | null, 
/**
 * The name of this [`Port`].
 */
instance_name: string | null, 
/**
 * Statistics associated with this port:
 */
statistics: PortStatistics | null, };
