// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The prefix system used for scaling and abbreviating a quantity.
 */
export type PrefixSystem = "Si" | "Iec" | "None";
