// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine";
import type { Operator } from "./Operator";
import type { Plan } from "./Plan";
import type { Port } from "./Port";
import type { Query } from "./Query";
import type { QueryGroup } from "./QueryGroup";
import type { Resource } from "./Resource";
import type { ResourceGroup } from "./ResourceGroup";
import type { ResourceTypeDecl } from "./ResourceTypeDecl";
import type { Worker } from "./Worker";

export type QueryEntities = { 
/**
 * The engine that ran this query.
 */
engine: Engine, 
/**
 * The group of this query.
 */
query_group: QueryGroup, 
/**
 * The query.
 */
query: Query, 
/**
 * The workers of this query.
 */
workers: { [key in string]?: Worker }, 
/**
 * The plans of this query.
 */
plans: { [key in string]?: Plan }, 
/**
 * The operators of the plans.
 */
operators: { [key in string]?: Operator }, 
/**
 * The ports of the operators
 */
ports: { [key in string]?: Port }, 
/**
 * Miscellaneous resources
 */
resources: { [key in string]?: Resource }, 
/**
 * Miscellaneous resource groups
 */
resource_groups: { [key in string]?: ResourceGroup }, 
/**
 * Miscellaneous resource types
 */
resource_types: { [key in string]?: ResourceTypeDecl }, };
