// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffDelta } from "./DiffDelta";

/**
 * Query-level stat deltas (derived from query timestamps).
 */
export type QueryStatDiffs = { duration: DiffDelta, };
