// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Compatibility } from "./Compatibility";
import type { DiffOperatorDelta } from "./DiffOperatorDelta";
import type { DiffQuerySummary } from "./DiffQuerySummary";
import type { QueryStatDiffs } from "./QueryStatDiffs";

/**
 * The diff result for a single comparison query against the baseline.
 */
export type QueryDiff = { compatibility: Compatibility, query: DiffQuerySummary | null, operator_diffs: Array<DiffOperatorDelta> | null, stat_diffs: QueryStatDiffs | null, warnings: Array<string> | null, };
