// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global timeline-request parameter identifying the query to report on.
 */
export type QueryFilter = { query_id: string, };
