// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Resource.
 */
export type Resource = { 
/**
 * The ID of this Resource.
 */
id: string, 
/**
 * The name of this Resource.
 */
instance_name: string, 
/**
 * The unique type name of this Resource.
 */
type_name: string, 
/**
 * The id of the parent resource group.
 */
parent_group_id: string, };
