// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResourceTimelineUrlQueryParams = { 
/**
 * The number of bins.
 *
 * u16::MAX is large enough when bins are plotted as single pixel wide
 * bars, even for insane screen resolutions.
 */
num_bins: number, 
/**
 * Start time in seconds.
 */
start: number, 
/**
 * End time in seconds.
 */
end: number, 
/**
 * If set, only include utilizations from FSMs with this type name, and
 * aggregate for each state separately.
 *
 * Can be set for both resource and resource group timelines.
 */
fsm_type_name: string | null, 
/**
 * Sets the resource type for which to provide an aggregated timeline.
 *
 * This is required for resource group routes, and is ignored for
 * individual resource timeline routes.
 */
resource_type_name: string | null, };
