// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for requesting a resource timeline.
 */
export type ResourceTimelineRequestParams = { 
/**
 * The type name of the FSM for which to produce the resource utilization timeline.
 *
 * If set, only include utilizations from FSMs with this type name, and
 * aggregate for each state separately.
 */
fsm_type_name: string | null, 
/**
 * Filter the usages of the resource on this operator ID.
 */
operator_id: string | null, 
/**
 * If set, fully include entities that have usages exceeding this amount of time.
 */
long_entities_threshold_s: number | null, };
