// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRef } from "./EntityRef";
import type { ResourceGroupNode } from "./ResourceGroupNode";

/**
 * A tree of resources.
 */
export type ResourceTree = { "ResourceGroup": ResourceGroupNode } | { "Resource": EntityRef };
