// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { FiniteStateMachine } from "./FiniteStateMachine";

export type ResourceTimelineBinned = { 
/**
 * The configuration of the binned timeline.
 *
 * This may slightly differ from the requested configuration to ensure
 * bounds are not exceeded and bin sizes are equal.
 */
config: BinnedSpanSec, 
/**
 * Maps a resource capacity name to a vector where each element holds an
 * aggregated value of a time bin.
 */
capacities_values: { [key in string]?: Array<number> }, 
/**
 * FSMs that have usage spans exceeding the long_entities_threshold.
 */
long_fsms: Array<FiniteStateMachine>, };
