// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceTree } from "./ResourceTree";

/**
 * A resource group node in a resource tree.
 */
export type ResourceGroupNode<T> = { id: T, children: Array<ResourceTree<T>>, };
