// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacityDecl } from "./CapacityDecl";

/**
 * A type of [`Resource`].
 */
export type ResourceTypeDecl = { 
/**
 * The unique type name for this type of Resource.
 */
name: string, 
/**
 * The capacities of this type of Resource.
 */
capacities: Array<CapacityDecl>, 
/**
 * The type names of the entities that used this Resource.
 */
used_by: Array<string>, };
