// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceGroupNode } from "./ResourceGroupNode";

/**
 * A tree of resources.
 */
export type ResourceTree<T> = { "ResourceGroup": ResourceGroupNode<T> } | { "Resource": T };
