// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for requesting a resource group timeline.
 */
export type ResourceGroupTimelineRequestParams = { 
/**
 * The type name of the FSM for which to produce the resource utilization timeline.
 *
 * If set, only include utilizations from FSMs with this type name, and
 * aggregate for each state separately.
 */
fsm_type_name: string | null, 
/**
 * The type name of the leaf resources for which to produce the timeline for this group.
 */
resource_type_name: string, 
/**
 * Filter the usages of the leaf resources by this operator ID.
 *
 * TODO(johanpel): this will only work for FSMs directly referencing this operator.
 */
operator_id: string | null, };
