// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A type of [`ResourceGroup`].
 */
export type ResourceGroupTypeDecl = { 
/**
 * The name of the type of Resource Group
 */
name: string, 
/**
 * The type names of the entities that used Resource of this group.
 */
used_by_entity_types: Array<string>, 
/**
 * The type names of the leaf Resources in this group or its children.
 */
contains_resource_types: Array<string>, };
