// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineConfig } from "./TimelineConfig";
import type { TimelineRequest } from "./TimelineRequest";

/**
 * Request for a single timeline.
 */
export type SingleTimelineRequest<GlobalParams, TimelineParams> = { 
/**
 * The configuration of the window and number of bins.
 */
config: TimelineConfig, 
/**
 * The timeline requested.
 */
entry: TimelineRequest<TimelineParams>, 
/**
 * Global application-specific parameters, e.g. filters.
 */
app_params: GlobalParams, };
