// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { ResourceTimeline } from "./ResourceTimeline";

export type SingleTimelineResponse = { 
/**
 * The configuration of the binned timeline.
 *
 * This may slightly differ from the requested configuration to ensure
 * bounds are not exceeded and bin sizes are equal.
 */
config: BinnedSpanSec, 
/**
 * The data of the response.
 */
data: ResourceTimeline, };
