// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntitySortKey } from "./EntitySortKey";
import type { SortDir } from "./SortDir";

/**
 * Sorting parameters.
 */
export type Sort = {
  /**
   * The key to sort on.
   */
  key: EntitySortKey;
  /**
   * The direction to sort in.
   */
  dir: SortDir;
};
