// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span of time in seconds.
 */
export type SpanSec = { 
/**
 * The start time, inclusive.
 */
start: number, 
/**
 * The end time, exclusive.
 */
end: number, };
