// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceGroupTimelineRequest } from "./ResourceGroupTimelineRequest";
import type { ResourceTimelineRequest } from "./ResourceTimelineRequest";

/**
 * Timeline request parameters unrelated to timing or binning.
 */
export type TimelineRequest<TimelineParams> = { "Resource": ResourceTimelineRequest<TimelineParams> } | { "ResourceGroup": ResourceGroupTimelineRequest<TimelineParams> };
