// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time window, resolved against an epoch supplied at conversion.
 */
export type TimeWindow = { 
/**
 * The start time of the window in seconds.
 */
start: number, 
/**
 * The end time of the window in seconds.
 */
end: number, };
