// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A worker that executed a leaf [`Plan`].
 */
export type Worker = { 
/**
 * The ID of this [`Worker`].
 */
id: string, 
/**
 * The ID of the [`Engine`] to which this [`Worker`] belongs.
 */
parent_engine_id: string | null, 
/**
 * The name of this [`Worker`].
 */
instance_name: string | null, 
/**
 * The time at which this [`Worker`] started, relative to the engine.
 */
start_unix_ns: bigint | null, 
/**
 * The time at which this [`Worker`] exited.
 */
end_unix_ns: bigint | null, };
