// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

use quent_ref_target::RefTarget;
use quent_schema::{DataType, Schema};

use crate::common::{path_pascal, path_snake, py_safe, to_case};
use crate::{GeneratedFile, Options, has_nvtx_source, public_entities};
use convert_case::Case;
use quent_fsm::{Fsm, SEQUENCE_FIELD_NAME};

pub(crate) fn emit(schema: &Schema, options: &Options) -> Vec<GeneratedFile> {
    let has_nvtx_source = has_nvtx_source(schema);
    let mut output = String::from(concat!(
        "# Generated by quent-schema-codegen-python. Do not edit.\n",
        "from __future__ import annotations\n\n",
        "import uuid\n",
        "from collections.abc import Iterable, Mapping, Sequence\n",
        "from os import PathLike\n",
        "from types import TracebackType\n",
        "from typing import TypeAlias, TypedDict\n",
        "\n",
        "class QuentError(Exception): ...\n",
        "class EventAlreadyEmittedError(QuentError): ...\n",
        "class SourceActivationError(QuentError): ...\n",
        "class ContextClosedError(QuentError): ...\n",
        "class HandleConsumedError(QuentError): ...\n\n",
        "def now_v7() -> uuid.UUID: ...\n",
        "def nil_uuid() -> uuid.UUID: ...\n\n",
        "class DynamicValue:\n",
        "    \"\"\"An explicitly typed dynamic attribute value.\"\"\"\n",
        "    @staticmethod\n    def u8(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def u16(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def u32(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def u64(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i8(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i16(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i32(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i64(value: int) -> DynamicValue: ...\n",
        "    @staticmethod\n    def f32(value: float) -> DynamicValue: ...\n",
        "    @staticmethod\n    def f64(value: float) -> DynamicValue: ...\n",
        "    @staticmethod\n    def string(value: str) -> DynamicValue: ...\n",
        "    @staticmethod\n    def structure(value: DynamicAttributes) -> DynamicValue: ...\n",
        "    @staticmethod\n    def u8_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def u16_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def u32_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def u64_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i8_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i16_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i32_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def i64_list(values: Sequence[int]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def f32_list(values: Sequence[float]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def f64_list(values: Sequence[float]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def string_list(values: Sequence[str]) -> DynamicValue: ...\n",
        "    @staticmethod\n    def struct_list(values: Sequence[DynamicAttributes]) -> DynamicValue: ...\n\n",
        "    @staticmethod\n    def list(values: Sequence[DynamicValue]) -> DynamicValue: ...\n\n",
        "DynamicAttributeValue: TypeAlias = bool | int | float | str | DynamicValue | Mapping[str, 'DynamicAttributeValue'] | None\n",
        "DynamicAttributes: TypeAlias = Mapping[str, DynamicAttributeValue]\n\n",
        "class ExporterOptions:\n",
        "    \"\"\"Exporter configuration for a telemetry context.\"\"\"\n",
    ));
    if options.exporters.ndjson {
        output.push_str(
            "    @staticmethod\n    def ndjson(output_dir: str | PathLike[str]) -> ExporterOptions: ...\n",
        );
    }
    if options.exporters.msgpack {
        output.push_str(
            "    @staticmethod\n    def msgpack(output_dir: str | PathLike[str]) -> ExporterOptions: ...\n",
        );
    }
    if options.exporters.postcard {
        output.push_str(
            "    @staticmethod\n    def postcard(output_dir: str | PathLike[str]) -> ExporterOptions: ...\n",
        );
    }
    if options.exporters.collector {
        output.push_str(
            "    @staticmethod\n    def collector(address: str) -> ExporterOptions: ...\n",
        );
    }
    if has_nvtx_source {
        output.push_str(
            "\nclass SourceCapture:\n    \"\"\"Controls private live-capture source activation.\"\"\"\n    Enabled: SourceCapture\n    Disabled: SourceCapture\n",
        );
    }

    for record in schema.records() {
        let name = format!("{}Dict", path_pascal(record.path()));
        output.push_str(&format!("\nclass {name}(TypedDict):\n"));
        if record.fields().next().is_none() {
            output.push_str("    pass\n");
        } else {
            for field in record.fields() {
                output.push_str(&format!(
                    "    {}: {}\n",
                    py_safe(&to_case(field.name(), Case::Snake)),
                    py_type(schema, field.ty()),
                ));
            }
        }
        output.push_str(&format!(
            "\n{}Input: TypeAlias = {name} | Mapping[str, object]\n",
            path_pascal(record.path()),
        ));
    }

    let mut reference_types = BTreeMap::new();
    for record in schema.records() {
        for field in record.fields() {
            collect_reference_types(schema, field.ty(), &mut reference_types);
        }
    }
    for entity in public_entities(schema) {
        for event in entity.events() {
            for field in event.fields() {
                collect_reference_types(schema, field.ty(), &mut reference_types);
            }
        }
    }
    for (name, (target, data)) in reference_types {
        output.push_str(&format!(
            "\nclass {name}(TypedDict):\n    target: {target}\n    data: {data}\n"
        ));
        output.push_str(&format!(
            "\n{}Input: TypeAlias = {name} | Mapping[str, object]\n",
            name.trim_end_matches("Dict"),
        ));
    }

    output.push_str(
        "\nclass Context:\n    \"\"\"Owns observer factories for one telemetry context.\"\"\"\n",
    );
    if has_nvtx_source {
        output.push_str("    def __init__(self, options: ExporterOptions | None = None, *, source_capture: SourceCapture = SourceCapture.Enabled) -> None: ...\n");
    } else {
        output.push_str(
            "    def __init__(self, options: ExporterOptions | None = None) -> None: ...\n",
        );
    }
    output.push_str("    @property\n    def id(self) -> uuid.UUID: ...\n");
    output.push_str("    @property\n    def closed(self) -> bool: ...\n");
    output.push_str("    def close(self) -> None: ...\n");
    output.push_str("    def __enter__(self) -> Context: ...\n");
    output.push_str("    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> None: ...\n");
    for entity in public_entities(schema) {
        let method = py_safe(&format!("{}_observer", path_snake(entity.path())));
        output.push_str(&format!(
            "    def {method}(self) -> {}Observer: ...\n",
            path_pascal(entity.path()),
        ));
    }

    for entity in public_entities(schema) {
        let name = path_pascal(entity.path());
        output.push_str(&format!(
            "\nclass {name}Observer:\n    \"\"\"Creates handles for `{}` entities.\"\"\"\n    def handle(self, id: uuid.UUID | None = None) -> {name}Handle: ...\n",
            entity.path(),
        ));
        if let Some(fsm) = Fsm::try_from_entity(entity).ok().flatten() {
            emit_fsm_handles(&mut output, schema, entity, &fsm);
        } else {
            output.push_str(&format!(
                "\nclass {name}Handle:\n    \"\"\"Emits events for one `{}` entity.\"\"\"\n    @property\n    def uuid(self) -> uuid.UUID: ...\n    def __repr__(self) -> str: ...\n",
                entity.path(),
            ));
            for event in entity.events() {
                emit_event_method(&mut output, schema, event, "None", false);
                if event.cardinality() == quent_schema::Cardinality::Once {
                    let emitted =
                        py_safe(&format!("{}_emitted", to_case(event.name(), Case::Snake)));
                    output.push_str(&format!("    def {emitted}(self) -> bool: ...\n",));
                }
            }
        }
    }

    let module_path = options.module_name.replace('.', "/");
    let stub_name = if options.module_name.contains('.') {
        format!("{module_path}.pyi")
    } else {
        format!("{module_path}/__init__.pyi")
    };
    let package = options
        .module_name
        .split('.')
        .next()
        .unwrap_or(&options.module_name);
    vec![
        GeneratedFile {
            name: stub_name,
            content: output,
        },
        GeneratedFile {
            name: format!("{package}/py.typed"),
            content: String::new(),
        },
    ]
}

fn emit_fsm_handles(
    output: &mut String,
    schema: &Schema,
    entity: &quent_schema::Entity,
    fsm: &Fsm,
) {
    let entity_name = path_pascal(entity.path());
    let initial = entity
        .event(fsm.initial_state())
        .expect("validated FSM initial state");
    output.push_str(&format!(
        "\nclass {entity_name}Handle:\n    \"\"\"Starts one `{}` state machine.\"\"\"\n    @property\n    def uuid(self) -> uuid.UUID: ...\n    def __repr__(self) -> str: ...\n",
        entity.path(),
    ));
    let initial_target = state_handle_name(entity, initial.name());
    emit_event_method(output, schema, initial, &initial_target, true);

    for state in entity.events() {
        let class_name = state_handle_name(entity, state.name());
        output.push_str(&format!(
            "\nclass {class_name}:\n    \"\"\"Represents a `{}` entity in the `{}` state.\"\"\"\n    @property\n    def uuid(self) -> uuid.UUID: ...\n    def __repr__(self) -> str: ...\n",
            entity.path(),
            state.name(),
        ));
        for transition in fsm
            .transitions()
            .iter()
            .filter(|transition| transition.source() == state.name())
        {
            let target = entity
                .event(transition.target())
                .expect("validated FSM transition target");
            let target_name = state_handle_name(entity, target.name());
            emit_event_method(output, schema, target, &target_name, true);
        }
    }
}

fn emit_event_method(
    output: &mut String,
    schema: &Schema,
    event: &quent_schema::Event,
    return_type: &str,
    skip_sequence: bool,
) {
    let params = event
        .fields()
        .filter(|field| !skip_sequence || field.name() != SEQUENCE_FIELD_NAME)
        .map(|field| {
            format!(
                "{}: {}",
                py_safe(&to_case(field.name(), Case::Snake)),
                py_type(schema, field.ty()),
            )
        })
        .collect::<Vec<_>>();
    let suffix = if params.is_empty() {
        String::new()
    } else {
        format!(", *, {}", params.join(", "))
    };
    output.push_str(&format!(
        "    def {}(self{suffix}) -> {return_type}: ...\n",
        py_safe(&to_case(event.name(), Case::Snake)),
    ));
}

fn state_handle_name(entity: &quent_schema::Entity, state: &quent_schema::Identifier) -> String {
    format!(
        "{}{}Handle",
        path_pascal(entity.path()),
        to_case(state, Case::Pascal),
    )
}

fn entity_reference_type(schema: &Schema, path: &quent_schema::Path) -> String {
    let entity = schema
        .entity(path)
        .expect("validated entity reference target");
    let mut handles = vec![format!("{}Handle", path_pascal(path))];
    if Fsm::try_from_entity(entity).ok().flatten().is_some() {
        handles.extend(
            entity
                .events()
                .map(|state| state_handle_name(entity, state.name())),
        );
    }
    handles.push("uuid.UUID".to_owned());
    handles.join(" | ")
}

fn py_type(schema: &Schema, ty: &DataType) -> String {
    match ty {
        DataType::Bool => "bool".to_owned(),
        DataType::Uuid => "uuid.UUID".to_owned(),
        DataType::String => "str".to_owned(),
        DataType::U8
        | DataType::U16
        | DataType::U32
        | DataType::U64
        | DataType::I8
        | DataType::I16
        | DataType::I32
        | DataType::I64 => "int".to_owned(),
        DataType::F32 | DataType::F64 => "float".to_owned(),
        DataType::Option(inner) => format!("{} | None", py_type(schema, inner)),
        DataType::List(inner) => format!("Iterable[{}]", py_type(schema, inner)),
        DataType::Record(path) => format!("{}Input", path_pascal(path)),
        DataType::DynamicRecord => "DynamicAttributes".to_owned(),
        DataType::EntityRef { data, annotations } => {
            let target = RefTarget::from_annotations(annotations)
                .map(|target| entity_reference_type(schema, target.as_ref()))
                .unwrap_or_else(|| "uuid.UUID".to_owned());
            match data {
                Some(data) => format!(
                    "{}Input",
                    ref_stub_name(data, annotations).trim_end_matches("Dict")
                ),
                None => target,
            }
        }
    }
}

fn collect_reference_types(
    schema: &Schema,
    ty: &DataType,
    output: &mut BTreeMap<String, (String, String)>,
) {
    match ty {
        DataType::Option(inner) | DataType::List(inner) => {
            collect_reference_types(schema, inner, output)
        }
        DataType::EntityRef {
            data: Some(data),
            annotations,
        } => {
            let target = RefTarget::from_annotations(annotations)
                .map(|target| entity_reference_type(schema, target.as_ref()))
                .unwrap_or_else(|| "uuid.UUID".to_owned());
            output
                .entry(ref_stub_name(data, annotations))
                .or_insert_with(|| (target, py_type(schema, data)));
            collect_reference_types(schema, data, output);
        }
        _ => {}
    }
}

pub(crate) fn ref_stub_name(data: &DataType, annotations: &quent_schema::Annotations) -> String {
    let target = RefTarget::from_annotations(annotations)
        .map(|target| path_pascal(target.as_ref()))
        .unwrap_or_else(|| "AnyEntity".to_owned());
    let data = type_key(data);
    if data
        .strip_prefix(&target)
        .is_some_and(|suffix| !suffix.is_empty())
    {
        format!("{data}RefDict")
    } else {
        format!("{target}{data}RefDict")
    }
}

fn type_key(ty: &DataType) -> String {
    match ty {
        DataType::Bool => "Bool".to_owned(),
        DataType::Uuid => "Uuid".to_owned(),
        DataType::String => "String".to_owned(),
        DataType::U8 => "U8".to_owned(),
        DataType::U16 => "U16".to_owned(),
        DataType::U32 => "U32".to_owned(),
        DataType::U64 => "U64".to_owned(),
        DataType::I8 => "I8".to_owned(),
        DataType::I16 => "I16".to_owned(),
        DataType::I32 => "I32".to_owned(),
        DataType::I64 => "I64".to_owned(),
        DataType::F32 => "F32".to_owned(),
        DataType::F64 => "F64".to_owned(),
        DataType::Option(inner) => format!("Optional{}", type_key(inner)),
        DataType::List(inner) => format!("{}List", type_key(inner)),
        DataType::Record(path) => path_pascal(path),
        DataType::DynamicRecord => "DynamicAttributes".to_owned(),
        DataType::EntityRef { data, annotations } => match data {
            Some(data) => ref_stub_name(data, annotations)
                .trim_end_matches("Dict")
                .to_owned(),
            None => RefTarget::from_annotations(annotations)
                .map(|target| format!("{}Ref", path_pascal(target.as_ref())))
                .unwrap_or_else(|| "AnyEntityRef".to_owned()),
        },
    }
}
use std::collections::BTreeMap;
