// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

use quent_ref_target::RefTarget;
use quent_schema::{DataType, Schema};

use crate::common::{path_pascal, path_snake, py_safe, to_case};
use crate::{GeneratedFile, Options};
use convert_case::Case;

pub(crate) fn emit(schema: &Schema, options: &Options) -> Vec<GeneratedFile> {
    let mut output = String::from(concat!(
        "# Generated by quent-schema-codegen-python. Do not edit.\n",
        "from __future__ import annotations\n\n",
        "from collections.abc import Mapping\n",
        "from os import PathLike\n",
        "from typing import TypedDict\n\n",
        "def now_v7() -> Uuid: ...\n",
        "def nil_uuid() -> Uuid: ...\n\n",
        "class Uuid:\n",
        "    def __repr__(self) -> str: ...\n",
        "    def __str__(self) -> str: ...\n",
        "    def __eq__(self, other: object) -> bool: ...\n",
        "    def __hash__(self) -> int: ...\n\n",
        "class ExporterOptions:\n",
        "    @staticmethod\n",
        "    def none() -> ExporterOptions: ...\n",
    ));
    if options.exporters.ndjson {
        output.push_str(
            "    @staticmethod\n    def ndjson(output_dir: str | PathLike[str]) -> ExporterOptions: ...\n",
        );
    }
    if options.exporters.msgpack {
        output.push_str(
            "    @staticmethod\n    def msgpack(output_dir: str | PathLike[str]) -> ExporterOptions: ...\n",
        );
    }
    if options.exporters.postcard {
        output.push_str(
            "    @staticmethod\n    def postcard(output_dir: str | PathLike[str]) -> ExporterOptions: ...\n",
        );
    }
    if options.exporters.collector {
        output.push_str(
            "    @staticmethod\n    def collector(address: str) -> ExporterOptions: ...\n",
        );
    }

    for record in schema.records() {
        let name = format!("{}Dict", path_pascal(record.path()));
        output.push_str(&format!("\nclass {name}(TypedDict):\n"));
        if record.fields().next().is_none() {
            output.push_str("    pass\n");
        } else {
            for field in record.fields() {
                output.push_str(&format!(
                    "    {}: {}\n",
                    py_safe(&to_case(field.name(), Case::Snake)),
                    py_type(field.ty()),
                ));
            }
        }
    }

    let mut reference_types = BTreeMap::new();
    for record in schema.records() {
        for field in record.fields() {
            collect_reference_types(field.ty(), &mut reference_types);
        }
    }
    for entity in schema.entities() {
        for event in entity.events() {
            for field in event.fields() {
                collect_reference_types(field.ty(), &mut reference_types);
            }
        }
    }
    for (name, (target, data)) in reference_types {
        output.push_str(&format!(
            "\nclass {name}(TypedDict):\n    target: {target}\n    data: {data}\n"
        ));
    }

    output.push_str("\nclass Context:\n");
    output
        .push_str("    def __init__(self, options: ExporterOptions | None = None) -> None: ...\n");
    output.push_str("    @property\n    def id(self) -> Uuid: ...\n");
    output.push_str("    def close(self) -> None: ...\n");
    output.push_str("    def __enter__(self) -> Context: ...\n");
    output.push_str("    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...\n");
    for entity in schema.entities() {
        let method = py_safe(&format!("{}_observer", path_snake(entity.path())));
        output.push_str(&format!(
            "    def {method}(self) -> {}Observer: ...\n",
            path_pascal(entity.path()),
        ));
    }

    for entity in schema.entities() {
        let name = path_pascal(entity.path());
        output.push_str(&format!(
            "\nclass {name}Observer:\n    def create(self, id: Uuid | None = None) -> {name}Handle: ...\n"
        ));
        output.push_str(&format!(
            "\nclass {name}Handle:\n    @property\n    def uuid(self) -> Uuid: ...\n"
        ));
        for event in entity.events() {
            let params = event
                .fields()
                .map(|field| {
                    format!(
                        "{}: {}",
                        py_safe(&to_case(field.name(), Case::Snake)),
                        py_type(field.ty()),
                    )
                })
                .collect::<Vec<_>>();
            let suffix = if params.is_empty() {
                String::new()
            } else {
                format!(", *, {}", params.join(", "))
            };
            output.push_str(&format!(
                "    def {}(self{suffix}) -> None: ...\n",
                py_safe(&to_case(event.name(), Case::Snake)),
            ));
            if event.cardinality() == quent_schema::Cardinality::Once {
                let emitted = py_safe(&format!("{}_emitted", to_case(event.name(), Case::Snake)));
                output.push_str(&format!("    def {emitted}(self) -> bool: ...\n",));
            }
        }
    }

    let module_path = options.module_name.replace('.', "/");
    let stub_name = if options.module_name.contains('.') {
        format!("{module_path}.pyi")
    } else {
        format!("{module_path}/__init__.pyi")
    };
    let package = options
        .module_name
        .split('.')
        .next()
        .unwrap_or(&options.module_name);
    vec![
        GeneratedFile {
            name: stub_name,
            content: output,
        },
        GeneratedFile {
            name: format!("{package}/py.typed"),
            content: String::new(),
        },
    ]
}

fn py_type(ty: &DataType) -> String {
    match ty {
        DataType::Bool => "bool".to_owned(),
        DataType::Uuid => "Uuid".to_owned(),
        DataType::String => "str".to_owned(),
        DataType::U8
        | DataType::U16
        | DataType::U32
        | DataType::U64
        | DataType::I8
        | DataType::I16
        | DataType::I32
        | DataType::I64 => "int".to_owned(),
        DataType::F32 | DataType::F64 => "float".to_owned(),
        DataType::Option(inner) => format!("{} | None", py_type(inner)),
        DataType::List(inner) => format!("list[{}]", py_type(inner)),
        DataType::Record(path) => format!("{}Dict", path_pascal(path)),
        DataType::DynamicRecord => "Mapping[str, bool | int | float | str | None]".to_owned(),
        DataType::EntityRef { data, annotations } => {
            let target = RefTarget::from_annotations(annotations)
                .map(|target| format!("{}Handle | Uuid", path_pascal(target.as_ref())))
                .unwrap_or_else(|| "Uuid".to_owned());
            match data {
                Some(data) => ref_stub_name(data, annotations),
                None => target,
            }
        }
    }
}

fn collect_reference_types(ty: &DataType, output: &mut BTreeMap<String, (String, String)>) {
    match ty {
        DataType::Option(inner) | DataType::List(inner) => collect_reference_types(inner, output),
        DataType::EntityRef {
            data: Some(data),
            annotations,
        } => {
            let target = RefTarget::from_annotations(annotations)
                .map(|target| format!("{}Handle | Uuid", path_pascal(target.as_ref())))
                .unwrap_or_else(|| "Uuid".to_owned());
            output
                .entry(ref_stub_name(data, annotations))
                .or_insert_with(|| (target, py_type(data)));
            collect_reference_types(data, output);
        }
        _ => {}
    }
}

pub(crate) fn ref_stub_name(data: &DataType, annotations: &quent_schema::Annotations) -> String {
    let target = RefTarget::from_annotations(annotations)
        .map(|target| path_pascal(target.as_ref()))
        .unwrap_or_else(|| "AnyEntity".to_owned());
    let data = type_key(data);
    if data
        .strip_prefix(&target)
        .is_some_and(|suffix| !suffix.is_empty())
    {
        format!("{data}RefDict")
    } else {
        format!("{target}{data}RefDict")
    }
}

fn type_key(ty: &DataType) -> String {
    match ty {
        DataType::Bool => "Bool".to_owned(),
        DataType::Uuid => "Uuid".to_owned(),
        DataType::String => "String".to_owned(),
        DataType::U8 => "U8".to_owned(),
        DataType::U16 => "U16".to_owned(),
        DataType::U32 => "U32".to_owned(),
        DataType::U64 => "U64".to_owned(),
        DataType::I8 => "I8".to_owned(),
        DataType::I16 => "I16".to_owned(),
        DataType::I32 => "I32".to_owned(),
        DataType::I64 => "I64".to_owned(),
        DataType::F32 => "F32".to_owned(),
        DataType::F64 => "F64".to_owned(),
        DataType::Option(inner) => format!("Optional{}", type_key(inner)),
        DataType::List(inner) => format!("{}List", type_key(inner)),
        DataType::Record(path) => path_pascal(path),
        DataType::DynamicRecord => "DynamicAttributes".to_owned(),
        DataType::EntityRef { data, annotations } => match data {
            Some(data) => ref_stub_name(data, annotations)
                .trim_end_matches("Dict")
                .to_owned(),
            None => RefTarget::from_annotations(annotations)
                .map(|target| format!("{}Ref", path_pascal(target.as_ref())))
                .unwrap_or_else(|| "AnyEntityRef".to_owned()),
        },
    }
}
use std::collections::BTreeMap;
