[package]
name = "quent-simulator-fixed"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
clap = { version = "4.5.57", features = ["derive", "env"] }
quent-time = { path = "../../../../../crates/time", features = ["__test-clock-override"] }
quent-dynamic-attributes = { path = "../../../../../crates/dynamic-attributes" }
quent-io = { path = "../../../../../crates/io", features = ["clap"] }
quent-simulator-instrumentation = { path = "../../instrumentation" }
uuid = { workspace = true }

[dev-dependencies]
quent-events = { workspace = true }
quent-instrumentation = { path = "../../../../../crates/instrumentation" }
quent-simulator-analyzer = { path = "../../analyzer" }
quent-simulator-store = { path = "../../store" }
quent-store = { path = "../../../../../crates/store", features = ["io-ndjson"] }
quent-query-engine-analyzer = { path = "../../../../../domains/query_engine/analyzer" }
quent-query-engine-ui = { path = "../../../../../domains/query_engine/ui" }
quent-ui = { path = "../../../../../crates/ui" }
tempfile = "3"
