[package]
name = "quent-query-engine-fixed"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
clap = { version = "4.5.57", features = ["derive", "env"] }
quent-time = { path = "../../../../crates/time", features = ["__test-clock-override"] }
quent-model = { path = "../../../../crates/model" }
quent-dynamic-attributes = { path = "../../../../crates/dynamic-attributes" }
quent-io = { path = "../../../../crates/io", features = ["clap"] }
quent-query-engine-model = { path = "../../model" }
quent-simulator-instrumentation = { path = "../../../simulator/instrumentation" }
quent-stdlib = { path = "../../../../crates/stdlib" }
uuid = { workspace = true }

[dev-dependencies]
quent-simulator-analyzer = { path = "../../../simulator/analyzer" }
quent-query-engine-analyzer = { path = "../../analyzer" }
quent-query-engine-ui = { path = "../../ui" }
quent-ui = { path = "../../../../crates/ui" }
