pub struct List {
    pub(crate) inner: quent_events::attributes::List,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for List {
    type Id = cxx::type_id!("quent::attributes::list");
    type Kind = cxx::kind::Opaque;
}

impl List {
    pub fn new_u8(values: Vec<u8>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::U8(values),
        })
    }

    pub fn new_u16(values: Vec<u16>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::U16(values),
        })
    }

    pub fn new_u32(values: Vec<u32>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::U32(values),
        })
    }

    pub fn new_u64(values: Vec<u64>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::U64(values),
        })
    }

    pub fn new_i8(values: Vec<i8>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::I8(values),
        })
    }

    pub fn new_i16(values: Vec<i16>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::I16(values),
        })
    }

    pub fn new_i32(values: Vec<i32>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::I32(values),
        })
    }

    pub fn new_i64(values: Vec<i64>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::I64(values),
        })
    }

    pub fn new_f32(values: Vec<f32>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::F32(values),
        })
    }

    pub fn new_f64(values: Vec<f64>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::F64(values),
        })
    }

    pub fn new_string(values: Vec<String>) -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::String(values),
        })
    }

    pub fn new_struct_empty() -> Box<Self> {
        Box::new(List {
            inner: quent_events::attributes::List::Struct(Vec::new()),
        })
    }

    #[allow(clippy::boxed_local)]
    pub fn add_struct(&mut self, s: Box<super::quent_struct::QuentStruct>) {
        match &mut self.inner {
            quent_events::attributes::List::Struct(v) => {
                v.push(s.inner);
            }
            _ => {
                // This is a programming error - cannot add struct to non-struct list
                panic!("Cannot add struct to non-struct list");
            }
        }
    }

    pub fn len(&self) -> usize {
        match &self.inner {
            quent_events::attributes::List::U8(v) => v.len(),
            quent_events::attributes::List::U16(v) => v.len(),
            quent_events::attributes::List::U32(v) => v.len(),
            quent_events::attributes::List::U64(v) => v.len(),
            quent_events::attributes::List::I8(v) => v.len(),
            quent_events::attributes::List::I16(v) => v.len(),
            quent_events::attributes::List::I32(v) => v.len(),
            quent_events::attributes::List::I64(v) => v.len(),
            quent_events::attributes::List::F32(v) => v.len(),
            quent_events::attributes::List::F64(v) => v.len(),
            quent_events::attributes::List::String(v) => v.len(),
            quent_events::attributes::List::Struct(v) => v.len(),
        }
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

#[cxx::bridge(namespace = "quent::attributes")]
mod ffi {
    #[namespace = "quent::attributes"]
    extern "C++" {
        include!("quent-cpp/src/attributes/quent_struct.rs.h");
        #[cxx_name = "quent_struct"]
        type QuentStruct = crate::attributes::quent_struct::QuentStruct;
    }

    extern "Rust" {
        #[cxx_name = "list"]
        type List;

        // List constructors
        #[Self = "List"]
        fn new_u8(values: Vec<u8>) -> Box<List>;
        #[Self = "List"]
        fn new_u16(values: Vec<u16>) -> Box<List>;
        #[Self = "List"]
        fn new_u32(values: Vec<u32>) -> Box<List>;
        #[Self = "List"]
        fn new_u64(values: Vec<u64>) -> Box<List>;
        #[Self = "List"]
        fn new_i8(values: Vec<i8>) -> Box<List>;
        #[Self = "List"]
        fn new_i16(values: Vec<i16>) -> Box<List>;
        #[Self = "List"]
        fn new_i32(values: Vec<i32>) -> Box<List>;
        #[Self = "List"]
        fn new_i64(values: Vec<i64>) -> Box<List>;
        #[Self = "List"]
        fn new_f32(values: Vec<f32>) -> Box<List>;
        #[Self = "List"]
        fn new_f64(values: Vec<f64>) -> Box<List>;
        #[Self = "List"]
        fn new_string(values: Vec<String>) -> Box<List>;
        #[Self = "List"]
        fn new_struct_empty() -> Box<List>;

        // List methods
        fn add_struct(self: &mut List, s: Box<QuentStruct>);
        fn len(self: &List) -> usize;
        fn is_empty(self: &List) -> bool;
    }
}
