pub mod list;
pub mod quent_struct;
pub mod value;

pub use list::List;
pub use quent_struct::QuentStruct;
pub use quent_struct::QuentStruct as Struct;
pub use value::Value;

#[derive(Clone, Debug)]
pub struct Attribute {
    pub(crate) inner: quent_attributes::Attribute,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for Attribute {
    type Id = cxx::type_id!("quent::attributes::attribute");
    type Kind = cxx::kind::Opaque;
}

impl Attribute {
    pub fn new(key: String, value: Option<value::Value>) -> Self {
        Attribute {
            inner: quent_attributes::Attribute {
                key,
                value: value.map(|v| v.inner),
            },
        }
    }

    #[allow(clippy::boxed_local)]
    pub fn new_boxed(key: String, value: Box<Option<value::Value>>) -> Box<Self> {
        Box::new(Attribute::new(key, *value))
    }

    pub fn key(&self) -> &str {
        &self.inner.key
    }
}

#[cxx::bridge(namespace = "quent::attributes")]
mod ffi {
    extern "Rust" {
        #[cxx_name = "attribute"]
        type Attribute;

    }
}
