pub struct QuentStruct {
    pub(crate) inner: quent_attributes::Struct,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for QuentStruct {
    type Id = cxx::type_id!("quent::attributes::quent_struct");
    type Kind = cxx::kind::Opaque;
}

impl QuentStruct {
    pub fn new(attributes: Vec<Box<super::Attribute>>) -> Box<Self> {
        Box::new(QuentStruct {
            inner: quent_attributes::Struct(
                attributes.into_iter().map(|attr| attr.inner).collect(),
            ),
        })
    }

    pub fn new_empty() -> Box<Self> {
        Box::new(QuentStruct {
            inner: quent_attributes::Struct(Vec::new()),
        })
    }

    pub fn len(&self) -> usize {
        self.inner.0.len()
    }

    pub fn is_empty(&self) -> bool {
        self.inner.0.is_empty()
    }
}

pub fn new_struct(attributes: Vec<super::Attribute>) -> Box<QuentStruct> {
    QuentStruct::new(attributes.into_iter().map(Box::new).collect())
}

#[cxx::bridge(namespace = "quent::attributes")]
mod ffi {
    extern "Rust" {
        #[cxx_name = "quent_struct"]
        type QuentStruct;

        // Struct constructors
        #[Self = "QuentStruct"]
        fn new_empty() -> Box<QuentStruct>;

        // Struct methods
        fn len(self: &QuentStruct) -> usize;
        fn is_empty(self: &QuentStruct) -> bool;
    }
}
