use crate::uuid::ffi::UUID;

pub struct EngineObserver {
    pub(crate) inner: quent::EngineObserver,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for EngineObserver {
    type Id = cxx::type_id!("quent::engine::engine_observer");
    type Kind = cxx::kind::Opaque;
}

impl EngineObserver {
    pub fn init(&self, id: UUID, init: ffi::Init) {
        let implementation = {
            let ffi::EngineImplementationAttributes {
                name,
                version,
                // custom_attributes,
            } = init.implementation;
            if name.is_empty() && version.is_empty() {
                None
            } else {
                Some(quent_events::engine::EngineImplementationAttributes {
                    name: (!name.is_empty()).then_some(name),
                    version: (!version.is_empty()).then_some(version),
                    custom_attributes: Vec::new(),
                })
            }
        };

        self.inner.init(
            id.into(),
            quent_events::engine::Init {
                implementation,
                name: (!init.name.is_empty()).then_some(init.name),
            },
        );
    }

    pub fn operating(&self, id: UUID) {
        self.inner
            .operating(id.into(), quent_events::engine::Operating {});
    }

    pub fn finalizing(&self, id: UUID) {
        self.inner
            .finalizing(id.into(), quent_events::engine::Finalizing {});
    }

    pub fn exit(&self, id: UUID) {
        self.inner.exit(id.into(), quent_events::engine::Exit {});
    }
}

#[cxx::bridge(namespace = "quent::engine")]
mod ffi {

    #[namespace = "quent::attributes"]
    extern "C++" {
        include!("quent-cpp/src/attributes/mod.rs.h");
        #[cxx_name = "attribute"]
        type Attribute = crate::attributes::Attribute;
    }

    /// Attributes describing details about the implementation of this Engine
    #[cxx_name = "engine_implementation_attributes"]
    // #[derive(Clone)]
    pub struct EngineImplementationAttributes {
        /// (Optional) The name of this Engine implementation, e.g. "SiriusDB", "Velox", "DataFusion", etc.
        pub name: String,
        /// (Optional) The version of this Engine implementation, e.g. "13.3.7"
        pub version: String,
        // // Arbitrary attributes defined at run time.
        // pub custom_attributes: &'a CxxVector<Attribute>,
    }

    #[cxx_name = "init"]
    // #[derive(Clone)]
    pub struct Init {
        /// Optional
        pub implementation: EngineImplementationAttributes,
        /// Optional
        pub name: String,
    }

    #[namespace = "uuid"]
    extern "C++" {
        include!("quent-cpp/src/uuid.rs.h");
        type UUID = crate::uuid::ffi::UUID;
    }

    extern "Rust" {
        #[cxx_name = "engine_observer"]
        type EngineObserver;
        fn init(self: &EngineObserver, id: UUID, init: Init);
        fn operating(self: &EngineObserver, id: UUID);
        fn finalizing(self: &EngineObserver, id: UUID);
        fn exit(self: &EngineObserver, id: UUID);
    }
}
