use crate::uuid::ffi::UUID;

pub struct OperatorObserver {
    pub(crate) inner: quent::OperatorObserver,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for OperatorObserver {
    type Id = cxx::type_id!("quent::plan_operator::operator_observer");
    type Kind = cxx::kind::Opaque;
}

impl OperatorObserver {
    pub fn init(&self, id: UUID, init: ffi::Init) {
        let ports = init
            .ports
            .iter()
            .map(|port| quent_events::operator::Port {
                id: port.id.into(),
                name: port.name.clone(),
            })
            .collect();

        let parent_operator_ids = init.ports.into_iter().map(|p| p.id.into()).collect();

        self.inner.init(
            id.into(),
            quent_events::operator::Init {
                plan_id: init.plan_id.into(),
                parent_operator_ids,
                name: (!init.name.is_empty()).then_some(init.name),
                ports,
            },
        );
    }

    pub fn waiting_for_inputs(&self, id: UUID, ports: Vec<ffi::PortId>) {
        // TODO: Add ports parameter once cxx supports Vec<UUID>
        self.inner.waiting_for_inputs(
            id.into(),
            quent_events::operator::WaitingForInputs {
                ports: ports.into_iter().map(|p| p.id.into()).collect(),
            },
        );
    }

    pub fn executing(&self, id: UUID) {
        self.inner
            .executing(id.into(), quent_events::operator::Executing {});
    }

    pub fn blocked(&self, id: UUID) {
        self.inner
            .blocked(id.into(), quent_events::operator::Blocked {});
    }

    pub fn finalizing(&self, id: UUID) {
        self.inner
            .finalizing(id.into(), quent_events::operator::Finalizing {});
    }

    pub fn exit(&self, id: UUID) {
        self.inner.exit(id.into(), quent_events::operator::Exit {});
    }
}

#[cxx::bridge(namespace = "quent::plan_operator")]
mod ffi {
    #[namespace = "uuid"]
    extern "C++" {
        include!("quent-cpp/src/uuid.rs.h");
        type UUID = crate::uuid::ffi::UUID;
    }

    #[cxx_name = "port"]
    #[derive(Debug)]
    pub struct Port {
        pub id: UUID,
        /// Optional
        pub name: String,
    }

    #[cxx_name = "port_id"]
    #[derive(Debug)]
    // cxx.rs does not support Vec<UUID> here
    // because UUID is included as an extern C++ type
    pub struct PortId {
        pub id: UUID,
    }

    #[cxx_name = "init"]
    #[derive(Debug)]
    pub struct Init {
        pub plan_id: UUID,
        pub parent_operator_ids: Vec<PortId>,
        /// Optional
        pub name: String,
        pub ports: Vec<Port>,
    }

    extern "Rust" {
        #[cxx_name = "operator_observer"]
        type OperatorObserver;
        fn init(self: &OperatorObserver, id: UUID, init: Init);
        fn waiting_for_inputs(self: &OperatorObserver, id: UUID, ports: Vec<PortId>);
        fn executing(self: &OperatorObserver, id: UUID);
        fn blocked(self: &OperatorObserver, id: UUID);
        fn finalizing(self: &OperatorObserver, id: UUID);
        fn exit(self: &OperatorObserver, id: UUID);
    }
}
