use crate::uuid::ffi::UUID;

pub struct PlanObserver {
    pub(crate) inner: quent::PlanObserver,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for PlanObserver {
    type Id = cxx::type_id!("quent::plan::plan_observer");
    type Kind = cxx::kind::Opaque;
}

impl PlanObserver {
    pub fn init(&self, id: UUID, init: ffi::Init) {
        let edges = init
            .edges
            .iter()
            .map(|edge| quent_events::plan::Edge {
                source: edge.source_port_id.into(),
                target: edge.sink_port_id.into(),
            })
            .collect();

        self.inner.init(
            id.into(),
            quent_events::plan::Init {
                name: init.name,
                query_id: init.query_id.into(),
                edges,
                worker_id: (!init.worker_id.is_nil())
                    .then_some(Into::<uuid::Uuid>::into(init.worker_id)),
                parent_plan_id: (!init.parent_plan_id.is_nil())
                    .then_some(Into::<uuid::Uuid>::into(init.parent_plan_id)),
            },
        );
    }

    pub fn executing(&self, id: UUID) {
        self.inner
            .executing(id.into(), quent_events::plan::Executing {});
    }

    pub fn idle(&self, id: UUID) {
        self.inner.idle(id.into(), quent_events::plan::Idle {});
    }

    pub fn finalizing(&self, id: UUID) {
        self.inner
            .finalizing(id.into(), quent_events::plan::Finalizing {});
    }

    pub fn exit(&self, id: UUID) {
        self.inner.exit(id.into(), quent_events::plan::Exit {});
    }
}

#[cxx::bridge(namespace = "quent::plan")]
mod ffi {
    #[cxx_name = "edge"]
    #[derive(Debug)]
    pub struct Egde {
        pub source_port_id: UUID,
        pub sink_port_id: UUID,
    }

    #[cxx_name = "init"]
    #[derive(Debug)]
    pub struct Init {
        pub name: String,
        pub query_id: UUID,
        /// A list of plan edges defined as (source port id, sink port id)
        pub edges: Vec<Egde>,

        /// Optional worker_id, nil for None
        pub worker_id: UUID,

        /// Optional parent_plan_id, nil for None
        pub parent_plan_id: UUID,
    }

    #[namespace = "uuid"]
    extern "C++" {
        include!("quent-cpp/src/uuid.rs.h");
        type UUID = crate::uuid::ffi::UUID;
    }

    extern "Rust" {
        #[cxx_name = "plan_observer"]
        type PlanObserver;
        fn init(self: &PlanObserver, id: UUID, init: Init);
        fn executing(self: &PlanObserver, id: UUID);
        fn idle(self: &PlanObserver, id: UUID);
        fn finalizing(self: &PlanObserver, id: UUID);
        fn exit(self: &PlanObserver, id: UUID);
    }
}
