use crate::uuid::ffi::UUID;

pub struct QueryObserver {
    pub(crate) inner: quent::QueryObserver,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for QueryObserver {
    type Id = cxx::type_id!("quent::query::query_observer");
    type Kind = cxx::kind::Opaque;
}

impl QueryObserver {
    pub fn init(&self, id: UUID, init: ffi::Init) {
        self.inner.init(
            id.into(),
            quent_events::query::Init {
                query_group_id: init.query_group_id.into(),
                name: (!init.name.is_empty()).then_some(init.name),
            },
        );
    }

    pub fn planning(&self, id: UUID) {
        self.inner
            .planning(id.into(), quent_events::query::Planning {});
    }

    pub fn executing(&self, id: UUID) {
        self.inner
            .executing(id.into(), quent_events::query::Executing {});
    }

    pub fn idle(&self, id: UUID) {
        self.inner.idle(id.into(), quent_events::query::Idle {});
    }

    pub fn finalizing(&self, id: UUID) {
        self.inner
            .finalizing(id.into(), quent_events::query::Finalizing {});
    }

    pub fn exit(&self, id: UUID) {
        self.inner.exit(id.into(), quent_events::query::Exit {});
    }
}

#[cxx::bridge(namespace = "quent::query")]
mod ffi {
    #[cxx_name = "init"]
    #[derive(Debug)]
    pub struct Init {
        pub query_group_id: UUID,
        /// Optional
        pub name: String,
    }

    #[namespace = "uuid"]
    extern "C++" {
        include!("quent-cpp/src/uuid.rs.h");
        type UUID = crate::uuid::ffi::UUID;
    }

    extern "Rust" {
        #[cxx_name = "query_observer"]
        type QueryObserver;
        fn init(self: &QueryObserver, id: UUID, init: Init);
        fn planning(self: &QueryObserver, id: UUID);
        fn executing(self: &QueryObserver, id: UUID);
        fn idle(self: &QueryObserver, id: UUID);
        fn finalizing(self: &QueryObserver, id: UUID);
        fn exit(self: &QueryObserver, id: UUID);
    }
}
