use crate::uuid::ffi::UUID;

pub struct WorkerObserver {
    pub(crate) inner: quent::WorkerObserver,
}

// Implement ExternType to allow this Rust type to be referenced from other bridges
// See: https://github.com/dtolnay/cxx/issues/942
// The type_id must match the fully qualified C++ type name generated by this bridge
unsafe impl cxx::ExternType for WorkerObserver {
    type Id = cxx::type_id!("quent::worker::worker_observer");
    type Kind = cxx::kind::Opaque;
}

impl WorkerObserver {
    pub fn init(&self, id: UUID, init: ffi::Init) {
        self.inner.init(
            id.into(),
            quent_events::worker::Init {
                engine_id: init.engine_id.into(),
                name: (!init.name.is_empty()).then_some(init.name),
            },
        );
    }

    pub fn operating(&self, id: UUID) {
        self.inner
            .operating(id.into(), quent_events::worker::Operating {});
    }

    pub fn finalizing(&self, id: UUID) {
        self.inner
            .finalizing(id.into(), quent_events::worker::Finalizing {});
    }

    pub fn exit(&self, id: UUID) {
        self.inner.exit(id.into(), quent_events::worker::Exit {});
    }
}

#[cxx::bridge(namespace = "quent::worker")]
mod ffi {
    #[cxx_name = "init"]
    #[derive(Debug)]
    pub struct Init {
        pub engine_id: UUID,
        /// Optional
        pub name: String,
    }

    #[namespace = "uuid"]
    extern "C++" {
        include!("quent-cpp/src/uuid.rs.h");
        type UUID = crate::uuid::ffi::UUID;
    }

    extern "Rust" {
        #[cxx_name = "worker_observer"]
        type WorkerObserver;
        fn init(self: &WorkerObserver, id: UUID, init: Init);
        fn operating(self: &WorkerObserver, id: UUID);
        fn finalizing(self: &WorkerObserver, id: UUID);
        fn exit(self: &WorkerObserver, id: UUID);
    }
}
