// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Build script for `quent-nvtx-injection`.
//!
//! Default/CI builds do nothing but declare the header dependency and
//! `include!` the committed `src/bindings.rs` (D-14) — no bindgen, no libclang,
//! no NVTX git fetch. Bindgen runs ONLY under the `regenerate-bindings` feature;
//! the `static-injection` feature compiles the strong-symbol C shim.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo::rerun-if-changed=wrapper.h");

    #[cfg(feature = "regenerate-bindings")]
    regenerate_bindings()?;

    #[cfg(feature = "static-injection")]
    compile_symbol_shim();

    Ok(())
}

/// Regenerate `src/bindings.rs` from the pinned NVTX headers (D-13/D-14).
///
/// Header sourcing: the `NVTX_INCLUDE_DIR` env var (offline override) if set,
/// otherwise the NVIDIA/NVTX git-dep checkout located via `cargo_metadata`
/// (`<checkout>/c/include`, derived from the `nvidia-nvtx` manifest at
/// `<checkout>/rust/Cargo.toml`).
#[cfg(feature = "regenerate-bindings")]
fn regenerate_bindings() -> Result<(), Box<dyn std::error::Error>> {
    use std::path::PathBuf;

    let include_dir = match std::env::var("NVTX_INCLUDE_DIR") {
        Ok(dir) => PathBuf::from(dir),
        Err(_) => locate_nvtx_include()?,
    };

    let out = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/bindings.rs");

    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_arg(format!("-I{}", include_dir.display()))
        .raw_line("// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.")
        .raw_line("// SPDX-License-Identifier: Apache-2.0")
        .raw_line("//")
        .raw_line("//! Committed bindgen output for the NVTX injection ABI (D-14).")
        .raw_line("//!")
        .raw_line("//! Generated by `build.rs` under the `regenerate-bindings` feature from the")
        .raw_line("//! pinned NVIDIA/NVTX headers (`c/include/nvtx3/nvToolsExt.h`, rev v3.5.0 /")
        .raw_line("//! 7d113f290f89eeeae9c957011c497101f3948d9e). Do NOT edit by hand; re-run")
        .raw_line("//! `cargo build -p quent-nvtx-injection --features regenerate-bindings` after an")
        .raw_line("//! NVTX `rev` bump. Committed so default and CI builds need no libclang and")
        .raw_line("//! fetch no NVTX git source.")
        .raw_line("#![allow(nonstandard_style, dead_code)]")
        .allowlist_type("nvtxEventAttributes_t")
        .allowlist_type("nvtxEventAttributes_v2")
        .allowlist_type("nvtxMessageValue_t")
        .allowlist_type("nvtxDomainHandle_t")
        .allowlist_type("nvtxDomainRegistration")
        .allowlist_type("nvtxStringHandle_t")
        .allowlist_type("nvtxStringRegistration")
        .allowlist_type("NvtxExportTableCallbacks")
        .allowlist_type("NvtxExportTableID")
        .allowlist_type("NvtxCallbackModule")
        .allowlist_type("NvtxCallbackIdCore")
        .allowlist_type("NvtxCallbackIdCore2")
        .allowlist_type("NvtxGetExportTableFunc_t")
        .allowlist_type("NvtxFunctionTable")
        .allowlist_type("NvtxFunctionPointer")
        .allowlist_type("nvtxPayloadType_t")
        .allowlist_type("nvtxMessageType_t")
        .allowlist_type("nvtxColorType_t")
        // IN-04: the allowlist deliberately omits the resource-attribute /
        // range-id ABI types. Those are hand-maintained in `convert::abi` and
        // are NOT regenerated here — a `bindings.rs` produced by this feature
        // will not contain the resource surface, and that is expected.
        .allowlist_var("NVTX_.*")
        .default_enum_style(bindgen::EnumVariation::ModuleConsts)
        .layout_tests(false)
        .generate_comments(false)
        .generate()?;

    bindings.write_to_file(&out)?;
    println!("cargo::warning=regenerated {}", out.display());
    Ok(())
}

/// Derive `<nvtx-checkout>/c/include` from the `nvidia-nvtx` git-dep manifest.
#[cfg(feature = "regenerate-bindings")]
fn locate_nvtx_include() -> Result<std::path::PathBuf, Box<dyn std::error::Error>> {
    let metadata = cargo_metadata::MetadataCommand::new().exec()?;
    let pkg = metadata
        .packages
        .iter()
        .find(|p| p.name.as_str() == "nvidia-nvtx")
        .ok_or("nvidia-nvtx git-dep not found in cargo metadata (regenerate-bindings)")?;
    // manifest_path: <checkout>/rust/Cargo.toml → repo root two levels up.
    let repo_root = pkg
        .manifest_path
        .parent()
        .and_then(|p| p.parent())
        .ok_or("unexpected nvidia-nvtx manifest layout")?;
    Ok(repo_root.as_std_path().join("c/include"))
}

/// Compile the strong-symbol C shim for the static-injection attach path (D-15).
#[cfg(feature = "static-injection")]
fn compile_symbol_shim() {
    println!("cargo::rerun-if-changed=c/symbol.c");
    cc::Build::new()
        .file("c/symbol.c")
        .compile("quent_nvtx_symbol");
}
