// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! CXX bridge for the query engine C++ integration example.
//!
//! The bridge modules are generated by quent-codegen during build.rs
//! into OUT_DIR so that cargo fmt does not need to resolve them.

#[allow(unused, clippy::all)]
mod bridge {
    include!(concat!(env!("OUT_DIR"), "/bridge_mod.rs"));
}
