/* automatically generated by rust-bindgen 0.72.1 */

// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
//! Committed bindgen output for the NVTX injection ABI (D-14).
//!
//! Generated by `build.rs` under the `regenerate-bindings` feature from the
//! pinned NVIDIA/NVTX headers (`c/include/nvtx3/nvToolsExt.h`, rev v3.5.0 /
//! 7d113f290f89eeeae9c957011c497101f3948d9e). Do NOT edit by hand; re-run
//! `cargo build -p quent-nvtx-injection --features regenerate-bindings` after an
//! NVTX `rev` bump. Committed so default and CI builds need no libclang and
//! fetch no NVTX git source.
#![allow(nonstandard_style, dead_code)]

pub const NVTX_VERSION: u32 = 3;
pub const NVTX_SUCCESS: u32 = 0;
pub const NVTX_FAIL: u32 = 1;
pub const NVTX_ERR_INIT_LOAD_PROPERTY: u32 = 2;
pub const NVTX_ERR_INIT_ACCESS_LIBRARY: u32 = 3;
pub const NVTX_ERR_INIT_LOAD_LIBRARY: u32 = 4;
pub const NVTX_ERR_INIT_MISSING_LIBRARY_ENTRY_POINT: u32 = 5;
pub const NVTX_ERR_INIT_FAILED_LIBRARY_ENTRY_POINT: u32 = 6;
pub const NVTX_ERR_NO_INJECTION_LIBRARY_AVAILABLE: u32 = 7;
pub const NVTX_RESOURCE_CLASS_GENERIC: u32 = 1;
pub const NVTX_INIT_STATE_FRESH: u32 = 0;
pub const NVTX_INIT_STATE_STARTED: u32 = 1;
pub const NVTX_INIT_STATE_COMPLETE: u32 = 2;
pub const NVTX_BUFSIZE: u32 = 16384;
pub const NVTX_LOAD_SEQUENCE_VERSION: u32 = 2;
pub const NVTX_SUPPORT_ALREADY_INJECTED_LIBRARY: u32 = 0;
pub const NVTX_SUPPORT_ENV_VARS: u32 = 1;
pub const NVTX_SUPPORT_DYNAMIC_INJECTION_LIBRARY: u32 = 1;
pub const NVTX_SUPPORT_ANDROID_INJECTION_LIBRARY_IN_PACKAGE: u32 = 0;
pub const NVTX_SUPPORT_STATIC_INJECTION_LIBRARY: u32 = 1;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nvtxDomainRegistration_st {
    _unused: [u8; 0],
}
pub type nvtxDomainRegistration = nvtxDomainRegistration_st;
pub type nvtxDomainHandle_t = *mut nvtxDomainRegistration;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nvtxStringRegistration_st {
    _unused: [u8; 0],
}
pub type nvtxStringRegistration = nvtxStringRegistration_st;
pub type nvtxStringHandle_t = *mut nvtxStringRegistration;
pub mod nvtxColorType_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const NVTX_COLOR_UNKNOWN: Type = 0;
    pub const NVTX_COLOR_ARGB: Type = 1;
}
pub mod nvtxMessageType_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const NVTX_MESSAGE_UNKNOWN: Type = 0;
    pub const NVTX_MESSAGE_TYPE_ASCII: Type = 1;
    pub const NVTX_MESSAGE_TYPE_UNICODE: Type = 2;
    pub const NVTX_MESSAGE_TYPE_REGISTERED: Type = 3;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union nvtxMessageValue_t {
    pub ascii: *const ::std::os::raw::c_char,
    pub unicode: *const wchar_t,
    pub registered: nvtxStringHandle_t,
}
pub mod nvtxPayloadType_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const NVTX_PAYLOAD_UNKNOWN: Type = 0;
    pub const NVTX_PAYLOAD_TYPE_UNSIGNED_INT64: Type = 1;
    pub const NVTX_PAYLOAD_TYPE_INT64: Type = 2;
    pub const NVTX_PAYLOAD_TYPE_DOUBLE: Type = 3;
    pub const NVTX_PAYLOAD_TYPE_UNSIGNED_INT32: Type = 4;
    pub const NVTX_PAYLOAD_TYPE_INT32: Type = 5;
    pub const NVTX_PAYLOAD_TYPE_FLOAT: Type = 6;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nvtxEventAttributes_v2 {
    pub version: u16,
    pub size: u16,
    pub category: u32,
    pub colorType: i32,
    pub color: u32,
    pub payloadType: i32,
    pub reserved0: i32,
    pub payload: nvtxEventAttributes_v2_payload_t,
    pub messageType: i32,
    pub message: nvtxMessageValue_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union nvtxEventAttributes_v2_payload_t {
    pub ullValue: u64,
    pub llValue: i64,
    pub dValue: f64,
    pub uiValue: u32,
    pub iValue: i32,
    pub fValue: f32,
}
pub type nvtxEventAttributes_t = nvtxEventAttributes_v2;
pub type NvtxGetExportTableFunc_t = ::std::option::Option<
    unsafe extern "C" fn(exportTableId: u32) -> *const ::std::os::raw::c_void,
>;
pub mod NvtxCallbackModule {
    pub type Type = ::std::os::raw::c_uint;
    pub const NVTX_CB_MODULE_INVALID: Type = 0;
    pub const NVTX_CB_MODULE_CORE: Type = 1;
    pub const NVTX_CB_MODULE_CUDA: Type = 2;
    pub const NVTX_CB_MODULE_OPENCL: Type = 3;
    pub const NVTX_CB_MODULE_CUDART: Type = 4;
    pub const NVTX_CB_MODULE_CORE2: Type = 5;
    pub const NVTX_CB_MODULE_SYNC: Type = 6;
    pub const NVTX_CB_MODULE_SIZE: Type = 7;
    pub const NVTX_CB_MODULE_FORCE_INT: Type = 2147483647;
}
pub mod NvtxCallbackIdCore {
    pub type Type = ::std::os::raw::c_uint;
    pub const NVTX_CBID_CORE_INVALID: Type = 0;
    pub const NVTX_CBID_CORE_MarkEx: Type = 1;
    pub const NVTX_CBID_CORE_MarkA: Type = 2;
    pub const NVTX_CBID_CORE_MarkW: Type = 3;
    pub const NVTX_CBID_CORE_RangeStartEx: Type = 4;
    pub const NVTX_CBID_CORE_RangeStartA: Type = 5;
    pub const NVTX_CBID_CORE_RangeStartW: Type = 6;
    pub const NVTX_CBID_CORE_RangeEnd: Type = 7;
    pub const NVTX_CBID_CORE_RangePushEx: Type = 8;
    pub const NVTX_CBID_CORE_RangePushA: Type = 9;
    pub const NVTX_CBID_CORE_RangePushW: Type = 10;
    pub const NVTX_CBID_CORE_RangePop: Type = 11;
    pub const NVTX_CBID_CORE_NameCategoryA: Type = 12;
    pub const NVTX_CBID_CORE_NameCategoryW: Type = 13;
    pub const NVTX_CBID_CORE_NameOsThreadA: Type = 14;
    pub const NVTX_CBID_CORE_NameOsThreadW: Type = 15;
    pub const NVTX_CBID_CORE_SIZE: Type = 16;
    pub const NVTX_CBID_CORE_FORCE_INT: Type = 2147483647;
}
pub mod NvtxCallbackIdCore2 {
    pub type Type = ::std::os::raw::c_uint;
    pub const NVTX_CBID_CORE2_INVALID: Type = 0;
    pub const NVTX_CBID_CORE2_DomainMarkEx: Type = 1;
    pub const NVTX_CBID_CORE2_DomainRangeStartEx: Type = 2;
    pub const NVTX_CBID_CORE2_DomainRangeEnd: Type = 3;
    pub const NVTX_CBID_CORE2_DomainRangePushEx: Type = 4;
    pub const NVTX_CBID_CORE2_DomainRangePop: Type = 5;
    pub const NVTX_CBID_CORE2_DomainResourceCreate: Type = 6;
    pub const NVTX_CBID_CORE2_DomainResourceDestroy: Type = 7;
    pub const NVTX_CBID_CORE2_DomainNameCategoryA: Type = 8;
    pub const NVTX_CBID_CORE2_DomainNameCategoryW: Type = 9;
    pub const NVTX_CBID_CORE2_DomainRegisterStringA: Type = 10;
    pub const NVTX_CBID_CORE2_DomainRegisterStringW: Type = 11;
    pub const NVTX_CBID_CORE2_DomainCreateA: Type = 12;
    pub const NVTX_CBID_CORE2_DomainCreateW: Type = 13;
    pub const NVTX_CBID_CORE2_DomainDestroy: Type = 14;
    pub const NVTX_CBID_CORE2_Initialize: Type = 15;
    pub const NVTX_CBID_CORE2_SIZE: Type = 16;
    pub const NVTX_CBID_CORE2_FORCE_INT: Type = 2147483647;
}
pub mod NvtxExportTableID {
    pub type Type = ::std::os::raw::c_uint;
    pub const NVTX_ETID_INVALID: Type = 0;
    pub const NVTX_ETID_CALLBACKS: Type = 1;
    pub const NVTX_ETID_RESERVED0: Type = 2;
    pub const NVTX_ETID_VERSIONINFO: Type = 3;
    pub const NVTX_ETID_SIZE: Type = 4;
    pub const NVTX_ETID_FORCE_INT: Type = 2147483647;
}
pub type NvtxFunctionPointer = ::std::option::Option<unsafe extern "C" fn()>;
pub type NvtxFunctionTable = *mut *mut NvtxFunctionPointer;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NvtxExportTableCallbacks {
    pub struct_size: usize,
    pub GetModuleFunctionTable: ::std::option::Option<
        unsafe extern "C" fn(
            callback_module: NvtxCallbackModule::Type,
            out_table: *mut NvtxFunctionTable,
            out_size: *mut ::std::os::raw::c_uint,
        ) -> ::std::os::raw::c_int,
    >,
}
