// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinatorTimestamps } from "./CoordinatorTimestamps";

/**
 * A Coordinator is an entity that orchestrates the execution of a distinct set of queries.
 */
export type Coordinator = { 
/**
 * The ID of this Coordinator
 */
id: string, 
/**
 * The ID of the Engine this Coordinator was spawned in
 */
engine_id: string, 
/**
 * Timestamps of state transitions throughout the lifetime of the Coordinator.
 */
timestamps: CoordinatorTimestamps, };
