// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Timestamps (nanoseconds since Unix epoch) of state transitions of a Coordinator.
 */
export type CoordinatorTimestamps = { 
/**
 * The time at which the Coordinator started initialization.
 */
init: bigint | null, 
/**
 * The time at which the Coordinator started accepting queries.
 */
operating: bigint | null, 
/**
 * The time at which the Coordinator started shutting down and cleaning up its resources.
 */
finalizing: bigint | null, 
/**
 * The time at which the Coordinator was completely destructed and all resources were freed.
 */
exit: bigint | null, };
