// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Plan edge.
 */
export type Edge = { 
/**
 * The source port id.
 */
source: string, 
/**
 * The target port id.
 */
target: string, };
