// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Engine = { id: string, init: bigint | null, operating: bigint | null, finalizing: bigint | null, exit: bigint | null, };
