// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineTimestamps } from "./EngineTimestamps";

/**
 * An Engine represents the top-level entity of the model.
 *
 * Engines accept Queries that they pass to Coordinators which in turn orchestrate their execution.
 */
export type Engine = { 
/**
 * The ID of this Engine
 */
id: string, 
/**
 * Timestamps of state transitions throughout the lifetime of the Engine.
 */
timestamps: EngineTimestamps, };
