// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaitingForInputs } from "./WaitingForInputs";

/**
 * Timestamps (nanoseconds since Unix epoch) of state transitions of a Query.
 */
export type OperatorState = { "Init": bigint } | { "WaitingForInputs": WaitingForInputs } | { "Executing": bigint } | { "Blocked": bigint } | { "Finalizing": bigint } | { "Exit": bigint };
