// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatorState } from "./OperatorState";
import type { Port } from "./Port";

export type Operator = { id: string, plan_id: string, name: string | null, ports: Array<Port>, state_sequence: Array<OperatorState>, };
