// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { Operator } from "./Operator";
import type { PlanTimestamps } from "./PlanTimestamps";

/**
 * A Query Plan.
 */
export type Plan = { 
/**
 * The ID of this Query Plan.
 */
id: string, 
/**
 * The ID of the Query this Plan is part of.
 */
query_id: string, 
/**
 * The timestamps of various state transitions during the lifetime of this plan.
 */
timestamps: PlanTimestamps, 
/**
 * The optional parent Plan ID. This is useful if an Engine constructs various
 * types of Plans before execution, sometimes referred to as "lowering".
 * Examples include a logical and physical plan.
 */
parent_id: string | null, 
/**
 * The optional Worker ID of the Worker that executed this Plan.
 *
 * If this Plan was not directly executed on a worker, but merely some level
 * plan in a sequence of lowering stages, then this may be  set to None.
 */
worker_id: string | null, 
/**
 * The Operators of this Plan.
 */
operators: Array<Operator>, 
/**
 * The Edges of this Plan.
 */
edges: Array<Edge>, };
