// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Timestamps of plan state transitions.
 */
export type PlanTimestamps = { 
/**
 * The time at which the Plan started initialization.
 */
init: bigint | null, 
/**
 * The time at which the Plan started execution.
 */
executing: bigint | null, 
/**
 * The time at which Plan execution was completed.
 */
idle: bigint | null, 
/**
 * The time at which the Plan started cleaning up its resources.
 */
finalizing: bigint | null, 
/**
 * The time at which the Worker was completely destructed and all resources
 * were freed.
 */
exit: bigint | null, };
