// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Port of an Operator in a Plan DAG.
 */
export type Port = { 
/**
 * The ID of this Port.
 */
id: string, 
/**
 * Whether this port is an input (or an output).
 */
is_input: boolean, 
/**
 * The name of this Port.
 */
name: string | null, };
