// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryGroupTimestamps } from "./QueryGroupTimestamps";

/**
 * A QueryGroup is an entity that orchestrates the execution of a distinct set of queries.
 *
 * For example, a session in a long-lived multi-user engine could be modeled as a QueryGroup.
 * TODO(johanpel): perhaps this isn't a great name for this concept, consider naming this something else.
 */
export type QueryGroup = { 
/**
 * The ID of this QueryGroup
 */
id: string, 
/**
 * The ID of the Engine this QueryGroup was spawned in
 */
engine_id: string, 
/**
 * Timestamps of state transitions throughout the lifetime of the QueryGroup.
 */
timestamps: QueryGroupTimestamps, 
/**
 * A name for this QueryGroup instance
 */
name: string | null, };
