// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Timestamps (nanoseconds since Unix epoch) of state transitions of a QueryGroup.
 */
export type QueryGroupTimestamps = { 
/**
 * The time at which the QueryGroup started initialization.
 */
init: bigint | null, 
/**
 * The time at which the QueryGroup started accepting queries.
 */
operating: bigint | null, 
/**
 * The time at which the QueryGroup started shutting down and cleaning up its resources.
 */
finalizing: bigint | null, 
/**
 * The time at which the QueryGroup was completely destructed and all resources were freed.
 */
exit: bigint | null, };
