// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Plan } from "./Plan";
import type { QueryTimestamps } from "./QueryTimestamps";

/**
 * A Query.
 */
export type Query = { 
/**
 * The ID of this Query
 */
id: string, 
/**
 * The ID of the QueryGroup orchestrating this query
 */
query_group_id: string, 
/**
 * Timestamps of state transitions throughout the lifetime of the Query.
 */
timestamps: QueryTimestamps, 
/**
 * A name for this Query.
 */
name: string | null, 
/**
 * The plans of this Query.
 */
plans: Array<Plan>, };
