// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryTimestamps } from "./QueryTimestamps";

/**
 * A Coordinator is an entity that orchestrates the execution of a distinct set of queries.
 */
export type Query = { 
/**
 * The ID of this Query
 */
id: string, 
/**
 * The ID of the Coordinator orchestrating this query
 */
coordinator_id: string, 
/**
 * Timestamps of state transitions throughout the lifetime of the Query.
 */
timestamps: QueryTimestamps, };
