// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { List } from "./List";
import type { Struct } from "./Struct";

/**
 * An [`Attribute`] value.
 */
export type Value = number | number | number | bigint | number | number | number | bigint | number | number | string | Struct | List;
