// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A state transition where an Operator is blocked from progressing beceause it is waiting for inputs to arrive.
 */
export type WaitingForInputs = { 
/**
 * The timestamp of this transition.
 */
timestamp: bigint, 
/**
 * The IDs of the Ports this Operator was blocked on.
 */
ports: Array<string>, };
