// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerTimestamps } from "./WorkerTimestamps";

/**
 * A Worker is an entity that executes Query Plans.
 *
 * It is a high-level resource of an Engine.
 * Its lifetime is bounded by the lifetime of an Engine, but it can outlive any other entity.
 */
export type Worker = { 
/**
 * The ID of this Worker.
 */
id: string, 
/**
 * The ID of the Engine that spawned this Worker.
 */
engine_id: string, 
/**
 * Timestamps of state transitions throughout the lifetime of the Worker.
 */
timestamps: WorkerTimestamps, 
/**
 * A name for this Worker instance
 */
name: string | null, };
