// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Timestamps (nanoseconds since Unix epoch) of state transitions of a Worker.
 */
export type WorkerTimestamps = { 
/**
 * The time at which the Worker started initialization.
 */
init: bigint | null, 
/**
 * The time at which the Worker started accepting Plans.
 */
operating: bigint | null, 
/**
 * The time at which the Worker started shutting down and cleaning up its resources.
 */
finalizing: bigint | null, 
/**
 * The time at which the Worker was completely destructed and all resources were freed.
 */
exit: bigint | null, };
