# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Value import Value



class Attribute(BaseModel):
	"""
	 A key-value pair.
	"""
	
	key: str
	value: Value
