# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Span import Span



class BinnedSpan(BaseModel):
	"""
	 A span of time separated into equally-sized bins of time.
	"""
	
	span: Span
	bin_duration: int
	num_bins: int
