# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Value import Value



class CapacityValue(BaseModel):
	"""
	 A Resource Capacity
	"""
	
	name: str
	bound: Value | None
