# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum



class CapacityKindIdentifier(StrEnum):
	Occupancy = "Occupancy"
	Rate = "Rate"


CapacityKind = CapacityKindIdentifier.Occupancy | CapacityKindIdentifier.Rate
