# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .CapacityKind import CapacityKind



class CapacityDecl(BaseModel):
	"""
	 Declaration of a Capacity of a Resource
	"""
	
	name: str
	kind: CapacityKind
