# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class Edge(BaseModel):
	"""
	 A directed edge of a Plan DAG.
	"""
	
	
	"""
	 The ID of the port sourcing data.
	"""
	source: str
	
	"""
	 The ID of the port sinking data.
	"""
	target: str
