# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Attribute import Attribute



class EngineImplementationAttributes(BaseModel):
	"""
	 Attributes describing details about the implementation of this Engine
	"""
	
	
	"""
	 The name of this Engine implementation, e.g. "SiriusDB", "Velox", "DataFusion", etc.
	"""
	name: str | None
	
	"""
	 The version of this Engine implementation, e.g. "13.3.7"
	"""
	version: str | None
	
	"""
	 Arbitrary attributes defined at run time.
	"""
	custom_attributes: list[Attribute]
