# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .EngineImplementationAttributes import EngineImplementationAttributes
from .EngineTimestamps import EngineTimestamps



class Engine(BaseModel):
	"""
	 An Engine represents the top-level entity of the model.
	
	 Engines accept Queries that they pass to Query Groups which in turn orchestrate
	 execution through Plans submitted to Workers.
	
	 Nothing can outlive the lifetime of an Engine.
	 TODO(johanpel): this assumes 0 clock skew, we need to address this in general.
	"""
	
	
	"""
	 The ID of this Engine
	"""
	id: str
	
	"""
	 Timestamps of state transitions throughout the lifetime of the Engine.
	"""
	timestamps: EngineTimestamps
	
	"""
	 The name of this Engine - typically a name for this instance of a specific engine implementation.
	"""
	name: str | None
	
	"""
	 Details about the Engine implementation.
	"""
	implementation: EngineImplementationAttributes | None
