# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class EngineTimestamps(BaseModel):
	"""
	 Timestamps (nanoseconds since Unix epoch) of state transitions of an Engine.
	"""
	
	
	"""
	 The time at which the Engine started initialization.
	"""
	init: int | None
	
	"""
	 The time at which the Engine started accepting queries.
	"""
	operating: int | None
	
	"""
	 The time at which the Engine started shutting down and cleaning up its resources.
	"""
	finalizing: int | None
	
	"""
	 The time at which the Engine was completely destructed and all resources were freed.
	"""
	exit: int | None
