# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum



class EntityRefIdentifier(StrEnum):
	Engine = "Engine"
	QueryGroup = "QueryGroup"
	Query = "Query"
	Plan = "Plan"
	Worker = "Worker"
	Operator = "Operator"
	Port = "Port"
	ResourceGroup = "ResourceGroup"
	Resource = "Resource"

class EntityRefVariantEngine(BaseModel):
	Engine: str

class EntityRefVariantQueryGroup(BaseModel):
	QueryGroup: str

class EntityRefVariantQuery(BaseModel):
	Query: str

class EntityRefVariantPlan(BaseModel):
	Plan: str

class EntityRefVariantWorker(BaseModel):
	Worker: str

class EntityRefVariantOperator(BaseModel):
	Operator: str

class EntityRefVariantPort(BaseModel):
	Port: str

class EntityRefVariantResourceGroup(BaseModel):
	ResourceGroup: str

class EntityRefVariantResource(BaseModel):
	Resource: str

EntityRef = EntityRefVariantEngine | EntityRefVariantQueryGroup | EntityRefVariantQuery | EntityRefVariantPlan | EntityRefVariantWorker | EntityRefVariantOperator | EntityRefVariantPort | EntityRefVariantResourceGroup | EntityRefVariantResource
