# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Engine import Engine
from .Fsm import Fsm
from .Operator import Operator
from .Plan import Plan
from .Port import Port
from .Query import Query
from .QueryGroup import QueryGroup
from .Resource import Resource
from .ResourceGroup import ResourceGroup
from .Worker import Worker



class Entities(BaseModel):
	"""
	 A set of entities stored in maps from entity id -> entity.
	
	 The maps provide an easy way for quick lookups based on entity IDs.
	 This also means the values in the maps are flattened entities.
	 Their relations are solely expressed through IDs serving as references.
	"""
	
	engine: Engine
	workers: { [key in str]?: Worker }
	resource_groups: { [key in str]?: ResourceGroup }
	resources: { [key in str]?: Resource }
	query_groups: { [key in str]?: QueryGroup }
	queries: { [key in str]?: Query }
	plans: { [key in str]?: Plan }
	operators: { [key in str]?: Operator }
	ports: { [key in str]?: Port }
	custom_fsms: { [key in str]?: Fsm }
