# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .State import State



class Fsm(BaseModel):

	id: str
	type_name: str | None
	instance_name: str | None
	state_sequence: list[State]
