# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Struct import Struct


class ListIdentifier(StrEnum):
	U8 = "U8"
	U16 = "U16"
	U32 = "U32"
	U64 = "U64"
	I8 = "I8"
	I16 = "I16"
	I32 = "I32"
	I64 = "I64"
	F32 = "F32"
	F64 = "F64"
	String = "String"
	Struct = "Struct"

class ListVariantU8(BaseModel):
	U8: list[int]

class ListVariantU16(BaseModel):
	U16: list[int]

class ListVariantU32(BaseModel):
	U32: list[int]

class ListVariantU64(BaseModel):
	U64: list[int]

class ListVariantI8(BaseModel):
	I8: list[int]

class ListVariantI16(BaseModel):
	I16: list[int]

class ListVariantI32(BaseModel):
	I32: list[int]

class ListVariantI64(BaseModel):
	I64: list[int]

class ListVariantF32(BaseModel):
	F32: list[float]

class ListVariantF64(BaseModel):
	F64: list[float]

class ListVariantString(BaseModel):
	String: list[str]

class ListVariantStruct(BaseModel):
	Struct: list[Struct]

List = ListVariantU8 | ListVariantU16 | ListVariantU32 | ListVariantU64 | ListVariantI8 | ListVariantI16 | ListVariantI32 | ListVariantI64 | ListVariantF32 | ListVariantF64 | ListVariantString | ListVariantStruct
