# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .OperatorState import OperatorState



class Operator(BaseModel):
	"""
	 An Operator in a Plan DAG.
	"""
	
	
	"""
	 The ID of this Operator.
	"""
	id: str
	
	"""
	 The ID of the Plan this Operator belongs to.
	"""
	parent_plan_id: str
	
	"""
	 A list of Operator IDs in a parent plan (if any) from which this
	 Operator was derived.
	"""
	parent_operator_ids: list[str]
	
	"""
	 The name of this Operator.
	"""
	name: str | None
	
	"""
	 The IDs of the Ports of this operator.
	"""
	ports: list[str]
	
	"""
	 The sequence of states through which this Operator has been
	 executed.
	"""
	state_sequence: list[OperatorState]
