# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .WaitingForInputs import WaitingForInputs


class OperatorStateIdentifier(StrEnum):
	Init = "Init"
	WaitingForInputs = "WaitingForInputs"
	Executing = "Executing"
	Blocked = "Blocked"
	Finalizing = "Finalizing"
	Exit = "Exit"

class OperatorStateVariantInit(BaseModel):
	Init: int

class OperatorStateVariantWaitingForInputs(BaseModel):
	WaitingForInputs: WaitingForInputs

class OperatorStateVariantExecuting(BaseModel):
	Executing: int

class OperatorStateVariantBlocked(BaseModel):
	Blocked: int

class OperatorStateVariantFinalizing(BaseModel):
	Finalizing: int

class OperatorStateVariantExit(BaseModel):
	Exit: int

OperatorState = OperatorStateVariantInit | OperatorStateVariantWaitingForInputs | OperatorStateVariantExecuting | OperatorStateVariantBlocked | OperatorStateVariantFinalizing | OperatorStateVariantExit
