# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class PlanTree(BaseModel):
	"""
	 A tree of Plans.
	
	 Plans under a Query can form a simple tree with a trunk and potentially a
	 single branching point when they are fanned out over workers for distributed
	 engines. Under the Queryy there must be always one top-level Plan (the root
	 of the tree). For example, this could be what in some engines is called a
	 "logical" plan. An engine may then "lower" a Plan to produce a derived Plan,
	 any arbitrary number of times. At some point, at least one worker will
	 execute a Plan, but the model is flexible enough to allow a worker to
	 locally lower the plan further.
	"""
	
	
	"""
	 The Plan ID.
	"""
	id: str
	
	"""
	 The ID of the Query this Plan is logically nested under.
	"""
	query: str | None
	
	"""
	 The ID of the Worker this Plan is local to.
	"""
	worker: str | None
	
	"""
	 The child plan. If this is an empty list, this is a leaf plan.
	"""
	children: list[PlanTree]
