# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Edge import Edge
from .Operator import Operator
from .PlanTimestamps import PlanTimestamps



class Plan(BaseModel):
	"""
	 A Query Plan.
	"""
	
	
	"""
	 The ID of this Query Plan.
	"""
	id: str
	
	"""
	 The ID of the Query this Plan is part of.
	"""
	query_id: str
	
	"""
	 The timestamps of various state transitions during the lifetime of this plan.
	"""
	timestamps: PlanTimestamps
	
	"""
	 The optional parent Plan ID. This is useful if an Engine constructs various
	 types of Plans before execution, sometimes referred to as "lowering".
	 Examples include a logical and physical plan.
	"""
	parent_id: str | None
	
	"""
	 The optional Worker ID of the Worker that executed this Plan.
	
	 If this Plan was not directly executed on a worker, but merely some level
	 plan in a sequence of lowering stages, then this may be  set to None.
	"""
	worker_id: str | None
	
	"""
	 The Operators of this Plan.
	"""
	operators: list[Operator]
	
	"""
	 The Edges of this Plan.
	"""
	edges: list[Edge]
