# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class PlanTimestamps(BaseModel):
	"""
	 Timestamps of plan state transitions.
	"""
	
	
	"""
	 The time at which the Plan started initialization.
	"""
	init: int | None
	
	"""
	 The time at which the Plan started execution.
	"""
	executing: int | None
	
	"""
	 The time at which Plan execution was completed.
	"""
	idle: int | None
	
	"""
	 The time at which the Plan started cleaning up its resources.
	"""
	finalizing: int | None
	
	"""
	 The time at which the Worker was completely destructed and all resources
	 were freed.
	"""
	exit: int | None
