# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Edge import Edge
from .PlanTimestamps import PlanTimestamps



class Plan(BaseModel):
	"""
	 A Query Plan.
	"""
	
	
	"""
	 The ID of this Plan.
	"""
	id: str
	
	"""
	 The name of this Plan.
	"""
	name: str | None
	
	"""
	 The ID of the Query this Plan is part of.
	"""
	query_id: str | None
	
	"""
	 The timestamps of various state transitions during the lifetime of
	 this plan.
	"""
	timestamps: PlanTimestamps
	
	"""
	 The optional parent Plan ID. This is useful if an Engine constructs
	 various types of Plans before execution, sometimes referred to as
	 "lowering". Examples include a logical and physical plan.
	"""
	parent_plan_id: str | None
	
	"""
	 The optional Worker ID of the Worker that executed this Plan.
	
	 If this Plan was not directly executed on a worker, but merely some
	 level plan in a sequence of lowering stages, then this may be set to
	 None.
	"""
	worker_id: str | None
	
	"""
	 The IDs of the Operators that are part of this Plan.
	"""
	operator_ids: list[str]
	
	"""
	 The Edges between Operators of this Plan.
	"""
	edges: list[Edge]
