# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class Port(BaseModel):
	"""
	 A Port of an Operator in a Plan DAG.
	"""
	
	id: str
	parent_operator_id: str
	name: str
