# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class QueryGroupTimestamps(BaseModel):
	"""
	 Timestamps (nanoseconds since Unix epoch) of state transitions of a QueryGroup.
	"""
	
	
	"""
	 The time at which the QueryGroup started initialization.
	"""
	init: int | None
	
	"""
	 The time at which the QueryGroup started accepting queries.
	"""
	operating: int | None
	
	"""
	 The time at which the QueryGroup started shutting down and cleaning up its resources.
	"""
	finalizing: int | None
	
	"""
	 The time at which the QueryGroup was completely destructed and all resources were freed.
	"""
	exit: int | None
