# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Plan import Plan
from .QueryTimestamps import QueryTimestamps



class Query(BaseModel):
	"""
	 A Query.
	"""
	
	
	"""
	 The ID of this Query
	"""
	id: str
	
	"""
	 The ID of the QueryGroup orchestrating this query
	"""
	query_group_id: str
	
	"""
	 Timestamps of state transitions throughout the lifetime of the Query.
	"""
	timestamps: QueryTimestamps
	
	"""
	 A name for this Query.
	"""
	name: str | None
	
	"""
	 The plans of this Query.
	"""
	plans: list[Plan]
