# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .QueryGroupTimestamps import QueryGroupTimestamps



class QueryGroup(BaseModel):
	"""
	 A QueryGroup is an entity that orchestrates the execution of a distinct set of queries.
	
	 For example, a session in a long-lived multi-user engine could be modeled as a QueryGroup.
	 TODO(johanpel): perhaps this isn't a great name for this concept, consider naming this something else.
	"""
	
	
	"""
	 The ID of this QueryGroup
	"""
	id: str
	
	"""
	 The ID of the Engine this QueryGroup was spawned in
	"""
	engine_id: str
	
	"""
	 Timestamps of state transitions throughout the lifetime of the QueryGroup.
	"""
	timestamps: QueryGroupTimestamps
	
	"""
	 A name for this QueryGroup instance
	"""
	name: str | None
