# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class QueryTimestamps(BaseModel):
	"""
	 Timestamps (nanoseconds since Unix epoch) of state transitions of a Query.
	"""
	
	
	"""
	 The time at which the Query started initialization.
	"""
	init: int | None
	
	"""
	 The time at which the Query started planning.
	"""
	planning: int | None
	
	"""
	 The time at which the Query started executing.
	"""
	executing: int | None
	
	"""
	 The time at which the Query was idle.
	
	 In this state, the Query has been processed, but it still potentially occupies
	 resources of the engine to hold a result which is yet to be delivered to the query
	 client.
	"""
	idle: int | None
	
	"""
	 The time at which the Query started shutting down and cleaning up its resources.
	"""
	finalizing: int | None
	
	"""
	 The time at which the Query was completely destructed and all resources were freed.
	"""
	exit: int | None
