# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Entities import Entities
from .PlanTree import PlanTree
from .ResourceTree import ResourceTree



class QueryBundle(BaseModel):

	entities: Entities
	plan_tree: PlanTree
	resource_tree: ResourceTree
	unique_operator_names: list[str]
	unique_entity_names: list[str]
