# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .ResourceOperatingState import ResourceOperatingState


class ResourceStateIdentifier(StrEnum):
	Init = "Init"
	Operating = "Operating"
	Resizing = "Resizing"
	Finalizing = "Finalizing"
	Exit = "Exit"

class ResourceStateVariantInit(BaseModel):
	Init: int

class ResourceStateVariantOperating(BaseModel):
	Operating: ResourceOperatingState

class ResourceStateVariantResizing(BaseModel):
	Resizing: int

class ResourceStateVariantFinalizing(BaseModel):
	Finalizing: int

class ResourceStateVariantExit(BaseModel):
	Exit: int

ResourceState = ResourceStateVariantInit | ResourceStateVariantOperating | ResourceStateVariantResizing | ResourceStateVariantFinalizing | ResourceStateVariantExit
