# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Attribute import Attribute
from .EntityRef import EntityRef
from .Span import Span



class ResourceTimelineUse(BaseModel):

	span: Span
	amounts: list[Attribute]
	entity: EntityRef
