# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .ResourceTimelineUse import ResourceTimelineUse
from .Span import Span



class ResourceTimeline(BaseModel):
	"""
	 A timeline of individual [`ResourceTimelineUse`]s.
	"""
	
	
	"""
	 The span of time for which the usages are included.
	"""
	span: Span
	
	"""
	 The uses, arbitrarily ordered.
	"""
	uses: list[ResourceTimelineUse]
