# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class ResourceGroupTimestamps(BaseModel):
	"""
	 Timestamps (nanoseconds since Unix epoch) of state transitions of a
	 ResourceGroup.
	"""
	
	
	"""
	 The time at which the ResourceGroup started initialization.
	"""
	init: int | None
	
	"""
	 The time at which the ResourceGroup started operating.
	"""
	operating: int | None
	
	"""
	 The time at which the ResourceGroup started shutting down and
	 cleaning up its resources.
	"""
	finalizing: int | None
	
	"""
	 The time at which the ResourceGroup was completely destructed and
	 all resources were freed.
	"""
	exit: int | None
