# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Attribute import Attribute
from .EntityRef import EntityRef
from .ResourceState import ResourceState



class Resource(BaseModel):
	"""
	 A Resource of which its Capacities cannot be resized.
	"""
	
	
	"""
	 The ID of this Resource
	"""
	id: str
	
	"""
	 The name of this Resource
	"""
	name: str | None
	
	"""
	 The scope of this Resource.
	"""
	scope: EntityRef | None
	
	"""
	 The Capacities of this Resource.
	
	 If this is empty, this is Unit resource.
	"""
	capacities: list[Attribute]
	
	"""
	 The sequence of states that this Resource
	"""
	state_sequence: list[ResourceState]
