# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .BinnedSpan import BinnedSpan



class ResourceTimelineBinnedByState(BaseModel):

	
	"""
	 The configuration of the binned timeline.
	"""
	config: BinnedSpan
	
	"""
	 Maps a resource capacity name to a map of a state name to a vector where
	 each element holds an aggregated value of a time bin.
	"""
	capacities_states_values: { [key in str]?: { [key in str]?: list[float] } }
