# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .BinnedSpan import BinnedSpan



class ResourceTimelineBinned(BaseModel):

	config: BinnedSpan
	capacity_values: { [key in str]?: list[float] }
