# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .ResourceTimelineUse import ResourceTimelineUse
from .Span import Span



class ResourceTimeline(BaseModel):

	span: Span
	uses: list[ResourceTimelineUse]
