# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .EntityRef import EntityRef



class ResourceTree(BaseModel):
	"""
	 A tree of references to entities that can hold resources in their scope,
	 with resources as leaf nodes.
	
	 The tree is built from the perspective of a single query. Thus, under the
	 root level, engine, query group and query and query-level plans are
	 siblings.
	"""
	
	
	"""
	 The ID of the Entity representing this node.
	
	 If this is None, this is the root level.
	"""
	item: EntityRef | None
	
	"""
	 The children of this "resource".
	
	 Valid for all items except those of the variant
	 ResourceTreeNodeItem::Resource
	"""
	children: list[ResourceTree]
