# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .CapacityValue import CapacityValue
from .EntityRef import EntityRef
from .Span import Span



class ResourceTimelineUse(BaseModel):
	"""
	 An individual usage of a resource.
	"""
	
	
	"""
	 The span of time in which the resource was utilized.
	"""
	span: Span
	
	"""
	 The amounts of the resource's capacity that was utilized.
	"""
	amounts: list[CapacityValue]
	
	"""
	 The entity that utilized the resource.
	"""
	entity: EntityRef
