# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .CapacityValue import CapacityValue



class ResourceOperatingState(BaseModel):
	"""
	 Attributes of the "Operating" state of a Resource.
	"""
	
	timestamp: int
	capacities: list[CapacityValue]
