# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .EntityRef import EntityRef
from .ResourceGroupTimestamps import ResourceGroupTimestamps



class ResourceGroup(BaseModel):
	"""
	 A Group of Resources.
	"""
	
	
	"""
	 The ID of this Resource Group
	"""
	id: str
	
	"""
	 The name of this Resource Group instance
	"""
	instance_name: str | None
	
	"""
	 The name of this Resource Group type
	"""
	type_name: str | None
	
	"""
	 The scope of this Resource Group
	"""
	scope: EntityRef | None
	
	"""
	 The timestamps of state transitions of this ResourceGroup.
	"""
	timestamps: ResourceGroupTimestamps
