# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class Span(BaseModel):
	"""
	 A span of time represented as a half-open interval [start, end) over discrete timestamps.
	"""
	
	
	"""
	 The start timestamp, inclusive.
	"""
	start: int
	
	"""
	 The end timestamp, exclusive.
	"""
	end: int
