# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Attribute import Attribute
from .EntityRef import EntityRef
from .Use import Use



class State(BaseModel):

	name: str
	uses: list[Use]
	timestamp: int
	attributes: list[Attribute]
	relations: list[EntityRef]
