# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .Attribute import Attribute



class Struct(BaseModel):
	"""
	 A group of [`Attribute`]s.
	"""
	
	list[Attribute]
