# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .List import List
from .Struct import Struct


class ValueIdentifier(StrEnum):
	U8 = "U8"
	U16 = "U16"
	U32 = "U32"
	U64 = "U64"
	I8 = "I8"
	I16 = "I16"
	I32 = "I32"
	I64 = "I64"
	F32 = "F32"
	F64 = "F64"
	String = "String"
	Struct = "Struct"
	List = "List"

class ValueVariantU8(BaseModel):
	U8: int

class ValueVariantU16(BaseModel):
	U16: int

class ValueVariantU32(BaseModel):
	U32: int

class ValueVariantU64(BaseModel):
	U64: int

class ValueVariantI8(BaseModel):
	I8: int

class ValueVariantI16(BaseModel):
	I16: int

class ValueVariantI32(BaseModel):
	I32: int

class ValueVariantI64(BaseModel):
	I64: int

class ValueVariantF32(BaseModel):
	F32: float

class ValueVariantF64(BaseModel):
	F64: float

class ValueVariantString(BaseModel):
	String: str

class ValueVariantStruct(BaseModel):
	Struct: Struct

class ValueVariantList(BaseModel):
	List: List

Value = ValueVariantU8 | ValueVariantU16 | ValueVariantU32 | ValueVariantU64 | ValueVariantI8 | ValueVariantI16 | ValueVariantI32 | ValueVariantI64 | ValueVariantF32 | ValueVariantF64 | ValueVariantString | ValueVariantStruct | ValueVariantList
