# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class WaitingForInputs(BaseModel):
	"""
	 A state transition where an Operator is blocked from progressing beceause it is waiting for inputs to arrive.
	"""
	
	
	"""
	 The timestamp of this transition.
	"""
	timestamp: int
	
	"""
	 The IDs of the Ports this Operator was blocked on.
	"""
	ports: list[str]
