# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum




class WorkerTimestamps(BaseModel):
	"""
	 Timestamps (nanoseconds since Unix epoch) of state transitions of a Worker.
	"""
	
	
	"""
	 The time at which the Worker started initialization.
	"""
	init: int | None
	
	"""
	 The time at which the Worker started accepting Plans.
	"""
	operating: int | None
	
	"""
	 The time at which the Worker started shutting down and cleaning up its resources.
	"""
	finalizing: int | None
	
	"""
	 The time at which the Worker was completely destructed and all resources were freed.
	"""
	exit: int | None
