# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel
from enum import StrEnum

from .WorkerTimestamps import WorkerTimestamps



class Worker(BaseModel):
	"""
	 A Worker is an entity that executes Query Plans.
	
	 It is a high-level resource of an Engine.
	 Its lifetime is bounded by the lifetime of an Engine, but it can outlive any other entity.
	"""
	
	
	"""
	 The ID of this Worker.
	"""
	id: str
	
	"""
	 The ID of the Engine that spawned this Worker.
	"""
	engine_id: str
	
	"""
	 Timestamps of state transitions throughout the lifetime of the Worker.
	"""
	timestamps: WorkerTimestamps
	
	"""
	 A name for this Worker instance
	"""
	name: str | None
