// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Generates the TypeScript bindings for the schema types.
//!
//! Run with `cargo test -p quent-schema --features ts --test export_bindings`.
//! Output is written to `ts/src/generated/` (gitignored): one `.ts` file per
//! type plus an `index.ts` barrel. The whole module compiles to nothing without
//! the `ts` feature.

#![cfg(feature = "ts")]

use std::fs;
use std::path::Path;

use quent_schema::Schema;
use ts_rs::{Config, TS};

const OUT_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/ts/src/generated");

#[test]
fn export_bindings() {
    let out = Path::new(OUT_DIR);
    let cfg = Config::new().with_out_dir(out);
    // Exporting from Schema transitively emits every reachable schema type.
    Schema::export_all(&cfg).expect("export schema bindings");
    write_barrel(out);
}

/// Writes `index.ts` re-exporting every generated `<Type>.ts` (excluding itself)
/// as a type-only export, so consumers can `import type { Schema } from '@quent/schema'`.
fn write_barrel(out: &Path) {
    let mut names: Vec<String> = fs::read_dir(out)
        .expect("read generated dir")
        .filter_map(|entry| {
            let file_name = entry.ok()?.file_name().into_string().ok()?;
            let stem = file_name.strip_suffix(".ts")?;
            (stem != "index").then(|| stem.to_owned())
        })
        .collect();
    names.sort();

    let mut contents = String::from(
        "// Generated by the quent-schema `export_bindings` test. Do not edit this file manually.\n",
    );
    for name in &names {
        contents.push_str(&format!("export type {{ {name} }} from \"./{name}\";\n"));
    }
    fs::write(out.join("index.ts"), contents).expect("write index.ts barrel");
}
