[package]
name = "quent-io-callback"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
quent-events = { path = "../../events" }
quent-io-types = { path = "../types" }
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
