[package]
name = "quent-instrumentation-build-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
quent-instrumentation = { path = "../../instrumentation", features = ["io-callback", "io-ndjson"] }
serde = { version = "1", features = ["derive"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Threading"] }

[build-dependencies]
quent-instrumentation-build = { path = ".." }
quent-yaml = { path = "../../yaml" }
