[package]
name = "quent-instrumentation-build-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
quent-instrumentation = { path = "../../instrumentation", features = ["io-callback", "io-ndjson"] }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
quent-instrumentation-build = { path = ".." }
quent-yaml = { path = "../../yaml" }
