[package]
name = "quent-codegen"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
quent-yaml.workspace = true
semver.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
