// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Proc macros for defining Quent application models.
//!
//! Four derive macros replace the former `#[quent_model(...)]` attribute:
//!
//! ```ignore
//! #[derive(State)]
//! pub struct Planning;
//!
//! #[derive(Fsm)]
//! pub struct MyFsm {
//!     #[entry] #[to(exit)]
//!     init: Init,
//! }
//!
//! #[derive(Entity)]
//! pub struct Engine {
//!     #[event]
//!     init: Init,
//! }
//!
//! #[derive(Entity, ResourceGroup)]
//! #[resource_group(root)]
//! pub struct Engine {
//!     #[event]
//!     init: Init,
//! }
//! ```

use proc_macro::TokenStream;

mod entity;
mod fsm;
mod resource_group;
mod state;
mod util;

/// Derive macro for FSM state structs.
///
/// Field-level attributes:
/// - `#[usage]` — marks a `Usage<T>` resource usage field
/// - `#[deferred]` — marks an `Option<T>` deferred field
/// - `#[capacity]` — marks a numeric capacity field
/// - `#[instance_name]` — marks the field carrying the instance name
#[proc_macro_derive(State, attributes(usage, deferred, capacity, instance_name))]
pub fn derive_state(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    state::expand_derive(input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

/// Derive macro for FSM definitions.
///
/// The struct must have named fields where each field's type is a state type.
/// Field-level attributes:
/// - `#[entry]` — marks this state as an entry point
/// - `#[to(StateA, StateB, exit)]` — declares transitions from this state
///
/// Struct-level attributes (optional):
/// - `#[resource(capacity = T)]` — marks this FSM as a resource
/// - `#[resource_group]` / `#[resource_group(root)]` — resource group metadata
#[proc_macro_derive(Fsm, attributes(entry, to, resource, resource_group))]
pub fn derive_fsm(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    fsm::expand_derive(input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

/// Derive macro for entity definitions.
///
/// Field-level attributes:
/// - `#[event]` — marks a field as an event type for this entity
///
/// Struct-level attributes (optional):
/// - `#[resource_group]` / `#[resource_group(root)]` — resource group metadata
///
/// If no `#[event]` fields are present, generates a simple (instant) entity.
#[proc_macro_derive(Entity, attributes(event, resource_group))]
pub fn derive_entity(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    entity::expand_derive(input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}

/// Derive macro for resource group definitions.
///
/// Generates the `ResourceGroup` trait impl. When combined with `Entity` or
/// `Fsm` derives, the ModelComponent is generated by those derives (they
/// detect `#[resource_group]`). When used standalone, also generates
/// ModelComponent.
///
/// Struct-level attributes:
/// - `#[resource_group]` — normal resource group (defaults to non-root)
/// - `#[resource_group(root)]` — marks as the root resource group
#[proc_macro_derive(ResourceGroup, attributes(resource_group))]
pub fn derive_resource_group(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    resource_group::expand_derive(input)
        .unwrap_or_else(|e| e.to_compile_error())
        .into()
}
