[package]
name = "quent-readme-example"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
quent-instrumentation = { path = "../../crates/instrumentation", features = ["io-ndjson"] }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
quent-instrumentation-build = { path = "../../crates/instrumentation-build" }
quent-yaml = { path = "../../crates/yaml" }
