// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Lowering from the deserialized model to a schema.
//!
//! Lowering deliberately avoids the usual `Result`/`?` path, which would stop
//! at the first error. Instead each function reports any problems into one
//! shared sink and carries on, returning what it built or `None` to skip an
//! invalid element. A single run can therefore surface problems across
//! independent declarations. Whether it succeeded is decided by the caller
//! from the sink, not from a `Result`.
//!
//! Constraint and metadata payloads are opaque: attached as written, never
//! interpreted.

use indexmap::IndexMap;
use quent_constraints::Constraint;
use quent_fsm::{FsmConstraint, FsmEntityBuilder, FsmEntityBuilderError, StateDecl};
use quent_ref_target::RefTargetConstraint;
use quent_ref_tree::RefTreeConstraint;
use quent_resource::{Capacity, Resource, ResourceBuilder};
use quent_schema::builder::{
    AnnotationsBuilder, BuilderError, EntityBuilder, EventBuilder, RecordBuilder, SchemaBuilder,
};
use quent_schema::{
    Annotations, Cardinality, DataType, Entity, Field, Identifier, Path, Record, Schema,
};
use serde::Deserialize;

use crate::ast::{self, AnnotationMap, Model, TypeExpr};
use crate::diag::Diagnostics;

/// Lower `model` to a schema, reporting problems into `sink`.
///
/// Lowering proceeds in the following phases:
///
/// - Validate the format and model name, then collect resource usage-record
///   names.
/// - Lower declared records.
/// - Lower entities and collect records generated by their resources.
/// - Lower FSM declarations into entities and collect their generated records.
/// - Insert the records, attach the entities and model annotations, and build
///   the schema.
///
/// Recoverable errors do not stop later phases, allowing one run to report
/// multiple problems. A returned schema is meaningful only when `sink`
/// contains no errors. Returns `None` when no schema can be built.
pub(crate) fn lower(model: &Model, sink: &mut Diagnostics) -> Option<Schema> {
    // Validate model-level inputs and prepare resource name resolution.
    if model.quent != "alpha" {
        sink.error(
            "quent",
            format!("unsupported format version `{}`", model.quent),
            Some("supported versions: alpha".to_string()),
        );
    }

    let name = ident(&model.model, "model", sink);
    let resources = ResourceLowerer::new(model, sink);

    // Lower declared records.
    let mut records: Vec<Record> = model
        .records
        .iter()
        .filter_map(|(name, record)| record_of(name, record, &resources, sink))
        .collect();

    // Lower entities and their generated resource records.
    let mut entities: Vec<Entity> = Vec::new();
    for (name, entity) in &model.entities {
        if let Some((entity, generated)) = entity_of(name, entity, &resources, sink) {
            entities.push(entity);
            records.extend(generated);
        }
    }

    // Lower FSM declarations into entities and generated records.
    for (name, spec) in &model.fsms {
        if model.entities.contains_key(name) {
            sink.error(
                &format!("fsms.{name}"),
                format!("`{name}` is declared as both an entity and an FSM"),
                None,
            );
            continue;
        }
        if let Some((entity, generated)) = fsm_entity_of(name, spec, &resources, sink) {
            entities.push(entity);
            records.extend(generated);
        }
    }

    let schema = SchemaBuilder::new(name?)
        .with_records(records)
        .with_entities(entities)
        .with_annotations(annotations(
            &model.doc,
            &model.constraints,
            &model.metadata,
            "",
            sink,
        ))
        .build();
    match schema {
        Ok(schema) => Some(schema),
        Err(error) => {
            schema_builder_diagnostics(&error, sink);
            None
        }
    }
}

fn schema_builder_diagnostics(error: &BuilderError, sink: &mut Diagnostics) {
    match error {
        BuilderError::DuplicateName(name) => {
            sink.error("", format!("duplicate type path `{name}`"), None)
        }
        error => sink.error("", error.to_string(), None),
    }
}

/// Lower one record, or `None` (after reporting) if its name is rejected.
///
/// Fields are lowered for their diagnostics even when the name is bad, but a
/// bad name skips the record so no placeholder identifier reaches the builder.
fn record_of(
    name: &str,
    record: &ast::Record,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<Record> {
    let path = format!("records.{name}");
    let id = type_decl_ident(name, "records", sink);
    let fields = fields_of(&record.fields, &path, resources, sink);
    let record = RecordBuilder::new(id?)
        .with_fields(fields)
        .with_annotations(annotations(
            &record.doc,
            &record.constraints,
            &record.metadata,
            &path,
            sink,
        ))
        .build();
    build_or_diagnose(record, &path, sink)
}

/// Lower one entity and any records generated by its resource declaration.
fn entity_of(
    name: &str,
    entity: &ast::Entity,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<(Entity, Vec<Record>)> {
    let path = format!("entities.{name}");
    let id = type_decl_ident(name, "entities", sink);

    let mut anns = annotations_builder(
        &entity.doc,
        &entity.constraints,
        &entity.metadata,
        &path,
        sink,
    );

    let (records, bounds_record, resource_constraint) = match (id.clone(), &entity.resource) {
        (Some(id), Some(resource)) => resources.lower(name, id, resource, &path, sink),
        _ => (Vec::new(), None, None),
    };
    if let Some(data) = resource_constraint {
        anns = anns.with_constraint(Resource::NAME, Some(data));
    }

    let events: Vec<_> = entity
        .events
        .iter()
        .filter_map(|(event_name, event)| {
            event_of(
                event_name,
                event,
                &path,
                bounds_record.as_ref(),
                resources,
                sink,
            )
        })
        .collect();
    match EntityBuilder::new(id?)
        .with_events(events)
        .with_annotations(build_or_diagnose(anns.build(), &path, sink).unwrap_or_default())
        .build()
    {
        Ok(entity) => Some((entity, records)),
        Err(BuilderError::NoEvents) => {
            sink.error(
                &path,
                format!("entity `{name}` declares no events"),
                Some("entities must declare at least one event".to_string()),
            );
            None
        }
        Err(error) => {
            sink.error(&path, error.to_string(), None);
            None
        }
    }
}

/// Lower an FSM entity and any records generated by its resource declaration.
///
/// Its states become entity events with cardinality derived from the topology.
/// Invalid FSMs are reported and skipped.
fn fsm_entity_of(
    name: &str,
    spec: &ast::FsmSpec,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<(Entity, Vec<Record>)> {
    let path = format!("fsms.{name}");
    let id = type_decl_ident(name, "fsms", sink);
    let mut anns = annotations_builder(&spec.doc, &spec.constraints, &spec.metadata, &path, sink);

    let (records, bounds_record, resource_constraint) = match (id.clone(), &spec.resource) {
        (Some(id), Some(resource)) => resources.lower(name, id, resource, &path, sink),
        _ => (Vec::new(), None, None),
    };
    if let Some(data) = resource_constraint {
        anns = anns.with_constraint(Resource::NAME, Some(data));
    }

    // Lower the states first, before bailing on a rejected entity name, so one
    // run still reports problems inside the states.
    let mut states = Vec::new();
    let mut complete = true;
    for (state_name, state) in &spec.states {
        let Some(state_id) = ident(state_name, &path, sink) else {
            complete = false;
            continue;
        };
        let attributes = event_fields(
            &state.attributes,
            &format!("{path}.states.{state_name}"),
            bounds_record.as_ref(),
            resources,
            sink,
        );
        // The reserved target `exit` transitions out of the FSM; the rest are
        // transitions to other states.
        let mut exit = false;
        let mut to = Vec::new();
        for target in &state.to {
            if target.eq_ignore_ascii_case("exit") {
                exit = true;
            } else if let Some(id) = ident(target, &path, sink) {
                to.push(id);
            }
        }
        states.push(StateDecl {
            name: state_id,
            attributes,
            to,
            initial: state.initial,
            exit,
        });
    }

    // A rejected state name leaves a reduced set whose structural checks would
    // mislead (e.g. reporting a missing initial state), so stop once one is bad.
    let id = id?;
    if !complete {
        return None;
    }

    let built = FsmEntityBuilder::new(id)
        .with_annotations(build_or_diagnose(anns.build(), &path, sink).unwrap_or_default())
        .with_states(states)
        .build();
    match built {
        Ok(entity) => Some((entity, records)),
        Err(error) => {
            fsm_shape_error(&error, &path, sink);
            None
        }
    }
}

/// Report an FSM structural error in the YAML's own terms (`initial: true`,
/// transitioning to `exit`).
fn fsm_shape_error(error: &FsmEntityBuilderError, path: &str, sink: &mut Diagnostics) {
    match error {
        FsmEntityBuilderError::NoInitialState => {
            sink.error(path, "no state marked `initial: true`", None);
        }
        FsmEntityBuilderError::MultipleInitialStates(_) => {
            sink.error(path, "more than one state marked `initial: true`", None);
        }
        FsmEntityBuilderError::NoExitState => {
            sink.error(path, "no state transitions to `exit`", None);
        }
        FsmEntityBuilderError::Invalid(error) => {
            sink.error(path, error.to_string(), None);
        }
        other => sink.error(path, other.to_string(), None),
    }
}

/// Lower one event, including an optional generated resource bounds field.
fn event_of(
    name: &str,
    event: &ast::Event,
    entity_path: &str,
    bounds_record: Option<&Path>,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<quent_schema::Event> {
    let events_path = format!("{entity_path}.events");
    let path = format!("{events_path}.{name}");
    let id = ident(name, &events_path, sink);
    let fields = event_fields(
        &event.attributes,
        &format!("{path}.attributes"),
        bounds_record,
        resources,
        sink,
    );
    let anns = annotations(&event.doc, &event.constraints, &event.metadata, &path, sink);
    let cardinality = if event.multi {
        Cardinality::Multi
    } else {
        Cardinality::Once
    };
    let event = EventBuilder::new(id?, cardinality)
        .with_fields(fields)
        .with_annotations(anns)
        .build();
    build_or_diagnose(event, &path, sink)
}

/// Lower event attributes, including a resource bounds field.
fn event_fields(
    fields: &IndexMap<String, ast::Field>,
    path: &str,
    bounds_record: Option<&Path>,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Vec<Field> {
    let mut lowered = Vec::new();
    for (name, field) in fields {
        let field_path = format!("{path}.{name}");
        let id = ident(name, &field_path, sink);
        match field {
            ast::Field::ResourceBounds(marker) => {
                if marker.sets_resource_bounds {
                    lowered.extend(bounds_field(id, bounds_record, &field_path, sink));
                } else {
                    sink.error(&field_path, "`sets-resource-bounds` must be `true`", None);
                }
            }
            _ => lowered.extend(field_of(id, field, &field_path, resources, sink)),
        }
    }
    lowered
}

fn fields_of(
    fields: &IndexMap<String, ast::Field>,
    path: &str,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Vec<Field> {
    fields
        .iter()
        .filter_map(|(name, field)| {
            let field_path = format!("{path}.{name}");
            let id = ident(name, &field_path, sink);
            field_of(id, field, &field_path, resources, sink)
        })
        .collect()
}

fn field_of(
    id: Option<Identifier>,
    field: &ast::Field,
    path: &str,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<Field> {
    let (ty, ann) = match field {
        ast::Field::Bare(expr) => (
            type_of(expr, path, resources, sink)?,
            Annotations::default(),
        ),
        ast::Field::Full(body) => {
            let ty = type_of(&body.r#type, path, resources, sink)?;
            let ann = annotations(&body.doc, &body.constraints, &body.metadata, path, sink);
            (ty, ann)
        }
        ast::Field::ResourceBounds(_) => {
            sink.error(
                path,
                "`sets-resource-bounds` is only valid in a resource event attribute",
                None,
            );
            return None;
        }
    };
    Some(Field::new(id?, ty, ann))
}

fn type_of(
    expr: &TypeExpr,
    path: &str,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<DataType> {
    match expr {
        TypeExpr::Builtin(b) => Some(builtin_data_type(b)),
        TypeExpr::Record(name) => record_ref(name, path, sink),
        TypeExpr::List(t) => Some(DataType::List(Box::new(type_of(
            &t.list, path, resources, sink,
        )?))),
        TypeExpr::Option(t) => Some(DataType::Option(Box::new(type_of(
            &t.option, path, resources, sink,
        )?))),
        TypeExpr::Ref(f) => entity_ref(&f.r#ref, f.data.as_deref(), false, path, resources, sink),
        TypeExpr::Scope(f) => {
            entity_ref(&f.scope_ref, f.data.as_deref(), true, path, resources, sink)
        }
        TypeExpr::Uses(f) => usage_ref(&f.uses, path, resources, sink),
    }
}

/// An entity reference targeting `target`, optionally carrying `data` and
/// optionally tree-forming.
///
/// The target is stored as the ref-target constraint, and a tree-forming
/// reference also gets the ref-tree marker. Whether `target` names a declared
/// entity and whether the references form a valid tree is checked by
/// validation, not here.
fn entity_ref(
    target: &str,
    data: Option<&TypeExpr>,
    tree: bool,
    path: &str,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<DataType> {
    let data = match data {
        Some(expr) => Some(type_of(expr, path, resources, sink)?),
        None => None,
    };
    entity_ref_type(target, data, tree, path, sink)
}

fn entity_ref_type(
    target: &str,
    data: Option<DataType>,
    tree: bool,
    path: &str,
    sink: &mut Diagnostics,
) -> Option<DataType> {
    let mut builder = AnnotationsBuilder::new()
        .with_constraint(RefTargetConstraint::NAME, Some(target.to_string()));
    if tree {
        builder = builder.with_constraint(RefTreeConstraint::NAME, None);
    }
    Some(DataType::EntityRef {
        data: data.map(Box::new),
        annotations: build_or_diagnose(builder.build(), path, sink).unwrap_or_default(),
    })
}

/// A bare name that is not a [`BuiltinType`], lowered as a record reference.
fn record_ref(name: &str, path: &str, sink: &mut Diagnostics) -> Option<DataType> {
    match Identifier::try_new(name) {
        Ok(id) => Some(DataType::Record(id.into())),
        Err(e) => {
            sink.error(path, format!("invalid type `{name}`: {e}"), None);
            None
        }
    }
}

/// The `DataType` a built-in name denotes.
fn builtin_data_type(builtin: &ast::BuiltinType) -> DataType {
    use ast::BuiltinType::*;
    match builtin {
        Bool => DataType::Bool,
        U8 => DataType::U8,
        U16 => DataType::U16,
        U32 => DataType::U32,
        U64 => DataType::U64,
        I8 => DataType::I8,
        I16 => DataType::I16,
        I32 => DataType::I32,
        I64 => DataType::I64,
        F32 => DataType::F32,
        F64 => DataType::F64,
        String => DataType::String,
        Uuid => DataType::Uuid,
        Dynamic => DataType::DynamicRecord,
        Ref => DataType::EntityRef {
            data: None,
            annotations: Annotations::default(),
        },
    }
}

/// Whether `name` is a [`BuiltinType`] spelling, decided by serde so the enum
/// stays the single source of truth for the reserved names.
fn is_builtin_type(name: &str) -> bool {
    use serde::de::IntoDeserializer;
    let de: serde::de::value::StrDeserializer<serde::de::value::Error> = name.into_deserializer();
    ast::BuiltinType::deserialize(de).is_ok()
}

fn annotations(
    doc: &Option<String>,
    constraints: &AnnotationMap,
    metadata: &AnnotationMap,
    path: &str,
    sink: &mut Diagnostics,
) -> Annotations {
    build_or_diagnose(
        annotations_builder(doc, constraints, metadata, path, sink).build(),
        path,
        sink,
    )
    .unwrap_or_default()
}

fn build_or_diagnose<T>(
    result: Result<T, BuilderError>,
    path: &str,
    sink: &mut Diagnostics,
) -> Option<T> {
    match result {
        Ok(value) => Some(value),
        Err(error) => {
            sink.error(path, error.to_string(), None);
            None
        }
    }
}

fn annotations_builder(
    doc: &Option<String>,
    constraints: &AnnotationMap,
    metadata: &AnnotationMap,
    path: &str,
    sink: &mut Diagnostics,
) -> AnnotationsBuilder {
    let mut builder = match doc {
        Some(doc) => AnnotationsBuilder::new().with_docs(doc),
        None => AnnotationsBuilder::new(),
    };
    for (name, value) in constraints {
        // The FSM constraint is produced only by the builder, from an `fsms:`
        // block, never written by hand.
        if name == FsmConstraint::NAME {
            sink.error(
                path,
                "the FSM constraint is set from an `fsms:` block, not written directly",
                None,
            );
            continue;
        }
        if name == Resource::NAME {
            sink.error(
                path,
                "the resource constraint is set from a `resource:` block, not written directly",
                None,
            );
            continue;
        }
        builder = builder.with_constraint(name, value.clone());
    }
    for (name, value) in metadata {
        builder = builder.with_metadata(name, value.clone());
    }
    builder
}

/// Validate a record/entity name, or `None` (after reporting) if it is invalid
/// or a reserved type name.
///
/// Records and entities are referenced by a bare name, so their names may not
/// shadow a built-in type ([`builtin_type`]). Field and event names are never
/// in type position and use [`ident`] directly.
fn type_decl_ident(name: &str, path: &str, sink: &mut Diagnostics) -> Option<Identifier> {
    if is_builtin_type(name) {
        sink.error(
            path,
            format!("`{name}` is a reserved type name"),
            Some("pick a different name".to_string()),
        );
        return None;
    }
    ident(name, path, sink)
}

fn ident(name: &str, path: &str, sink: &mut Diagnostics) -> Option<Identifier> {
    match Identifier::try_new(name) {
        Ok(id) => Some(id),
        Err(e) => {
            sink.error(path, format!("invalid name `{name}`: {e}"), None);
            None
        }
    }
}

#[derive(Default)]
struct ResourceLowerer {
    usage_records: IndexMap<String, Path>,
}

impl ResourceLowerer {
    fn new(model: &Model, sink: &mut Diagnostics) -> Self {
        let mut lowerer = Self::default();
        for (name, entity) in &model.entities {
            if let Some(resource) = &entity.resource {
                lowerer.add_usage_record(
                    name,
                    resource,
                    &format!("entities.{name}.resource"),
                    sink,
                );
            }
        }
        for (name, fsm) in &model.fsms {
            if let Some(resource) = &fsm.resource {
                lowerer.add_usage_record(name, resource, &format!("fsms.{name}.resource"), sink);
            }
        }
        lowerer
    }

    fn add_usage_record(
        &mut self,
        owner: &str,
        resource: &ast::ResourceDecl,
        path: &str,
        sink: &mut Diagnostics,
    ) {
        let record = match resource.usage_record() {
            Some(name) => ident(name, &format!("{path}.usage-record"), sink).map(Path::from),
            None => ident(owner, path, sink)
                .map(|owner| ResourceBuilder::default_usage_record_path(&owner.into())),
        };
        if let Some(record) = record {
            self.usage_records
                .entry(owner.to_string())
                .or_insert(record);
        }
    }

    fn lower(
        &self,
        owner: &str,
        id: Identifier,
        resource: &ast::ResourceDecl,
        path: &str,
        sink: &mut Diagnostics,
    ) -> (Vec<Record>, Option<Path>, Option<String>) {
        let resource_path = format!("{path}.resource");
        let Some(usage_record_name) = self.usage_records.get(owner).cloned() else {
            return (Vec::new(), None, None);
        };
        let bounds_record_name = match resource.bounds_record() {
            Some(name) => {
                ident(name, &format!("{resource_path}.bounds-record"), sink).map(Path::from)
            }
            None => Some(ResourceBuilder::default_bounds_record_path(
                &id.clone().into(),
            )),
        };
        let Some(bounds_record_name) = bounds_record_name else {
            return (Vec::new(), None, None);
        };

        let mut builder =
            ResourceBuilder::with_record_names(id, usage_record_name, bounds_record_name);
        let capacities = match resource {
            ast::ResourceDecl::Unit(true) => None,
            ast::ResourceDecl::Unit(false) => {
                sink.error(
                    &resource_path,
                    "write `resource: true` for a unit resource, or list capacities",
                    None,
                );
                return (Vec::new(), None, None);
            }
            ast::ResourceDecl::Capacities(capacities) => Some(capacities),
            ast::ResourceDecl::Detailed(spec) => Some(&spec.capacities),
        };
        if let Some(capacities) = capacities {
            for (name, capacity) in capacities {
                if let Some(name) = ident(name, &resource_path, sink) {
                    builder = builder
                        .with_capacity(name, Capacity::new(capacity.kind, capacity.known_bounds));
                }
            }
        }

        match builder.build() {
            Ok(parts) => {
                let constraint = match parts.definition.constraint_data() {
                    Ok(data) => Some(data),
                    Err(error) => {
                        sink.error(&resource_path, error.to_string(), None);
                        None
                    }
                };
                let bounds = parts.bounds.as_ref().map(|record| record.path().clone());
                let mut records = vec![parts.usage];
                records.extend(parts.bounds);
                (records, bounds, constraint)
            }
            Err(error) => {
                sink.error(&resource_path, error.to_string(), None);
                (Vec::new(), None, None)
            }
        }
    }

    fn usage_record(&self, target: &str, path: &str, sink: &mut Diagnostics) -> Option<Path> {
        if let Some(record) = self.usage_records.get(target) {
            return Some(record.clone());
        }
        let target = ident(target, path, sink)?;
        sink.error(
            path,
            format!("`{target}` does not declare a resource"),
            Some("`uses` must name an entity or FSM with a `resource:` declaration".to_string()),
        );
        None
    }
}

/// Build a field carrying the resource's generated bounds record.
///
/// Reports an error when no bounds record is available.
fn bounds_field(
    name: Option<Identifier>,
    bounds_record: Option<&Path>,
    path: &str,
    sink: &mut Diagnostics,
) -> Option<Field> {
    match bounds_record {
        Some(record) => Some(Field::new(
            name?,
            DataType::Record(record.clone()),
            Annotations::default(),
        )),
        None => {
            sink.error(
                path,
                "`sets-resource-bounds` needs a resource with a capacity whose bounds are known",
                None,
            );
            None
        }
    }
}

/// Build a reference claiming capacity from `target`.
///
/// The reference carries the resource's generated usage record. Resource
/// validity is checked during validation.
fn usage_ref(
    target: &str,
    path: &str,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<DataType> {
    let usage = resources.usage_record(target, path, sink)?;
    entity_ref_type(target, Some(DataType::Record(usage)), false, path, sink)
}
