// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Traits for extracting analysis-ready data from model-generated types.
//!
//! These traits are implemented by the proc macros on state and capacity types,
//! enabling the analyzer to extract resource usage information without
//! runtime type dispatch.

use uuid::Uuid;

use crate::ModelBuilder;

/// A capacity value extracted from a state's usage field, ready for analysis.
#[derive(Debug, Clone)]
pub struct ExtractedCapacity {
    pub name: &'static str,
    pub value: Option<u64>,
}

impl ExtractedCapacity {
    pub const fn new(name: &'static str, value: u64) -> Self {
        Self {
            name,
            value: Some(value),
        }
    }

    pub const fn unit() -> Self {
        Self {
            name: "unit",
            value: Some(1),
        }
    }
}

/// A resource usage extracted from a state, ready for analysis.
#[derive(Debug, Clone)]
pub struct ExtractedUsage {
    pub resource_id: Uuid,
    pub capacities: Vec<ExtractedCapacity>,
}

/// Trait for extracting capacity values from a resource's capacity type.
///
/// Generated by `#[quent_model(state)]` for each state type. For unit structs
/// (no fields), returns a single "unit" capacity. For structs with
/// `#[capacity]` fields, returns one capacity per annotated field.
pub trait ExtractCapacities {
    fn extract_capacities(&self) -> Vec<ExtractedCapacity>;
}

/// Trait for extracting resource usages from an FSM state.
///
/// Generated by `#[quent_model(state)]` for states with `#[usage]` fields.
/// Returns one `ExtractedUsage` per usage field.
pub trait ExtractUsages {
    fn extract_usages(&self) -> Vec<ExtractedUsage>;
}

/// Trait for extracting the instance name from an FSM state.
///
/// Generated by `#[quent_model(state)]` when a field is annotated with
/// `#[instance_name]`. Returns `Some(&str)` for states that
/// carry the instance name, `None` for all others.
pub trait ExtractInstanceName {
    fn extract_instance_name(&self) -> Option<&str> {
        None
    }
}

/// Trait for extracting analysis data from a transition enum variant.
///
/// Generated by `#[quent_model::fsm]` on the transition enum. Enables the
/// analyzer to work generically with any model-generated FSM.
pub trait TransitionInfo {
    /// The canonical state name for this transition.
    fn state_name(&self) -> &'static str;

    /// Resource usages for this transition's state data.
    fn usages(&self) -> Vec<ExtractedUsage>;

    /// Instance name if this transition's state carries one.
    fn instance_name(&self) -> Option<&str>;

    /// The FSM type name (snake_case, e.g., "task").
    fn fsm_type_name() -> &'static str;

    /// Collect model metadata for this FSM.
    fn collect_model(builder: &mut ModelBuilder);
}
