// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Traits for extracting analysis-ready data from model-generated types.
//!
//! These traits are implemented by the proc macros on state and capacity types,
//! enabling the analyzer to extract resource usage information without
//! runtime type dispatch.

use quent_attributes::{Attribute, CustomAttributes, List, Struct, Value};
use uuid::Uuid;

use crate::ModelBuilder;
use crate::Ref;

/// A capacity value extracted from a state's usage field, ready for analysis.
#[derive(Debug, Clone)]
pub struct ExtractedCapacity {
    pub name: &'static str,
    pub value: Option<u64>,
}

impl ExtractedCapacity {
    pub const fn new(name: &'static str, value: u64) -> Self {
        Self {
            name,
            value: Some(value),
        }
    }

    pub const fn unit() -> Self {
        Self {
            name: "unit",
            value: Some(1),
        }
    }
}

/// A resource usage extracted from a state, ready for analysis.
#[derive(Debug, Clone)]
pub struct ExtractedUsage {
    pub resource_id: Uuid,
    pub capacities: Vec<ExtractedCapacity>,
}

/// Trait for extracting capacity values from a resource's capacity type.
///
/// Generated by the `state!` macro for each state type. For unit structs
/// (no fields), returns a single "unit" capacity. For structs with
/// `Capacity<V, K>` fields, returns one capacity per detected field.
pub trait ExtractCapacities {
    fn extract_capacities(&self) -> Vec<ExtractedCapacity>;
}

/// Trait for extracting resource usages from an FSM state.
///
/// Generated by the `state!` macro for states with `Usage<T>` fields.
/// Returns one `ExtractedUsage` per usage field.
pub trait ExtractUsages {
    fn extract_usages(&self) -> Vec<ExtractedUsage>;
}

/// Trait for extracting the instance name from an FSM state.
///
/// Generated by the `state!` macro when a field is marked as
/// `instance_name`. Returns `Some(&str)` for states that carry the
/// instance name, `None` for all others.
pub trait ExtractInstanceName {
    fn extract_instance_name(&self) -> Option<&str> {
        None
    }
}

/// Conversion of a state attribute field into an attribute [`Value`].
///
/// Implemented for the field types accepted by the `state!` macro's
/// `attributes:` block. Returns `None` when the field carries no value
/// (e.g. `Option::None`).
pub trait ToAttributeValue {
    fn to_attribute_value(&self) -> Option<Value>;
}

macro_rules! impl_to_attribute_value {
    ($($ty:ty => $variant:ident),* $(,)?) => {
        $(
            impl ToAttributeValue for $ty {
                fn to_attribute_value(&self) -> Option<Value> {
                    Some(Value::$variant(self.clone()))
                }
            }
        )*
    };
}

impl_to_attribute_value! {
    u8 => U8, u16 => U16, u32 => U32, u64 => U64,
    i8 => I8, i16 => I16, i32 => I32, i64 => I64,
    f32 => F32, f64 => F64,
    String => String,
}

macro_rules! impl_to_attribute_value_list {
    ($($ty:ty => $variant:ident),* $(,)?) => {
        $(
            impl ToAttributeValue for Vec<$ty> {
                fn to_attribute_value(&self) -> Option<Value> {
                    Some(Value::List(List::$variant(self.clone())))
                }
            }
        )*
    };
}

impl_to_attribute_value_list! {
    u8 => U8, u16 => U16, u32 => U32, u64 => U64,
    i8 => I8, i16 => I16, i32 => I32, i64 => I64,
    f32 => F32, f64 => F64,
    String => String,
}

// Booleans follow the `CustomAttributes::add_bool` convention: U8 zero/one.
impl ToAttributeValue for bool {
    fn to_attribute_value(&self) -> Option<Value> {
        Some(Value::U8(u8::from(*self)))
    }
}

impl ToAttributeValue for Uuid {
    fn to_attribute_value(&self) -> Option<Value> {
        Some(Value::String(self.to_string()))
    }
}

impl ToAttributeValue for Vec<Uuid> {
    fn to_attribute_value(&self) -> Option<Value> {
        Some(Value::List(List::String(
            self.iter().map(Uuid::to_string).collect(),
        )))
    }
}

impl<T> ToAttributeValue for Ref<T> {
    fn to_attribute_value(&self) -> Option<Value> {
        Some(Value::String(self.uuid().to_string()))
    }
}

impl<T> ToAttributeValue for Vec<Ref<T>> {
    fn to_attribute_value(&self) -> Option<Value> {
        Some(Value::List(List::String(
            self.iter().map(|r| r.uuid().to_string()).collect(),
        )))
    }
}

impl<T: ToAttributeValue> ToAttributeValue for Option<T> {
    fn to_attribute_value(&self) -> Option<Value> {
        self.as_ref().and_then(ToAttributeValue::to_attribute_value)
    }
}

impl ToAttributeValue for CustomAttributes {
    fn to_attribute_value(&self) -> Option<Value> {
        Some(Value::Struct(Struct(self.0.clone())))
    }
}

/// Trait for extracting attribute key-value pairs from an FSM state.
///
/// Generated by the `state!` macro. For inline attributes, yields one
/// [`Attribute`] per declared field (excluding the auto-added
/// `instance_name`, which is surfaced separately via
/// [`ExtractInstanceName`]). For external attribute structs, delegates to
/// the struct's own impl (generated by `#[derive(Attributes)]`).
pub trait ExtractAttributes {
    fn extract_attributes(&self) -> Vec<Attribute>;
}

/// Trait for extracting the parent group ID from an FSM state.
///
/// Generated by the `state!` macro when a field is marked as
/// `parent_group`. Returns `Some(Uuid)` for states that carry the
/// parent group ID, `None` for all others.
pub trait ExtractParentGroupId {
    fn extract_parent_group_id(&self) -> Option<Uuid> {
        None
    }
}

/// Trait for extracting analysis data from a transition enum variant.
///
/// Generated by the `fsm!` macro on the transition enum. Enables the
/// analyzer to work generically with any model-generated FSM.
pub trait TransitionInfo {
    /// The canonical state name for this transition.
    fn state_name(&self) -> &'static str;

    /// Resource usages for this transition's state data.
    fn usages(&self) -> Vec<ExtractedUsage>;

    /// Instance name if this transition's state carries one.
    fn instance_name(&self) -> Option<&str>;

    /// Attribute key-value pairs from this transition's state data.
    ///
    /// Defaults to empty for FSMs whose states carry no attributes
    /// (e.g. resource lifecycle FSMs).
    fn attributes(&self) -> Vec<Attribute> {
        vec![]
    }

    /// Parent group ID if this transition's state carries one.
    fn parent_group_id(&self) -> Option<Uuid>;

    /// The FSM type name (snake_case, e.g., "task").
    fn fsm_type_name() -> &'static str;

    /// Collect model metadata for this FSM.
    fn collect_model(builder: &mut ModelBuilder);
}
