// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Core types for defining Quent application models.
//!
//! This crate provides the foundational types used to define FSMs, resources,
//! entities, and their relationships. Proc macro annotations (provided by
//! `quent-model-macros`) generate instrumentation APIs and metadata from
//! definitions built on these types.

pub mod analyze;
mod capacity;
mod fsm_event;
mod model;
mod r#ref;
mod resource;
mod usage;

// Re-export macros.
pub use quent_model_macros::{
    Attributes, ResizableResource, Resource, entity, fsm, instrumentation, model, resource, state,
};

pub use capacity::{Capacity, Occupancy, Rate};
pub use fsm_event::FsmEvent;
pub use model::{
    AttributeDef, EntityDef, EntityEventDef, FsmDef, Model, ModelBuilder, ModelComponent,
    ResourceGroupDef, StateDef, TransitionDef, TransitionEndpoint, UsageDef, ValueType,
};
pub use r#ref::Ref;
pub use resource::Resource;
pub use usage::{IntoUsage, Usage, usage};

/// Metadata trait for FSM states, generated by the `state!` macro.
///
/// Provides the state's structural metadata (field names, types, which are
/// usages) so the `fsm!` macro can collect it without needing to inspect the
/// state struct directly.
pub trait StateMetadata {
    /// Returns the state definition for model metadata collection.
    fn state_def() -> model::StateDef;

    /// The canonical name of this state (snake_case derived from struct name).
    fn state_name() -> &'static str;
}

/// Marker trait for types declared as entities via the `entity!` macro.
pub trait Entity {}

/// Compatibility name for the shared entity/event association contract.
pub use quent_events::Entity as HasEventType;

/// Associates a model marker type with its analyzer data struct.
///
/// Generated by `entity!`. The data struct has `Option<T>` fields per event
/// type, populated by `push()`.
pub trait EntityData: quent_events::Entity {
    type Data: Default;

    /// Store an event in the data struct.
    fn push(data: &mut Self::Data, event: Self::Event);
}

/// Metadata trait for entity event structs, generated by `#[derive(Attributes)]`.
///
/// Provides the event's structural metadata (field names, types) so the
/// `entity!` macro can populate `EntityEventDef.attributes` without needing
/// to inspect the event struct directly.
pub trait EventMetadata {
    /// Returns the event definition for model metadata collection.
    fn event_def() -> model::EntityEventDef;
}

/// Marker trait for resource groups declared via `entity!` or `fsm!`.
pub trait ResourceGroup {
    /// Whether this is the root resource group (no parent).
    const IS_ROOT: bool = false;
}

// Re-exports referenced by generated instrumentation code and by model consumers.
pub use quent_build_info as build_info;
#[cfg(feature = "collector")]
pub use quent_collector_client::{CollectorSink, deserialize_event};
pub use quent_dynamic_attributes as attributes;
#[doc(hidden)]
pub use quent_events as events;
pub use quent_events::{EntityEvent, Event};
pub use quent_instrumentation::{ContextInner, ObserverInner as Observer, write_sidecar};
pub use quent_io as io;
pub use quent_time::timestamp;
#[cfg(feature = "serde")]
pub use serde;
#[doc(hidden)]
pub use tokio;
pub use uuid;
