// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Core types for defining Quent application models.
//!
//! This crate provides the foundational types used to define FSMs, resources,
//! entities, and their relationships. Proc macro annotations (provided by
//! `quent-model-macros`) generate instrumentation APIs and metadata from
//! definitions built on these types.

pub mod analyze;
mod fsm_event;
mod model;
mod r#ref;
mod resource;
mod usage;

// Re-export the unified proc macro.
// Usage: #[quent_model(state)], #[quent_model(fsm(...))], etc.
pub use quent_model_macros::quent_model;

pub use fsm_event::FsmEvent;
pub use model::{
    AttributeDef, CapacityDef, CapacityType, CapacityValueDef, EntityDef, EntityEventDef, FsmDef,
    Model, ModelBuilder, ModelComponent, ResourceDef, ResourceGroupDef, ResourceKind, StateDef,
    TransitionDef, TransitionEndpoint, UsageDef, ValueType,
};
pub use r#ref::Ref;
pub use resource::Resource;
pub use usage::Usage;

/// Marker trait for types declared as FSM states via `#[quent::state]`.
pub trait State: StateMetadata {}

/// Metadata trait for FSM states, generated by `#[quent::state]`.
///
/// Provides the state's structural metadata (field names, types, which are
/// deferred, which are usages) so the `#[fsm]` macro can collect it without
/// needing to inspect the state struct directly.
pub trait StateMetadata {
    /// The deferred fields enum for this state. If the state has no deferred
    /// fields, this is an uninhabitable enum (empty enum).
    type Deferred: std::fmt::Debug + Clone + serde::Serialize + serde::de::DeserializeOwned;

    /// Returns the state definition for model metadata collection.
    fn state_def() -> model::StateDef;

    /// The canonical name of this state (snake_case derived from struct name).
    fn state_name() -> &'static str;
}

/// Marker trait for types declared as entities via `#[quent::entity]`.
pub trait Entity {}

/// Marker trait for types declared as entity events via `#[quent::event]`.
pub trait EntityEvent {
    /// The entity type this event is associated with.
    type Entity: Entity;
}

/// Marker trait for types declared as resource groups via
/// `#[quent::resource_group]`. Use `#[resource_group(root)]` for the root
/// resource group (no parent).
pub trait ResourceGroup {
    /// Whether this is the root resource group (no parent).
    const IS_ROOT: bool = false;
}

// Re-export instrumentation types needed by generated code.
pub use quent_events::Event;
pub use quent_instrumentation::EventSender;
pub use quent_time::timestamp;

/// Prelude for convenient imports in model definition crates.
pub mod prelude {
    pub use crate::{
        Entity, EntityEvent, Event, EventSender, FsmEvent, Model, ModelBuilder, ModelComponent,
        Ref, Resource, ResourceGroup, State, StateMetadata, Usage, quent_model,
        analyze::{
            ExtractCapacities, ExtractInstanceName, ExtractUsages, ExtractedCapacity,
            ExtractedUsage, TransitionInfo,
        },
    };
    pub use uuid::Uuid;
}
