// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Core types for defining Quent application models.
//!
//! This crate provides the foundational types used to define FSMs, resources,
//! entities, and their relationships. Proc macro annotations (provided by
//! `quent-model-macros`) generate instrumentation APIs and metadata from
//! definitions built on these types.

pub mod analyze;
mod capacity;
mod fsm_event;
mod model;
mod r#ref;
mod resource;
mod usage;

// Re-export derive macros.
pub use quent_model_macros::{Attributes, Entity, Event, Fsm, ResizableResource, Resource, State};

pub use capacity::{Capacity, Occupancy, Rate};
pub use fsm_event::FsmEvent;
pub use model::{
    AttributeDef, EntityDef, EntityEventDef, FsmDef, Model, ModelBuilder, ModelComponent,
    ResourceGroupDef, StateDef, TransitionDef, TransitionEndpoint, UsageDef, ValueType,
};
pub use r#ref::Ref;
pub use resource::Resource;
pub use usage::Usage;

/// Marker type for entity fields that emit an event at most once per instance.
///
/// Used in entity struct definitions to declare event types:
/// ```ignore
/// #[derive(Entity)]
/// pub struct Job {
///     pub submit: EmitOnce<Submit>,
///     pub complete: EmitOnce<Complete>,
/// }
/// ```
///
/// The Entity derive detects `EmitOnce<T>` fields by type and extracts `T`
/// as an event type (which must implement `EventMetadata` via `#[derive(Event)]`).
pub struct EmitOnce<T: EventMetadata>(std::marker::PhantomData<T>);

/// Metadata trait for FSM states, generated by `#[derive(State)]`.
///
/// Provides the state's structural metadata (field names, types, which are
/// usages) so the `#[derive(Fsm)]` macro can collect it without needing to inspect
/// the state struct directly.
pub trait StateMetadata {
    /// Returns the state definition for model metadata collection.
    fn state_def() -> model::StateDef;

    /// The canonical name of this state (snake_case derived from struct name).
    fn state_name() -> &'static str;
}

/// Marker trait for types declared as entities via `#[derive(Entity)]`.
pub trait Entity {}

/// Associates a model marker type with its event type.
///
/// Generated by `#[derive(Fsm)]` and `#[derive(Entity)]`.
/// Used by `define_model!` to auto-generate the top-level event enum.
pub trait HasEventType {
    type Event: std::fmt::Debug + Send + 'static;
}

/// Associates a model marker type with its analyzer data struct.
///
/// Generated by `#[derive(Entity)]`. The data struct has `Option<T>` fields
/// per event type, populated by `push()`.
pub trait EntityData: HasEventType {
    type Data: Default + std::fmt::Debug;

    /// Store an event in the data struct.
    fn push(data: &mut Self::Data, event: Self::Event);
}

/// Metadata trait for entity event structs, generated by `#[derive(Event)]`.
///
/// Provides the event's structural metadata (field names, types) so the
/// entity derive can populate `EntityEventDef.attributes` without needing
/// to inspect the event struct directly.
pub trait EventMetadata {
    /// Returns the event definition for model metadata collection.
    fn event_def() -> model::EntityEventDef;
}

/// Marker trait for resource groups declared via `#[resource_group]` on
/// `#[derive(Entity)]` or `#[derive(Fsm)]`.
pub trait ResourceGroup {
    /// Whether this is the root resource group (no parent).
    const IS_ROOT: bool = false;
}

/// Marker trait for states that have a `#[parent_group]` field.
/// Used by the Fsm derive to enforce that non-root resource group FSMs
/// have a parent group reference on their entry state.
pub trait HasParentGroup {}

// Re-export instrumentation types needed by generated code.
pub use quent_attributes as attributes;
pub use quent_events::Event;
pub use quent_exporter::{self as exporter, ExporterOptions};
pub use quent_instrumentation::Context;
#[doc(hidden)]
pub use quent_instrumentation::EventSender;
pub use quent_time::timestamp;
pub use uuid;

// define_model! is a proc macro — see quent_model_macros::define_model
pub use quent_model_macros::{define_instrumentation, define_model};
