// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Model composition via type alias and tuple recursion.

/// Trait implemented by every model component (FSMs, resources, entities,
/// resource groups).
///
/// Generated by proc macro annotations (`#[quent::fsm]`, `#[quent::resource]`,
/// `#[quent::entity]`, etc.). Each impl contributes its metadata to the
/// `ModelBuilder` when `collect()` is called.
pub trait ModelComponent {
    /// Collects this component's metadata into the builder.
    fn collect(builder: &mut ModelBuilder);
}

/// A composed model. `T` is a tuple of `ModelComponent` types.
///
/// Used as a type alias:
///
/// ```text
/// pub type SimulatorModel = Model<(
///     quent_qe_model::QueryEngineModel,
///     Task,
///     WorkerMemory,
///     Thread,
/// )>;
/// ```
///
/// `Model<T>` itself implements `ModelComponent`, enabling recursive
/// composition: a domain model is a `Model<(...)>` that appears as one
/// element in an application model's tuple.
pub struct Model<T: ModelComponent> {
    _phantom: std::marker::PhantomData<T>,
}

impl<T: ModelComponent> ModelComponent for Model<T> {
    fn collect(builder: &mut ModelBuilder) {
        T::collect(builder);
    }
}

impl<T: ModelComponent> Model<T> {
    /// Collects metadata from all components in this model.
    pub fn build() -> ModelBuilder {
        let mut builder = ModelBuilder::new();
        T::collect(&mut builder);
        builder
    }
}

/// Accumulates model metadata during collection.
///
/// The codegen binary calls `Model::build()` which populates this builder
/// via `ModelComponent::collect()` calls. The builder is then consumed to
/// produce the final resolved model representation.
#[derive(Debug, Default)]
pub struct ModelBuilder {
    pub fsms: Vec<FsmDef>,
    pub resources: Vec<ResourceDef>,
    pub entities: Vec<EntityDef>,
    pub resource_groups: Vec<ResourceGroupDef>,
}

impl ModelBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn add_fsm(&mut self, fsm: FsmDef) {
        self.fsms.push(fsm);
    }

    pub fn add_resource(&mut self, resource: ResourceDef) {
        self.resources.push(resource);
    }

    pub fn add_entity(&mut self, entity: EntityDef) {
        self.entities.push(entity);
    }

    pub fn add_resource_group(&mut self, group: ResourceGroupDef) {
        self.resource_groups.push(group);
    }
}

//------------------------------------------------------------------------
// Model definition types (the in-memory representation)
//------------------------------------------------------------------------

/// An FSM definition.
#[derive(Debug, Clone)]
pub struct FsmDef {
    pub name: String,
    pub states: Vec<StateDef>,
    pub transitions: Vec<TransitionDef>,
}

/// A state definition within an FSM.
#[derive(Debug, Clone)]
pub struct StateDef {
    pub name: String,
    pub attributes: Vec<AttributeDef>,
    pub usages: Vec<UsageDef>,
}

/// A transition between states.
#[derive(Debug, Clone)]
pub struct TransitionDef {
    pub from: TransitionEndpoint,
    pub to: TransitionEndpoint,
}

/// An endpoint in a transition (entry, exit, or a named state).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TransitionEndpoint {
    Entry,
    Exit,
    State(String),
}

/// A resource usage declared on a state.
#[derive(Debug, Clone)]
pub struct UsageDef {
    pub field_name: String,
    pub resource_name: String,
    /// Rust path to the resource marker type (e.g., "quent_stdlib::ProcessorResource").
    /// The codegen uses `<T as Resource>::CapacityValue` to get the operating state type.
    pub resource_type_path: String,
    pub capacities: Vec<CapacityValueDef>,
}

/// A capacity value within a usage.
#[derive(Debug, Clone)]
pub struct CapacityValueDef {
    pub name: String,
    pub value_type: ValueType,
}

/// A resource definition (an FSM marked with `#[quent::resource]`).
#[derive(Debug, Clone)]
pub struct ResourceDef {
    pub name: String,
    pub kind: ResourceKind,
    pub capacities: Vec<CapacityDef>,
}

/// The kind of resource (determined by its FSM structure).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ResourceKind {
    Unit,
    FixedBounds,
    DynamicBounds,
}

/// A capacity declared on a resource.
#[derive(Debug, Clone)]
pub struct CapacityDef {
    pub name: String,
    pub capacity_type: CapacityType,
    pub value_type: ValueType,
    pub bounded: bool,
}

/// Whether a capacity tracks occupancy or rate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CapacityType {
    Occupancy,
    Rate,
}

/// A resource group definition.
#[derive(Debug, Clone)]
pub struct ResourceGroupDef {
    pub name: String,
    /// If set, the parent type is fixed (domain model constraint).
    /// If `None`, the parent is assigned at runtime.
    pub fixed_parent: Option<String>,
    /// Whether this is the root resource group.
    pub is_root: bool,
}

/// A plain entity definition (not an FSM, not a resource).
#[derive(Debug, Clone)]
pub struct EntityDef {
    pub name: String,
    pub events: Vec<EntityEventDef>,
}

/// A one-shot event type associated with an entity.
#[derive(Debug, Clone)]
pub struct EntityEventDef {
    pub name: String,
    pub attributes: Vec<AttributeDef>,
}

/// An attribute on a state, entity, or event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttributeDef {
    pub name: String,
    pub value_type: ValueType,
    pub optional: bool,
}

/// Attribute value types, mapping to the spec's type system.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ValueType {
    Bool,
    Uuid,
    String,
    U8,
    U16,
    U32,
    U64,
    I8,
    I16,
    I32,
    I64,
    F32,
    F64,
    List(Box<ValueType>),
    Struct(Vec<AttributeDef>),
    /// A typed reference to another entity, FSM, or resource.
    /// The string is the referenced type's canonical name.
    Ref(std::string::String),
}

// Unit tuple (base case)
impl ModelComponent for () {
    fn collect(_builder: &mut ModelBuilder) {}
}

macro_rules! impl_model_component_tuple {
    ($($T:ident),+) => {
        impl<$($T: ModelComponent),+> ModelComponent for ($($T,)+) {
            fn collect(builder: &mut ModelBuilder) {
                $($T::collect(builder);)+
            }
        }
    };
}

impl_model_component_tuple!(A);
impl_model_component_tuple!(A, B);
impl_model_component_tuple!(A, B, C);
impl_model_component_tuple!(A, B, C, D);
impl_model_component_tuple!(A, B, C, D, E);
impl_model_component_tuple!(A, B, C, D, E, F);
impl_model_component_tuple!(A, B, C, D, E, F, G);
impl_model_component_tuple!(A, B, C, D, E, F, G, H);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I, J);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I, J, K);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I, J, K, L);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I, J, K, L, M);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I, J, K, L, M, N);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O);
impl_model_component_tuple!(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P);
