// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Resource trait for types that can be referenced via `Usage<T>`.

/// Marker trait for FSMs that represent resources.
///
/// Generated by the `resource!` macro. The associated `CapacityValue`
/// type is derived from the FSM's operating state — it contains the
/// capacity fields that `Usage<T>` expands to.
///
/// For a unit resource (operating state has no fields), `CapacityValue`
/// is `()`.
pub trait Resource {
    /// The capacity value type, derived from the resource FSM's operating
    /// state fields.
    type CapacityValue: Send + 'static;

    /// The snake_case name of this resource (e.g., "processor", "memory").
    /// Used by the State derive to resolve `Usage<T>` field metadata.
    const RESOURCE_NAME: &'static str;
}
