name: Markdown

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".rumdl.toml"
      - ".github/workflows/markdown.yml"
      - "pixi.toml"
      - "pixi.lock"
  pull_request:
    paths:
      - "**/*.md"
      - ".rumdl.toml"
      - ".github/workflows/markdown.yml"
      - "pixi.toml"
      - "pixi.lock"

permissions:
  contents: read

jobs:
  markdown:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        with:
          cache: true
      - run: pixi run --frozen rumdl check --diff
